### ISSUE TITLE
Locale detection not working in Next >=13

### ISSUE THREAD

**Issue by PhilipAngelinNE** [vinissimus/next-translate#1015]
**What version of this package are you using?**

2.0.2

**What operating system, Node.js, and npm version?**

Ubuntu, Node v18.15.0, npm 9.5.0

**What happened?**

The locale detection seems to not be working at all.

**What did you expect to happen?**

It should detect locale based on domain. E.g visiting a `.se` domain sets locale to `sv` and visiting a `.de` domain sets it to `de` etc. 
This has worked fine in Next 12, but ever since upgrading to Next v13 (have tried several versions) it won't work.

**Are you willing to submit a pull request to fix this bug?**

Probably not.

**Comment by aralroca** [comment]
All the routing part (including locale detection) is done in the core of Next.js, not in this library. 

This is the documentation https://nextjs.org/docs/advanced-features/i18n-routing

In next-translate is loading the translations for each page and allows us to consume it in an easy way. However, it does not do any extra job for locale routing. Probably you need to report it directly to Next.js: https://github.com/vercel/next.js/

**Comment by aralroca** [comment]
@PhilipAngelinNE Within [/examples](https://github.com/aralroca/next-translate/tree/master/examples) there are some examples.

I invite you to create a repository that reproduces the error and we will look at it and I will reopen the issue in case it is from the library. 

With Next.js 13:

- If you use `pages` dir: Use the locale of useRouter.
- If you use `app` dir: It goes through the lang parameter of the URL and all the configuration must be done at middleware level.

Both examples are in the repo.

**Comment by aralroca** [comment]
The problem with appDir is that is still in beta and the i18n routing part is missing in Next.js core, take a look at Next.js docs: https://beta.nextjs.org/docs/guides/internationalization#routing-overview 

Probably this is going to change in the future and the middleware will be not needed more. The next-translate docs about this: https://github.com/aralroca/next-translate#14-use-next-13-app-directory
