### ISSUE TITLE
Pass key with no namespace to useTranslation()?

### ISSUE THREAD

**Issue by ekafyi** [vinissimus/next-translate#105]
First of all, thank you for the great work!

[This example](https://github.com/vinissimus/next-translate/blob/master/README.md#usetranslation) in the docs shows it's possible to pass string without namespace into `useTranslation()`, like so:

```js
export default function Description() {
  const { t, lang } = useTranslation()
  const title = t('title') // instead of 'common:title' or 'home:title' etc
   // ...
}
```

Is this possible? What value should I pass to `i18n.json` and what filename should I use for the locale file?

I've also checked the example sites but this usage without namespace is not present in them.

My use case is for common translation which will be used in all pages. I've been able to use common, eg. `{"*": ["common"]}`, but was just wondering if that example is possible because it would be more concise.

Thanks!

**Comment by aralroca** [comment]
It is a mistake on the docs!! You should always reference the namespace! This should be fixed in the docs! Thanks to reporting it!

**Comment by akshitkrnagpal** [comment]
> You should always reference the namespace!

@aralroca Why is this the case? Why can't we set a default namespace and pass just the key?

**Comment by aralroca** [comment]
@akshitkrnagpal in the latest version you would be able to do it. It's already supported:

```js
const { t, lang } = useTranslation('ns1') // default namespace (optional)
const title = t('title') // no need to add the ns1: on front
```

PR: https://github.com/vinissimus/next-translate/pull/335
Issue: https://github.com/vinissimus/next-translate/issues/305
