### ISSUE TITLE
support for windows (rm -rf)

### ISSUE THREAD

**Issue by rafinskipg** [vinissimus/next-translate#113]
Hello, I was trying to set up next-translate while working on windows (😅 ) and it does not remove the 'pages' directory because it does not support 'rm -rf'.

Anyway. Do you think there is another way of doing what this project does, without having to change to another "pages_" structure. It seems a bit odd to change the standard way of development.

Thanks

**Comment by aralroca** [comment]
There is an open PR just for that!  https://github.com/vinissimus/next-translate/pull/111 Duplicated of https://github.com/vinissimus/next-translate/pull/99

Will be fixed on 0.14.2 version 👍

**Comment by aralroca** [comment]
@rafinskipg We released the `0.14.2-canary.2`. Can you try this version and verify that it works now? Thanks 👏

**Comment by rafinskipg** [comment]
Hello @aralroca after seeing the behaviour of having to give up on the standard "pages" way i stopped using this module. I need to evaluate a solution that is not too intrusive. I am still deciding on what to use

**Comment by aralroca** [comment]
Ok @rafinskipg ! I understand, don't worry 👍! This "build step" is a workaround to work with static pages meanwhile we don't found a better solution. As an alternative, you can use a custom server:

* https://github.com/vinissimus/next-translate/blob/master/docs/USING_CUSTOM_SERVER.md

This solution is not intrusive, however you can't take advantage of page optimization.

I would like to listen to your final solution! 👏We want to evolve on 1.0.0 to a robust solution, without workarounds. 🙂
