### ISSUE TITLE
Cannot export as static bundle

### ISSUE THREAD

**Issue by neslinesli93** [vinissimus/next-translate#130]
Hi!
First of all, awesome job you did with this library - keep it up :)

I've been playing with next for the first time, and I'm trying to build a static, localized landing page.

This is an excerpt of my `next.config.js`:

```js
  exportTrailingSlash: true,
  exportPathMap: function () {
    return {
      '/': { page: '/' },
      '/documentation': { page: '/documentation' },
    };
  }
```

When I run `next-translate && next build`, the `pages` folder correctly includes the main pages, as well as the localized subfolders. However, if I run `next export`, all I get is the main pages but no localized versions. If I understand correctly, this use case should be supported. Is there a problem with the config file, where I do not export the localized pages, one by one?

Thank you!

**Comment by aralroca** [comment]
Did you try to do `yarn build && yarn export` without the `exportPathMap` property? It looks not necessary for your use case, and you are doing without the lang paths.

If you are using `next-translate` CLI to build your pages and is working well in localhost, it should work using `yarn export` unless you have a bad configuration on your `next.config.js`...

**Comment by neslinesli93** [comment]
Oh, didn't know that `exportPathMap` had a default value... Now it works like a charm, thank you :)

**Comment by aralroca** [comment]
I'm going to close this issue @neslinesli93 . Feel free to reopen or create a new issue if you get some troubles
