### ISSUE TITLE
How to use Dynamic Routes in Class Component

### ISSUE THREAD

**Issue by dmamira** [vinissimus/next-translate#132]
I use class component in my project.
and I want to use dynamic routes but no examples are available.
How to use Dynamic Routes?

**Comment by aralroca** [comment]
@dmamira in order to use class components instead of functional components you can consume the translations using the `withTranslation` HOC:

https://github.com/vinissimus/next-translate#withtranslation

The other things are just the same than with functional components.

**Comment by dmamira** [comment]
Thank you It works!!

**Comment by aralroca** [comment]
Nice 😊 I'm going to close this issue! Feel free to reopen or create another one if you have more doubts!
