### ISSUE TITLE
HTML "lang" attribute support 

### ISSUE THREAD

**Issue by neslinesli93** [vinissimus/next-translate#133]
Hi,
is it possible to set a custom `lang` attribute for the `html` tag inside a custom `_document.js`, while keeping static site generation support? I think it could be fairly easy to inject it at build time in the generated html...

**Comment by aralroca** [comment]
There isn't any helper of this library right now for this. (Maybe we can consider to add it 🙂). 

Meanwhile, you can handle this with this:

```jsx
import Document, { Html, Head, Main, NextScript } from 'next/document'
import i18nConfig from '../i18n.json'

function documentLang({ __NEXT_DATA__}) {
  const { page } = __NEXT_DATA__
  const [,langQuery] = page.split('/')
  const lang = i18nConfig.allLanguages.find(l => l === langQuery)

  return lang || i18nConfig.defaultLanguage
}

export default class MyDocument extends Document {
  render() {
    return (
      <Html lang={documentLang(this.props)}>
        <Head />
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    )
  }
}

```

**Comment by neslinesli93** [comment]
Thanks for the quick feedback. I was wondering, why it's not possible to use `clientSideLang`? It seems easier and more straightforward...

**Comment by aralroca** [comment]
The reason is that `clientSideLang` is a global variable. In the browser this is not a problem but in node.js it can have conflicts with concurrent users visiting the same page.

**Comment by neslinesli93** [comment]
I'm exporting the next project using static html, so it shouldn't be an issue for this use case. Thanks anyway!

**Comment by aralroca** [comment]
In this case, is not a problem and you can use `clientSideLang` directly.

However, using SSR on some page (`getServerSideProps`) you can have conflicts and the only way is using [documentLang](https://github.com/vinissimus/next-translate/issues/133#issuecomment-619415454), that this works in all cases.

**Comment by aralroca** [comment]
@neslinesli93 on `0.17.0-canary.1` is available the helper:

```js
import Document, { Html, Head, Main, NextScript } from 'next/document'
import documentLang from 'next-translate/documentLang'

export default class MyDocument extends Document {
  render() {
    return (
      <Html lang={documentLang(this.props)}>
        <Head />
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    )
  }
}
```
