### ISSUE TITLE
Router.pushI18n and Router.replaceI18n does not append lang with a custom server

### ISSUE THREAD

**Issue by sbekaert** [vinissimus/next-translate#148]
Hello,

First thanks to next-translate, it provided me the solution to translate my serverless nextjs application.

I met this issue when I try to navigate using the **pushI18n** or **replaceI18n** methods:

> Unhandled Rejection (Error): The provided `as` value (/es/article/my-random-article-2) is incompatible with the `href` value (/article/[id]). Read more: https://err.sh/zeit/next.js/incompatible-href-as

To reproduce it, I created the page **article/[id].js** under the pages directory of the example app **examples/with-server**:

```
import { useState } from 'react';
import Router from 'next-translate/Router';

export const getServerSideProps = async ({ query }) => {
  const { id } = query;

  return {
    props: {
      id,
    },
  };
};

export default function Article({ id }) {
  const [articleId, setArticleId]= useState(id);

  const onClick = () => Router.replaceI18n('/article/[id]', `/article/${articleId}`, { shallow: true });

  return (
    <>
      <h2>Article {id}</h2>
      <div style={{ display: "flex" }}>
        <input type='text' value={articleId} onChange={(e) => setArticleId(e.target.value)} />
        <button onClick={() => onClick()}>Redirect</button>
      </div>
    </>
  )
}
```

It seems that the current lang is not prepended to the href.

Thanks for any help.

**Comment by aralroca** [comment]
Hi @sbekaert, I'm not sure if this error it's from next-translate:

> Unhandled Rejection (Error): The provided as value (/es/article/my-random-article-2) is incompatible with the href value (/article/[id]). Read more: https://err.sh/zeit/next.js/incompatible-href-as

As I see, you are using an incorrect syntax to navigate to a dynamic route. You should pass the id on the `href`. Something like:

```js
function onClick() {
  Router.replaceI18n(`/article/[id]?id=${articleId}`, `/article/${articleId}`, {
    shallow: true,
  })
}
```

Can you try if this solves your problem? The `Router.replaceI18n` should add the lang for you. 

Let me know 😄 And if is something from this lib, we are going to fix it! Thanks 😊

**Comment by sbekaert** [comment]
Hi @aralroca, my bad, it works!

Thanks a lot because I was convinced it was the right way to use replace with dynamic routes.

Thanks again.
