### ISSUE TITLE
No router instance found when using with "next-redux-wrapper"

### ISSUE THREAD

**Issue by RobinSCU** [vinissimus/next-translate#150]
Hi,

I'm not sure if the problem is on your or next-redux-wrapper site, but when I try to combine these two modules I get this error "Error: No router instance found. you should only use "next/router" inside the client side of your app. https://err.sh/zeit/next.js/no-router-instance" by every call, especially by 404 sites.

The Error occurs in this Row of the [...path].js `router.replace(`/en/${router.query.path.join('/')}`)`

I build a little example: https://github.com/RobinSCU/next-translate-with-next-redux-wrapper 

Maybe you can show me what i did wrong.

Thanks
Robin

**Comment by RobinSCU** [comment]
As I understand the default "redirect" is just a cosmetic one in the browser and not a 301 on the server. To fix the error you can add the typeof !== 'undefined' mentioned in https://github.com/zeit/next.js/blob/master/errors/no-router-instance.md. The replace than only happens in the browser and not on the server.

`if(typeof window !== 'undefined'){
   router.replace(\`/${defaultLanguage}/\${router.query.path.join('/')}\`)
 }`

**Comment by aralroca** [comment]
@RobinSCU Sorry it took me so long to answer! I just tested your project. Absolutely right. We might add the `typeof window !== 'undefined'` check!

This should be fixed on the next `0.16.0` version 😊!  Thanks a lot to report it!

**Comment by RobinSCU** [comment]
@aralroca I'm not 100% sure but maybe does the pull request from @Faulik has now the same problem with the getDefaultLanguageIndexRedirectTemplate function.

**Comment by aralroca** [comment]
I included this change also on the PR! I just pre-released `0.16.0-canary.2` with this change if you wanna try. Thanks a lot to report it 👏 !! Your reproducible example was very useful to understand the problem !
