### ISSUE TITLE
How to using mdx

### ISSUE THREAD

**Issue by ng-yt** [vinissimus/next-translate#156]
Using this amazing library, you can use the
I am developing a static site.

If you know of a way to use it in conjunction with this library, please let me know.
https://github.com/zeit/next.js/tree/master/packages/next-mdx

**Comment by aralroca** [comment]
`mdx` extension should be added into the codebase in order to support it.

**Comment by aralroca** [comment]
@ng-yt I added support to `.mdx` on a PR. This will be available on `0.16.0`. However, I upload a prerelease **[0.16.0-canary.5](https://github.com/vinissimus/next-translate/releases/tag/0.16.0-canary.5)** if you want to try it before. Can you confirm that it's working in your case? Thanks!

**Comment by mercale** [comment]
Love this library. Awesome job.  I am also interested in adding MDX, any example on how to do this?
