### ISSUE TITLE
Routing breaks down

### ISSUE THREAD

**Issue by kodermax** [vinissimus/next-translate#165]
![image](https://user-images.githubusercontent.com/590985/82216544-c1a4e080-9921-11ea-9780-38c07692c5f9.png)
routing breaks when we use forbidden characters

**Comment by aralroca** [comment]
Ok, this should be fixed to return 404 page 👍

**Comment by aralroca** [comment]
@kodermax thank you to report this! The PR is already merged, it will be available on `0.16.0` version. However if you want to try it before, it's under the pre-release `0.16.0-canary.6` 😊
