### ISSUE TITLE
Fallback Language support

### ISSUE THREAD

**Issue by SpicyPete** [vinissimus/next-translate#166]
It would be great to have support for fallback translations if the current language locale file is missing a given translation key, but exists on the default language.

**Comment by aralroca** [comment]
The problem of this approach is that it implies downloading at least two language dictionaries instead of only the current language dictionary. So by default I'd keep the current behavior, which is lighter. 

This can be implemented right now outside the library:

**hooks/useTranslationWithFallback.js**:

```js
import useTranslation from 'next-translate/useTranslation'

const fallbacks = {
  'common': 'commonFbk'
}

export default function useTranslationWithFallback() {
  const { t, lang } = useTranslation()

  return {
     t: (ns, key, ...args) => {
       const currentText = `${ns}:${key}`
       const fallbackText = `${fallbacks[ns]}:${key}`
       const currentTranslation = t(currentText, ...args)
       
       if(currentTranslation === currentText) return t(fallbackText, ...args)
       return currentTranslation
     },
     lang,
  }
}
```

**In your page**:

```js
import React from 'react'
import I18nProvider from 'next-translate/I18nProvider'
import useTranslationWithFallback from '../hooks/useTranslationWithFallback'

// Import English common.json as Fallback
import commonFbk from '../locales/en/common.json'

function PageContent() {
  const { t, lang } = useTranslationWithFallback()

  return (
    <div>
      <h1>{t('common', 'title')}</h1>
    </div>
  )
}

export default function Page() {
  const { lang } = useTranslation()

  return (
    <I18nProvider lang={lang} namespaces={{ commonFbk }}>
      <PageContent />
    </I18nProvider>
  )
}
```

If we see that it is a very demanded feature then we will consider introducing this hook and a more comfortable alternative. But for now I would avoid introducing this complexity into the library.

**Comment by SpicyPete** [comment]
Great thank for that snippet, I'll give it a shot.  
In my opinion, fallback languages, or an easy to implement alternative like the above, is a must-have for a i18n library.

**Comment by aralroca** [comment]
Ok, it can be considered as a future feature then.

**Comment by aralroca** [comment]
We added the missing logger now, I hope it helps to detect when a translation is missing

**Comment by sujin-lifology** [comment]
I'm having the same issue any alternative solutions for that ?

**Comment by sujin-lifology** [comment]
@aralroca

**Comment by aralroca** [comment]
maybe overwritting `loadLocaleFrom`:

```js
loadLocaleFrom: async (lang, ns) => {
  const defaultLang = 'es'
  const defaultNs = await import(`./locales/${defaultLang}/${ns}.json`)

  if (lang === defaultLang) return defaultNs
  
  return {
    ...defaultNs,
    ...(await import(`./locales/${lang}/${ns}.json`))
  }
}
````

**Comment by MonstraG** [comment]
Can confirm that this works, here is an updated snipped if you're not guaranteed that file exits, should work exactly like next-18next:
```js
	loadLocaleFrom: async (lang, ns) => {
		const defaultLang = process.env.NEXT_PUBLIC_FALLBACK_LANGUAGE;
		const defaultNs = await import(`./public/static/locales/${defaultLang}/${ns}`).then(
			(x) => x.default
		);

		if (lang === defaultLang) return defaultNs;

		try {
			const localeNs = await import(`./public/static/locales/${lang}/${ns}`).then(
				(x) => x.default
			);
			return { ...defaultNs, ...localeNs };
		} catch (e) {
			// failed to load the locale file (it was not created yet)
			return defaultNs;
		}
	},
```

**Comment by martinbrueckenwirt** [comment]
thanks for your fast reply.

It doesn't exist in my project.
Shall I put it in the node-modules/next-translate folder? Where?

Just for info, I use the app-folder and try to stick to nextjs 13.4.

Martin

Am Sa., 6. Mai 2023 um 09:16 Uhr schrieb Arseny Garelyshev <
***@***.***>:

**Comment by MonstraG** [comment]
> Shall I put it in the node-modules/next-translate folder? Where?

`loadLocaleFrom` is one of the configuration options - https://github.com/aralroca/next-translate#3-configuration.

There is an example under the header `i18n.js` just above:

> ### i18n.js
> ```js
> {
>  // ...rest of config
>  "loadLocaleFrom": (lang, ns) =>
>    // You can use a dynamic import, fetch, whatever. You should
>    // return a Promise with the JSON file.
>    import(`./myTranslationsFiles/${lang}/${ns}.json`).then((m) => m.default),
> }
> ```

**Comment by rolandjlevy** [comment]
I found a fallback solution which works for me, here: https://github.com/aralroca/next-translate/issues/1029#issuecomment-1684827974
