### ISSUE TITLE
There is a way to use translate in SSR Site (not static) without a custom server or a [lang]/ route?

### ISSUE THREAD

**Issue by wilsonneto-dev** [vinissimus/next-translate#190]
Hello guys, there is a way to work with next-translate full SSR site without using the folder [lang]/ or a custom server? 

Thanks so much!

**Comment by aralroca** [comment]
@wilsonneto-dev you can use the default getting started in the [README.md](https://github.com/vinissimus/next-translate#2-getting-started), using the "build step".

Using the build step it works for static, SSG, and SSR sites.

The `lang` property is injected inside `getServerSideProps` and `getInitialProps` methods:

```js
export async function getServerSideProps({ lang }) {
  // ...
}
```

[Dynamic routes](https://github.com/vinissimus/next-translate/tree/master/examples/with-dynamic-routes) ([lang] folder) and [custom server](https://github.com/vinissimus/next-translate/tree/master/examples/with-server#with-server-example) are just alternatives of this "build step".

**Comment by wilsonneto-dev** [comment]
Thanks, I'm doinga  lot of tests and POCs here... This is amazing man, it should be incorporated into the Nextjs core and be native.
Are there plans for that?

Thanks so much!

**Comment by wilsonneto-dev** [comment]
Great! I hope the proposal is made, it would be spectacular.
It helped me a lot, thank you very much!
