### ISSUE TITLE
ISO 639-1 (e.g. sv-SE, da-DK, ru-RU)

### ISSUE THREAD

**Issue by Joelgullander** [vinissimus/next-translate#194]
Is there any support for this format or do I need to define them all in the string array? 
Was looking for a folder-structure of `locales/da/DK `

If no, is this an interesting feature? This would mean that:

Ff `en-CA` is requested we fall back to `en` if there is no locales for that.

This would mean that the `en` is the fallback language while you can still have more specific locales.

**Comment by aralroca** [comment]
I tried, and yep!

![image](https://user-images.githubusercontent.com/13313058/83799337-ee891f80-a6a5-11ea-80bf-195532ca4519.png)

**Comment by Joelgullander** [comment]
Sure but this was more a question regarding nested locales. I understand that you can define the languages in the format that you want, however I would like to know if nested locales is something that is planned to be supported or if there is more people looking for this. 

Like if en-CA is requested and we fall back to en if there is no locales for that. 

This would mean that the en is the fallback language while you can still have more specific locales. 

But thanks for your answer.

**Comment by aralroca** [comment]
Sorry @Joelgullander but nested locales like `locales/da/DK` is not supported...
