### ISSUE TITLE
[Question] - Are remote locale files supported?

### ISSUE THREAD

**Issue by Fghurayri** [vinissimus/next-translate#197]
Hello! 👋

Thank you [again] for the best library to handle i18n with Next JS! 🙏

I'm building a bilingual application where my customer demands managing the i18n translations through a CMS, not by JSON files. Assuming I build such a CMS that outputs the locales in JSON and stores them in a public endpoint, is it possible to load and apply such remote locales using this library?

I think it's doable with the `DynamicNamespaces` feature, but I'm not sure about the best way to configure it. 🤔

If you think there is a better solution/workaround, please share!

I appreciate your help!

**Comment by aralroca** [comment]
Did you try something like this?

```js
<DynamicNamespaces
    dynamic={(lang, namespace) =>
       fetch(`https://remotesite.com/locales/${lang}/${namespace}.json`).then(r => r.json())
    }
    namespaces={['file1', 'file2']}
    fallback="Loading..."
  >
  <Trans i18nKey="file1:example-of-dynamic-translation" />
  <Trans i18nKey="file2:example-of-dynamic-translation" />
</DynamicNamespaces>
```

**Comment by aralroca** [comment]
Another way (if you don't want to loaded dynamically):

```js
export default YourPage({ namespaces }) {
   const { lang } = useTranslation()

   return (
     <I18nProvider lang={lang} namespaces={namespaces}>
        <Trans i18nKey="namespace:example-of-dynamic-translation" />
     </I18nProvider>
   )
}

export async function getStaticProps({ lang }) {
   const namespaces = fetchPageNamespaces(lang)

   return { props: { namespaces } }
}
```

**Comment by aralroca** [comment]
@Fghurayri I'm going to close this. Consider to reopen if you still have troubles

**Comment by Fghurayri** [comment]
Thanks, @aralroca, and sorry for not confirming back on time (the project was sidelined with COVID-19)

I got back to it today. I can confirm the Dynamic approach worked flawlessly and integrates nicely with the API routes for Next JS being the provider for the remote translations! 💯

```js
    <DynamicNamespaces
      dynamic={(lang, ns) => fetch(`/api/translations/${lang}/${ns}`).then(r => r.json())}
      namespaces={['landing', 'inner']}
      fallback=""
    >
        <Trans i18nKey="landing:hero.title" />
        <Trans i18nKey="inner:user.welcome" />
    </DynamicNamespaces>
```

**Comment by aralroca** [comment]
Ok perfect, don't hesitate to open other issues if you have more doubts
