### ISSUE TITLE
Change language while staying on the same route

### ISSUE THREAD

**Issue by ianidi** [vinissimus/next-translate#204]
Hi,

I wouldn't want to redirect user to some predefined route (like "/") when changing language. Instead, I would want it to get the current dynamic path and once user clicks the link just change the language without redirection. Is there a clean way to achieve this? Thanks.

Example (not working right now) what I'm trying to achieve:

```
import withTranslation from "next-translate/withTranslation";
import { withRouter } from "next/router";
import Link from "next-translate/Link";
...
render() {
 const { pathname } = this.props.router;
 const { lang } = this.props.i18n;

return (<Link href={pathname} lang={lang == "en" ? "fr" : "en"}>Change language</Link>)
}
```

**Comment by aralroca** [comment]
When you say "no redirect" do you mean to keep the same state? In this case, you can use [shallow](https://nextjs.org/docs/routing/shallow-routing) to keep the same state on the page (except translations).

```js
onChangeLang() {
  Router.pushI18n(pathname, {
    lang: lang === "en" ? "fr" : "en", 
    shallow: true
   })
}
```

If you mean with "no redirect" to just do a URL replace. You can use `Router.replaceI18n` from `next-translate/Router`, that works in the same way than `Router.push` from `next/router`

**Comment by ianidi** [comment]
@aralroca thank you. It doesn't work until I clean language name from path, because when route includes lang in path, the redirection fails. In my case defaultLangRedirect is set to root.

I had to clean my path
```
  onChangeLang = () => {
    let path = this.props.router.pathname
      .split("/")
      .map((part, index) =>
        index == 1 && (part == "en" || part == "fr") ? null : part
      )
      .filter((el) => el != null)
      .join("/");

    Router.pushI18n({
      url: path,
      options: {
        lang: this.props.i18n.lang === "en" ? "fr" : "en",
        shallow: true,
      },
    });
  };
```

Without cleaning it doesn't work.

**Comment by aralroca** [comment]
Well yes, the suggested code it only works with a [custom server](https://github.com/vinissimus/next-translate/blob/master/docs/USING_CUSTOM_SERVER.md) approach because it allows to use different language per page. For static sites using the pre-build step, it generates a page per language, so it will be hard to achieve this...

**Comment by MasterEric** [comment]
Could this be fixed with a method on `next-translate/Router` that returns the route without the language?
