### ISSUE TITLE
getInitialProps, getServerSideProps & others NEVER work if class component is wrapped with withTranslation

### ISSUE THREAD

**Issue by ianidi** [vinissimus/next-translate#205]
They never work, I've tested several times.

```
import React from "react";
import withTranslation from "next-translate/withTranslation";

class Test extends React.Component {
  static async getInitialProps(ctx) {
   console.log("no output");
    return {
      hello: "hello",
    };
  }

  render() {
    return (<div>{this.props.hello}</div>
    );
  }
}

export default withTranslation(Test);
```

```
import React from "react";
import withTranslation from "next-translate/withTranslation";

class Test extends React.Component {
  render() {
    return (<div>{this.props.hello}</div>
    );
  }
}

 Test.getInitialProps = async (ctx) => {
   console.log("no output");
   return {
      hello: "hello",
   };
 };

export default withTranslation(Test);
```

```
import React from "react";
import withTranslation from "next-translate/withTranslation";

class Test extends React.Component {
  render() {
    return (<div>{this.props.hello}</div>
    );
  }
}

 export async function getServerSideProps(ctx) {
   console.log("no output");
   return {
      props: {
       hello: "hello"
     }
   };
 };

export default withTranslation(Test);
```

**Comment by aralroca** [comment]
@ianidi The first and second examples are because the `getInitialProps` should be added on Page-level.

Working example:

```js
import React from "react";
import withTranslation from "next-translate/withTranslation";

class Test extends React.Component {
  render() {
    return (<div>{this.props.hello}</div>
    );
  }
}

const Page = withTranslation(Test)

Page.getInitialProps = async (ctx) => {
  console.log("output");
  return {
    hello: "hello",
  };
};

export default Page
```

The last example, with `getServerSideProps` for me it works correctly.

![image](https://user-images.githubusercontent.com/13313058/84865767-08990980-b079-11ea-9e77-3b6a4c672b4c.png)

And the same with `getStaticProps`.

Can you provide me more info in order to reproduce it? Next & next-translate version, i18n config... Thanks!

**Comment by ianidi** [comment]
Hello @aralroca, thank you for clarification about the first and second example. However `getInitialProps` doesn't seem good. For me if I use the code from your screenshot I get the "no output", but the props itself are not passed to the page. If I console log this.props, that's what I get:

```
no output
{ i18n: { lang: 'en', t: [Function: t] } }
```
`<div>{this.props.hello}</div>;` is empty

**Comment by aralroca** [comment]
It would be useful if you provide here a reproducible example. BTW; which `next` and `next-translate` versions are you using?

**Comment by aralroca** [comment]
@ianidi did you resolve it? If you provide a reproducible example I'll help you

**Comment by aralroca** [comment]
@ianidi it should work after 0.19.3 release 👍

**Comment by emmekappa** [comment]
I'm having the same issue even with the version 1.0.1. So I submitted this PR #433
