### ISSUE TITLE
[Need Help] useTranslation() lang property is empty on components

### ISSUE THREAD

**Issue by Hypernikao** [vinissimus/next-translate#207]
Hi, 
the lang property from useTranslation() hooks is empty when i log it from any components or custom hooks but the current language is set in every pages.

``` 
// Component Level
import useTranslation from 'next-translate/useTranslation'

export default function Header(){
 console.log(useTranslation().lang) // Empty ''
 return (...)
}

```
Any idea ?

Thanks in advance

**Comment by aralroca** [comment]
@Hypernikao Which way are you using? pre-build with the CLI, using a custom server, dynamic routes? 

If you are using the pre-build, check the parent page how is generated inside `pages`. It should have a `I18nProvider` with the corresponding lang. It would be very useful if you share here the generated outputted of the page to discard an issue.

**Comment by Hypernikao** [comment]
Hi @aralroca ,

Thank you for your response.
I use pre-build with the cli. I call my component in custom layout from _app.js
here is the generated parent:

```
// @ts-nocheck
import I18nProvider from 'next-translate/I18nProvider'
import React from 'react'
import C from '../../_pages'
import ns0 from '../../public/static/locales/fr/common.json'

const namespaces = { 'common': ns0 }

export default function Page(p){
  return (
    <I18nProvider 
      lang="fr" 
      namespaces={namespaces}  
      internals={{"defaultLangRedirect":"lang-path","defaultLanguage":"fr","isStaticMode":true}}
    >
      <C {...p} />
    </I18nProvider>
  )
}

Page = Object.assign(Page, { ...C })

if(C && C.getInitialProps) {
  Page.getInitialProps = ctx => C.getInitialProps({ ...ctx, lang: 'fr'})
}
```

**Comment by aralroca** [comment]
@Hypernikao the generated output looks correct. Do you have some custom `I18nProvider` in your code? In that case, you always need to wrap the lang attribute into it.

**Comment by aralroca** [comment]
The `useTranslation` implementation is just a wrapper of `useContext`:

```js
import { useContext } from 'react'
import I18nContext from './_context'

export default function useTranslation(){
  return useContext(I18nContext)
}
```

So looks that the parent `I18nProvider` doesn't have the `lang`. 😕

**Comment by Hypernikao** [comment]
I have not a custom provider.
My _app.js looks like:
```
import React from 'react';
import App from 'next/app';
import AppLayout from '../components/layouts/appLayout';
import { ThemeProvider } from 'styled-components';
import '../styles/global.css';
import { theme } from '../components/ui/themes/theme';

function MyApp({ Component, pageProps }) {
  return (
    <ThemeProvider theme={theme}>
      <AppLayout>
        <Component {...pageProps}></Component>
      </AppLayout>
    </ThemeProvider>
  );
}

MyApp.getInitialProps = async appContext => {
  const appProps = await App.getInitialProps(appContext);
  return { ...appProps };
};

export default MyApp;
```

And i just call an header component in my AppLayout

**Comment by aralroca** [comment]
@Hypernikao this is related to this issue: https://github.com/vinissimus/next-translate/issues/44

`_app.js` is not wrapped right now with any `i18nProvider`. This is why this is happening... This is documented [here](https://github.com/vinissimus/next-translate#use-translations-in-your-pages).

As a temporal solution, meanwhile this is not fixed, is to move `ThemeProvider`and `AppLayout ` from `_app.js` to every page level...

**Comment by Hypernikao** [comment]
Yes ! it exactly the point !

Thank you for your time.
I wait for this integration ...hope pretty soon.

Regards,

**Comment by aralroca** [comment]
by the way, I noticed that you have an empty `getInitialProps` on `_app.js` level. Removing it, it would provide you a better performance because you are going to activate the Automatic Page Optimization 😊

**Comment by aralroca** [comment]
@Hypernikao thanks to you to report it! Feel free to open more issues or PR 😄

I'm going to close this in favor of #44
