### ISSUE TITLE
Storybook integration

### ISSUE THREAD

**Issue by shunkakinoki** [vinissimus/next-translate#210]
Thanks so much for this amazing project!
Is there a recommended way to integrate with storybook?
That would be very nice!

**Comment by aralroca** [comment]
Did you try to wrap the `<i18nProvider />` on top with a fixed language and all namespaces?

**Comment by aralroca** [comment]
@shunkakinoki did you get it? 😊 I'm going to close the issue. Feel free to re-open if you have some trouble with the with Storybook integration.

**Comment by wlaaraki** [comment]
you can add a decorator in your storybook config

`
import I18nProvider from 'next-translate/I18nProvider';
import common from '~/locales/en/common.json';

addDecorator((storyFn) => (
  <I18nProvider lang="en" namespaces={{ common }}>
    {storyFn()}
  </I18nProvider>
));`
