### ISSUE TITLE
Default Language redirect removes Query Params

### ISSUE THREAD

**Issue by RobinSCU** [vinissimus/next-translate#211]
Hi,

I don't know if it is intentionally but the default language redirect removes the Query Parameters that is especially a bad thing when you try to read them at componentDidMount.

Steps to replicate:
1) Set "en" as DefaultRedirect in i18n.json
2) Request https://test.com/moep?test=12123
3) You get redirected to https://test.com/en/moep

I think the problem comes from the `getDefaultLanguageIndexRedirectTemplate` function in the builder.js which only cares for the path and not for the query params

Thanks for looking at this issue

**Comment by aralroca** [comment]
Thanks for report It

**Comment by aralroca** [comment]
@RobinSCU this will be released on 0.17.2 version. However, is already released on [0.17.2-canary.3](https://github.com/vinissimus/next-translate/releases/tag/0.17.2-canary.3). It should work now 👍 Thank you a lot to report it!

**Comment by RobinSCU** [comment]
@aralroca thanks for the quick fix!
