### ISSUE TITLE
Translate non-pages_ components

### ISSUE THREAD

**Issue by handrei** [vinissimus/next-translate#214]
Hello guys, i installed next-translate and i wanna translate a component from components, not from 'pages_' app.
I'm using the useTranslate hook in the component, and when i console.log it i receive: common:terms, like i use it ( t('common:terms')...
can someone tell me how to translate this kind of components ?
thanks a lot.

**Comment by aralroca** [comment]
You can take a look at the example of this repo:

https://github.com/vinissimus/next-translate/blob/master/examples/static-site/components/header.js

Feel free to clone it and play it.

The idea is that every component in Next.js has a parent page. And in the `i18n.json` you tell which namespaces you want to use on each page.

Hope it helps.

**Comment by handrei** [comment]
thanks !

**Comment by aralroca** [comment]
@handrei I'm going to close this issue! Feel free to re-open if you have some trouble 👍

Also, I recommend to take a look at the example on the Next.js repo:

* https://github.com/vercel/next.js/tree/canary/examples/with-next-translate

**Comment by aralroca** [comment]
If you want to reuse `next-translate`, outside a "Next.js" environment, to translate other components. You will need to wrap the [i18nProvider](https://github.com/vinissimus/next-translate#i18nprovider) on top.

**Comment by handrei** [comment]
i wrapped the Footer Component, which i load in _app.js, with the provider, but sill not working :(

**Comment by aralroca** [comment]
This is related with this open issue: https://github.com/vinissimus/next-translate/issues/44

Right now is hard to fix translations on `_app.js`. (The difficult part is downloading the correct language dictionaries, without adding a `getInitialProps`).

We recommend as a workaround of this, moving the Layout component on a page-level. It's quite annoying, but it's the only solution for now.

**Comment by handrei** [comment]
ok, thanks for advice!
