### ISSUE TITLE
Using next-translate Link in _error.js page with DynamicNamespaces

### ISSUE THREAD

**Issue by skoob13** [vinissimus/next-translate#216]
First of all thank you for the repo!

I'm trying to implement shared Header/Footer components that use next-translate Link in _error.js page. The code is:
```
<DynamicNamespaces
  dynamic={(_, ns) => import(`locales/${lang}/${ns}.json`).then((m) => m.default)}
  namespaces={['common', 'error']}
>
  <Header />
  <Content />
  <Footer />
</DynamicNamespaces>
```
However, since DynamicNamespaces component uses [useTranslation hook](https://github.com/vinissimus/next-translate/blob/master/src/DynamicNamespaces.js#L11), it's not possible to apply a language without wrapping the code with another I18nProvider with current language from asPath or html lang attribute. Furthermore, when I try to open a page with default language, all links become prefixed with default language, what doesn't happen in case of regular page. Finally I figured out to create a redirect from `/[defaultLanguage]/[...path]` to `/[...path]`, but it doesn't seem for me like a good solution.

Is there a way to pass language to Link component without making a hack with default language redirect?

**Comment by aralroca** [comment]
Thanks to report this.

As a temporal workaround meanwhile we don't find a solution, I guess you can add the `internals` object:

* https://github.com/vinissimus/next-translate/blob/fa448f17995790a31c1bc2f246bc5e67b12605f1/src/I18nProvider.js#L63

In the same way that the builder does:

* https://github.com/vinissimus/next-translate/blob/fa448f17995790a31c1bc2f246bc5e67b12605f1/cli/builder.js#L31

Hope it helps as a temporal fix.

**Comment by skoob13** [comment]
> Thanks to report this.
> 
> As a temporal workaround meanwhile we don't find a solution, I guess you can add the `internals` object:
> 
> * https://github.com/vinissimus/next-translate/blob/fa448f17995790a31c1bc2f246bc5e67b12605f1/src/I18nProvider.js#L63
> 
> In the same way that the builder does:
> 
> * https://github.com/vinissimus/next-translate/blob/fa448f17995790a31c1bc2f246bc5e67b12605f1/cli/builder.js#L31
> 
> Hope it helps as a temporal fix.

Thank you! Works perfectly.
