### ISSUE TITLE
Locales subpath

### ISSUE THREAD

**Issue by arnaudjnn** [vinissimus/next-translate#220]
How to define the page path in ```i18n.json``` when you have a subfolder like this:

<img width="212" alt="Screenshot 2020-07-09 at 15 04 39" src="https://user-images.githubusercontent.com/25635480/87043735-d2712480-c1f5-11ea-9a10-f5556200d362.png">

**Comment by aralroca** [comment]
Sorry @arnaudjnn I don't understand the question. Can you clarify it? `locales` folder is designed to contain the namespaces for each language. So the structure should be like:

```
locales
├── ca
│   ├── common.json
│   └── home.json
├── en
│   ├── common.json
│   └── home.json
└── es
    ├── common.json
    └── home.json
```

The subfolder should be always the language.

**Comment by arnaudjnn** [comment]
@aralroca Sorry, I edited the original question. Can't manage with tree markedown 😅

**Comment by aralroca** [comment]
@arnaudjnn Right now is not possible to do this due that this feature is not supported

**Comment by arnaudjnn** [comment]
@aralroca Yes of course but the subfolder of ```en```, I want for example ```pages``` and ```articles```

**Comment by aralroca** [comment]
> @aralroca Yes of course but the subfolder of `en`, I want for example `pages` and `articles`

@arnaudjnn What I meant was that the structure that is now designed only allows for one level. So it's not supported (right now) to use `local/en/pages/home.json` This is a limitation that exists now, but it's good that you've opened up this issue, so we can see if it's worth adding this feature.
