### ISSUE TITLE
SSG or Hook

### ISSUE THREAD

**Issue by arnaudjnn** [vinissimus/next-translate#228]
What's the best?

```JSX
export default ({ article }) => (
  <ArticlePage article={article}/>
)

export const getStaticPaths = async () => {
  return {
    paths: [{ params: { slug: 'example-1' } }, { params: { slug: 'example-2' } }],
    fallback: false
  }
}

export const getStaticProps = async ({ params }) => {
  const article = await import(`locales/${params.slug}.json`)

  return { props: { article } }
}
```
or

```JSX
import { useTranslation } from 'next-translate';

export default ({slug }) => {
      const { t, lang } = useTranslation()
      const article = t(`${slug}:article`, {}, { returnObjects: true })
     return (
      <ArticlePage article={article}/>
     )
}

export const getStaticPaths = async () => {
  return {
    paths: [{ params: { slug: 'example-1' } }, { params: { slug: 'example-2' } }],
    fallback: false
  }
}

export const getStaticProps = async ({ params }) => {
  const slug = params.slug

  return { props: { slug } }
}

```
Why?

**Comment by omarryhan** [comment]
How are you loading the translations in the second example? Is it functional?

Side note: you can color the code by adding "JSX" or "javascript" next to the opening: /`/`/`

**Comment by arnaudjnn** [comment]
@omarryhan 

My translation file has the slug name. The path looks like this ```/locales/slug.json``` so the translation is loaded at build as explained [here in the doc](https://github.com/vinissimus/next-translate#use-translations-in-your-pages)

As files are JSON I don't know if I have to use the hook provided by ```next-translate``` or the original GetStaticProps from Next.js?

**Comment by omarryhan** [comment]
`getStaticProps` was released after this library was first created. So, the `getStaticProps` method is newer than  the method that involves a build step. Both methods require using the `useTranslate` hook though.

 `getStaticProps` requires more boilerplate though. @aralroca mentioned in another issue that the original method (build stage method) might be deprecated in the future. So I'd stick with `getStaticProps`.

**Comment by aralroca** [comment]
I prefer the second option, so in this way you can still have the namespaces declared correctly in your `i18n.json`.

**Comment by aralroca** [comment]
@arnaudjnn I'm going to close this. Feel free to reopen if you still have doubts
