### ISSUE TITLE
Possiblity of maintaining locale by query param instead of path

### ISSUE THREAD

**Issue by harshzalavadiya** [vinissimus/next-translate#230]
This project looks amazing,

However, I was thinking that is there possiblity to have current language figured out by using lang param? for example instead of `/app/en/home` like `/app/home?lang=en` since there's already custom link component and router.

this kind of routing is useful when you are providing offline support with service worker and don't want to cache same page again and again

Anyways, Keep up the good work :+1:

**Comment by aralroca** [comment]
The "build step" is to convert all the structure with locale paths as `/en/home`.  However, you simply can avoid the build step, and do it for query param, the only thing you should do is to wrap every single page with the `i18nProvider` with the lang. 

The only problem is that every page can render different languages, so you need to import all language namespaces or use a dynamic namespace approach (that displays a loading state). But this limitation comes from the implementation, so implementing this in the library will have the same limitation... Instead, implementing by path we have different pages, making it possible to only download the necessary locale namespaces to each one: `/es/page.js`  and `/en/page.js` are different pages.

**Comment by harshzalavadiya** [comment]
hmm, that makes sense, static export SSR will be totally broken in query param scenario

In our app we have query param scenario beacuse of legacy support since we are gradually migrating, I'm hoping that once full migration is complete hopefully I will be able to use this plugin :smile: 

Thanks closing this as of now
