### ISSUE TITLE
GetStaticPaths with different slug for each lang

### ISSUE THREAD

**Issue by arnaudjnn** [vinissimus/next-translate#231]
I have different articles with a different title and slug for each lang. I don't know how can I get only posts from the corresponding lang.

Currently, I have:

```JSX
export const getStaticPaths: GetStaticPaths = async () => {
  const i18nConfig = await import('i18n.json')
  const { allLanguages } = i18nConfig
  const paths = allLanguages.flatMap(lang => {
    const articles = getAllArticles(lang, ['slug'])
    return articles.map(article => ({
      params: {
        slug: article.slug
      }
    }))
  })

  return {
    paths: paths,
    fallback: false
  }
}
```

And it returns this error because it builds slugs also for the other language.

```
Automatically optimizing pages ...Failed: {}
Automatically optimizing pages .
Error occurred prerendering page "/en/blog/16-nouvelles-mesures-de-lutte-contre-travail-illegal-fraude-detachement". Read more: https://err.sh/next.js/prerender-error
Error: ENOENT: no such file or directory, open '/Users/arnaudjeannin/Documents/chapelle-avocat/content/en/articles/16-nouvelles-mesures-de-lutte-contre-travail-illegal-fraude-detachement.md'
```

My issue is quite related [to this](https://stackoverflow.com/questions/61732511/how-to-use-multiple-nested-dynamic-routes-with-getstaticpaths) but with next-translate [lang] is not a dynamic path.

**Comment by aralroca** [comment]
Hi @arnaudjnn thanks a lot to report it. In fact, It's an issue that should be fixed. Tomorrow I'll try to fix it.

**Comment by aralroca** [comment]
@arnaudjnn I think that misunderstood the issue. Did you try it with 

```ts
export const getStaticPaths: GetStaticPaths = async ({ lang }) => {
  console.log(lang) // We are injecting the lang inside the context
}
```

**Comment by aralroca** [comment]
@arnaudjnn did you try this?

> ```ts
> export const getStaticPaths: GetStaticPaths = async ({ lang }) => {
>   console.log(lang) // We are injecting the lang inside the context
> }
> ```

Please confirm if this solves your issue.

**Comment by arnaudjnn** [comment]
Not really,

Like major e-commerce websites for product pages, the slug is the product title so when you change the lang it changes also the URL like so: /fr/mon-produit => /en/my-product
