### ISSUE TITLE
Provide function to log missing keys

### ISSUE THREAD

**Issue by RobinSCU** [vinissimus/next-translate#237]
Hi,

we have a pretty large eCommerce website and unfortunately, we have some error messages/key from external APIs we don't know and they can even change.
Is there a way we can log these missing keys in production so that our translation Team can find them more easily? 

When we could inject an function via i18n.js like this it would be unbelievable great :)  :
```
missingKeyHandler: (key: string): string => { 
    // logging part
    return ''
}
```

Thanks
Robin

**Comment by aralroca** [comment]
@RobinSCU there isn't a way right now, but is an interesting feature to implement

**Comment by dasblitz** [comment]
@aralroca I'm interested in this as well. And thx for a great library :)

**Comment by RobinSCU** [comment]
@aralroca  @giovannigiordano thanks for the implementation, but how can I actually provide the prop to the I18nProvider? As you said in your documentation:

> The I18nProvider is a context provider internally used by next-translate to provide the current lang and the page namespaces. SO MAYBE YOU'LL NEVER NEED THIS.

We actually don't use the I18nProvider directly and in the implementation from @giovannigiordano I can't see a way how we can provide a logger without using the I18nProvider directly in our code or do I miss something?

**Comment by giovannigiordano** [comment]
Sorry, I missed the fact it is automatically added. I will work on it in these days.I will add the logger function to the  JSON config and read from there. 

Inviato da iPhone

**Comment by aralroca** [comment]
I think the best option is to allow `i18n.js` for the configuration, because `i18n.json` is not possible to storage functions. This way the missingKeyLogger function can be added to the config in a simple way. We can support both, `.js` and `.json` to don't add any breaking change.

**Comment by aralroca** [comment]
@RobinSCU I did a prerelease [0.18.0-canary.2](https://github.com/vinissimus/next-translate/releases/tag/0.18.0-canary.2) with this change and improving a little bit the default logger! If you can test it and provide some feedback before the `0.18.0` it would be very useful 🙏. Thanks!

**Comment by RobinSCU** [comment]
@aralroca works like a charm! Thanks for the implementation!
