### ISSUE TITLE
"Using export * from ... in a page is disallowed" error in next.js canary

### ISSUE THREAD

**Issue by myylow** [vinissimus/next-translate#238]
Thanks for all your work on this project, it has been working great for us 😀

Today I tried upgrading to latest next.js canary version (`v9.5.2-canary.8` as of now) in order to use the blocking fallback feature. When using this version together with next-translate, I get this error `Using export * from ... in a page is disallowed`. I believe it is related to https://github.com/vercel/next.js/pull/14325. 

Reverting next.js back to 9.5.1 fixes the problem.

**Comment by aralroca** [comment]
@myylow Thank you very much for reporting it ! I just did a PR to fix it. I'll try to release it today. Meanwhile, it's available at 0.17.2-canary.6
