### ISSUE TITLE
Please fail next-translation before deleting the pages folder

### ISSUE THREAD

**Issue by dreamerNcoder** [vinissimus/next-translate#239]
Hi, 

By mistake I added the translation, and with adding the script "next-translation", it just removed the folder "pages". And this made me lose all the content of "page".
Can we please fail the "next-translate", if the config is missing instead of simply deleting the folder :(

**Comment by aralroca** [comment]
I think that failing when there is no configuration is not a good way. Because if there is no specific configuration, it uses the default configuration values.

Perhaps it would make more sense to fail when it detects that the `pages_` directory does not exist or is empty. With some error message.

**Comment by dreamerNcoder** [comment]
Thanks @aralroca  💯
