### ISSUE TITLE
Default translation when translate doesn't exist.

### ISSUE THREAD

**Issue by radakuceruSM** [vinissimus/next-translate#240]
I didn't find way to translate sentence to default language, when translation doesn't exits.

For example:
_/en/common.json_
`
...
"animalDog": "dog",
"animalCat": "cat"
...
`

_/de/common.json_
`
...
"animalDog": "der hund"
...
`

_component.js_
`
...
`
`
const { t } = useTranslation();
`
`
console.log(t("common:animalDog")); // en: dog, de: der hund
`
`
console.log(t("common:animalCat")); // en: cat, de: common:animalCat - instead of en: cat, de: cat
`
`
...
`

It would be better to translate it into default language instead of printing the path.

**Comment by aralroca** [comment]
@radakuceruSM There is a problem with this... to do the default language fallback means that you have to download all the namespaces twice (for the original language + for the default language)... And that's something we don't want to do.

There are tools to handle translations in JSONs, such as [PoEditor](https://poeditor.com/), which automatically adds a default language to all missing translations. At the moment we prefer the usage of these tools to handle this than to pass the responsibility to the next-translate library.

Hope that you understand! Anyway, thank you so much for your proposal. And, if you get an idea to handle this easily without having to duplicate the namespaces, feel free to reopen the issue.
