### ISSUE TITLE
Breaks in v9.5.2 due to `"Using export * from ... in a page is disallowed"`

### ISSUE THREAD

**Issue by shunkakinoki** [vinissimus/next-translate#241]
Thanks for the awesome repo!!!
I couldn't imagine a next.js life without this awesome project!

Related to #238, since it was published

**Comment by shunkakinoki** [comment]
https://github.com/vercel/next.js/pull/14325

**Comment by aralroca** [comment]
@shunkakinoki Thank you very much for reporting it 🧡! 

I just did a PR to fix it. I'll try to release it today. Meanwhile, it's available at 0.17.2-canary.6

**Comment by shunkakinoki** [comment]
@aralroca Thank you so much!!! 🔥🔥🔥
I can't tell you how much I appreciate your work!
Thank you, once again!

**Comment by aralroca** [comment]
If you can try the pre-release and confirm that everything works in your project 👏 It should work well now 👍
