### ISSUE TITLE
Unhandled Rejection (Error): Cannot find module './/common.json'

### ISSUE THREAD

**Issue by ItsEcholot** [vinissimus/next-translate#244]
Because translations aren't supported in _app.tsx, and thus my Layout / Menu component, I tried wrapping it:
```tsx
  return <>
    <DynamicNamespaces
      dynamic={(lang: string, ns: string) => import(`../../locales/${lang}/${ns}.json`).then(m => m.default)}
      namespaces={['common']}
      fallback="Loading...">
      <Menu
      mode="horizontal"
      theme="dark"
      selectedKeys={[selectedMenuItem]}>
        <Menu.Item key="/">
          <Link href="/"><a><Trans i18nKey="common:header.home" /></a></Link>
        </Menu.Item>
      </Menu>
    </DynamicNamespaces>
  </>;
```

The following error appears:
![image](https://user-images.githubusercontent.com/2771251/90401230-eeda6980-e09d-11ea-991f-3a49e36496a0.png)

Any ideas what's going wrong here?

**Comment by aralroca** [comment]
Looks that the language is missing. This is because `_app.js` is not wrapped with the `i18nProvider` so it doesn't have the context.

You can maybe extract the language from the URL, something like:

```jsx
const router = useRouter()
const langFromUrl = getLangFromRouter(router)

 return (
   <DynamicNamespaces
      dynamic={(lang: string, ns: string) => import(`../../locales/${langFromUrl}/${ns}.json`).then(m => m.default)}
      namespaces={['common']}
      fallback="Loading...">
      <Menu
      mode="horizontal"
      theme="dark"
      selectedKeys={[selectedMenuItem]}>
        <Menu.Item key="/">
          <Link href="/"><a><Trans i18nKey="common:header.home" /></a></Link>
        </Menu.Item>
      </Menu>
    </DynamicNamespaces>
)
```

**Comment by aralroca** [comment]
@ItsEcholot this solve your problem?

**Comment by aralroca** [comment]
@ItsEcholot I'm going to close the issue. Feel free to reopen it if you have more doubts

**Comment by ItsEcholot** [comment]
Yeah sorry that fixed it. I discovered though that this library isn't really fitting my needs. Thanks for the quick help.
