### ISSUE TITLE
Change dynamically language

### ISSUE THREAD

**Issue by gitlabesercitazione** [vinissimus/next-translate#256]
Hi everybody!

What is the best practice for change language dynamically, after an user is logged and i've got the settings language?

**Comment by aralroca** [comment]
The internationalization is via URL: `/es/your-page` or `/en/your-page`... So you need to navigate to the correct one.

**Comment by aralroca** [comment]
@gitlabesercitazione I hope the doubt is resolved. I'm going to close this. If you have more doubts feel free to reopen it or create a new issue
