### ISSUE TITLE
One lang page

### ISSUE THREAD

**Issue by arnaudjnn** [vinissimus/next-translate#257]
What is the best way to redirect the user to another page when the page is not available in the selected language? 

Ex: 
/en/blog/my-article => available
/fr/blog/my-article => not available

If the user changes the lang on  /en/blog/my-article page what's the logic?

Do we need to add this condition to the select component or higher in the app?

**Comment by aralroca** [comment]
If you do not need to `next export` you can use the [redirects](https://nextjs.org/docs/api-reference/next.config.js/redirects) feature of next.js for this. If you need to `next export` you can use some logic as:

```js
const langsNotAvailable = new Set(['fr', 'it'])
const { lang } = useTranslation()

if(langsNotAvailable.has(lang) && typeof window !== 'undefined') {
  Router.replace('/en/blog/my-article')
}
```

I put it outside a `useEffect` to don't wait to mount the component.
