### ISSUE TITLE
Build fails after adding amp config

### ISSUE THREAD

**Issue by kidnapkin** [vinissimus/next-translate#258]
Using this awesome package for a while like it a lot.

The issue comes after trying to add AMP support with `export const config = { amp: true }` at the page level. Got an Invalid Page Config error. However generated file inside `pages` has next line

```js
export { config } from '../../pages_/post/[slug]'
```
This is wrong config according to the docs https://github.com/vercel/next.js/blob/canary/errors/invalid-page-config.md

Thank you!

**Comment by aralroca** [comment]
Ok, perhaps the best way is to copy exactly all the config at build time instead of use the export. Thanks to report it

**Comment by aralroca** [comment]
@kidnapkin thank you for your contribution. I hadn't noticed before.

I'm going to prerelease it under 0.17.3-canary.3 today if you need it 👍 It will be released on 0.17.3 next week

**Comment by aralroca** [comment]
@kidnapkin I already did the prerelease [0.17.3-canary.3](https://github.com/vinissimus/next-translate/releases/tag/0.17.3-canary.3) 👍
