### ISSUE TITLE
Navigating to a link with anchor will cause client side language to be incorrect

### ISSUE THREAD

**Issue by hibearpanda** [vinissimus/next-translate#264]
**Steps to Reproduce**
1. Started at `/es`
2. Navigate to `/es/blog` using `next-translate/link` (`<Link href="/blog" />`)
3. Navigate back to `/es#anchor` using `next-translate/link` (`<Link href="/#anchor" />`)

**Expectation**
Navigating to a page using a link with an anchor will preserve the current language. The language should still be `es` instead of whatever the default language is.

**Actual**
Navigating to a page using a link with an anchor does not preserve the current language. Upon arriving at `/es#anchor` the `lang` value is incorrect (no longer `es` but now the default language), and the translations will be using the wrong file.

**Setup and Versions**
Using custom server setup.

```
"next-translate": "^0.17.3-canary.3",
"next": "^9.5.3",
```

I tried passing in Url objects to href with `url.hash` property but this library currently assumes href is always a string. But that is a separate issue.

**Comment by hibearpanda** [comment]
I did some investigation and the cause is due to `getLang` and `startsWithLang`. Specifically, `startsWithLang` does not recognize if a url starts with a language if there is # in url path, and `getLang` also wouldn't take it into consideration.

**Comment by liuboaibc** [comment]
This problem reappeared in version 0.20.2
