### ISSUE TITLE
[Discussion] With Next v9.5.5

### ISSUE THREAD

**Issue by shunkakinoki** [vinissimus/next-translate#272]
Hi once again!

Next v9.5.5 has been released today, with initial changes for i18n
https://github.com/vercel/next.js/releases/tag/v9.5.5

As far as I have tested, the lang path seems to be automatically generated/handled by next.js,
perhaps eradicating entirely the need for a build step?
How will the library evolve to v1.0.0 given the official i18n rfc?

I'm happy to devote as much as possible to contribute to this awesome library!

**Comment by aralroca** [comment]
@shunkakinoki I think it is better to move the discussion into this existing issue: https://github.com/vinissimus/next-translate/issues/129

Initially, when I created this library I did the build-step as a workaround while there was no better solution. Now that it seems that Next.js is focusing on improving support for i18n, I think the most sensible thing is to adapt to its way, eliminating the build-step and other possible workarounds. 

I still have doubts about how to support totally static pages (yarn export) without the build-step. Although the Next.js team comments that it is a very small percentage of the people who use Next.js, I myself for example have some projects on CDNs using Next.js + next-translate + yarn export... 🤔

That said. I close the issue and we move the discussion to the already open issue to talk about the evolution of this library.
