### ISSUE TITLE
Different languages base on the domain 

### ISSUE THREAD

**Issue by TheFullResolution** [vinissimus/next-translate#276]
In one issue @aralroca mentioned, "In our case, for example, we have the same webpage in different domains and only one language per domain." 

_Originally posted by @aralroca in https://github.com/vinissimus/next-translate/issues/51#issuecomment-585945735_

Do you have any example or suggestion on how to use this plugin to achieve that? In my case, we are looking into having different languages base on the domain. Belgium is a great example where only french and dutch needs to be supported.

**Comment by TheFullResolution** [comment]
I see that on your page https://www.vinissimus.fr/fr/ if I replace `/fr/` with '/en/`, I am being redirected to https://www.vinissimus.com/en/  would be awesome if you shared which of many alternatives you used to achieve that. 😄

**Comment by aralroca** [comment]
@TheFullResolution we are currently using the "custom server" version, documented here:

* https://github.com/vinissimus/next-translate/blob/master/docs/USING_CUSTOM_SERVER.md

For the redirects, we are using an extra Node middleware that checks the location and the lang and redirects (or no) to the correct one.

Although we currently have this implementation, the Next.js team now advises against using a custom server, as you can now use their own API for [redirects](https://nextjs.org/docs/api-reference/next.config.js/redirects) and [middleware](https://nextjs.org/docs/api-routes/api-middlewares). I guess we will gradually migrate to this option.

Hope it helps.

**Comment by TheFullResolution** [comment]
Awesome, thanks for the insight! I was simply wondering if there is something I am missing. Hopefully, the Next.js team will release their support for i18n routes soon :)

**Comment by aralroca** [comment]
Yes, I hope so too!
