### ISSUE TITLE
The Trans tag in React, if you re-use a tag it gives a key error.

### ISSUE THREAD

**Issue by zeg-io** [vinissimus/next-translate#277]
In the case of the following translation I get the standard react key missing error.

`"somekey": "this text contains <0>bold text</0> and this other text <0>is also bold</0>."`

```js
<Trans
        i18nKey={'ns:somekey'}
        components={[<b />]}
      />
```

However, if I do not attempt to reuse the component it works fine:
`"somekey": "this text contains <0>bold text</0> and this other text <1>is also bold</1>."`
(note the <1> tag)

```js
<Trans
        i18nKey={'ns:somekey'}
        components={[<b />, <b />]}
      />
```

**Comment by aralroca** [comment]
@zeg-io thanks to report the issue 😊  I fixed and prereleased on [0.18.0-canary.1](https://github.com/vinissimus/next-translate/releases/tag/0.18.0-canary.1). Now it should work 👍  It will be finally released on 0.18.0 during the next weeks.
