### ISSUE TITLE
Adapt i18n Routing to Next.js core

### ISSUE THREAD

**Issue by aralroca** [vinissimus/next-translate#284]
Now i18n Routing is part of the nextjs core: https://nextjs.org/docs/advanced-features/i18n-routing

We need to deprecate some things like Link, Router, and adapt the builder and everything to the new way.

**Comment by arnaudjnn** [comment]
Awesome! Do you have a timeline?

**Comment by aralroca** [comment]
@arnaudjnn The PR about this is already done (but not merged yet). I invite you to try `0.19.0-experimental.5` to give us feedback about it, this way we can fix possible issues before the release. There is no timeline, this will be merged asap we can ensure some users migrated to 0.19.0-experimental.5 without any problem. For now, I updated the examples according to the new experimental version and it works well.

For now, there is a bug with `getInitialProps` when loading the namespaces, report it here: https://github.com/vercel/next.js/issues/18396

On the build step, we put a `console.warn` when using getInitialProps reporting this and indicating that it is recommended to change it to `getServerSideProps`. I don't know if this is enough or better to wait for feedback from the next.js team. Right now this is the only thing that is blocking the release.
