### ISSUE TITLE
Static Site Export doesn't work properly with Next 9

### ISSUE THREAD

**Issue by rjvim** [vinissimus/next-translate#29]
Out folder generated with Next 9

![Screenshot 2020-01-03 at 4 37 23 PM](https://user-images.githubusercontent.com/23579455/71720337-544b5400-2e47-11ea-805a-9a3b7ffe460d.png)

Out folder generated with Next 8

![Screenshot 2020-01-03 at 4 40 12 PM](https://user-images.githubusercontent.com/23579455/71720440-c3c14380-2e47-11ea-964a-4455483a5c64.png)

It works well with Next 8.

It's not clear if something should be changed in app config or nextjs config.

**Comment by rjvim** [comment]
```
module.exports = {
    exportTrailingSlash: true
};
```

Above fixes it.

**Comment by aralroca** [comment]
@rjvim in the repo example is without the `exportTrailingSlash: true`:

https://github.com/vinissimus/next-translate/tree/master/examples/static-site

Although you already fix it... I'm curious... how is your i18n config?

Is similar to this?

```json
{
  "allLanguages": ["en", "ca", "es"],
  "defaultLanguage": "en",
  "pages": {
    "*": ["common"],
    "/": ["home"],
    "/more-examples": ["more-examples"]
  }
}
```

Maybe we can improve the docs to clarify it.
