### ISSUE TITLE
t(common:title) works - but `t(common:section-1.title)` doesn't works - t function unable to retrieve the text from multiple JSON nesting levels

### ISSUE THREAD

**Issue by himanshu-dhiman26** [vinissimus/next-translate#30]
I tried using the translation which works perfectly when my JSON looks like : 

```
{
    "title": "Some Title"
}
```
and called using : `t(common:title)`

But if my JSON looks like :

```
{
    "section-1": {
        "title": "Some Title"
    }
}
```

and if I call it as : `t(common:section-1.title)`

This doesn't work. It prints "common:section-1.title" instead of the text value.

**Comment by aralroca** [comment]
Totally agree. It's a feature that is not implemented right now. But it will be very useful. 

Thanks for reporting this. We are going to try to implement this for the next release.

**Comment by aralroca** [comment]
@himanshu-dhiman26 in the next release `0.3.0` this is fixed.

 Thanks for reporting it! Feel open to re-open it if the problem persists.

**Comment by aralroca** [comment]
Use `0.3.1` instead of `0.3.0`. I fixed some defaults in https://github.com/vinissimus/next-translate/pull/35.
