### ISSUE TITLE
Bind namepace to t function

### ISSUE THREAD

**Issue by GrefriT** [vinissimus/next-translate#305]
I would like to see the ability to pass a namespace to the useTranslation hook that would bind to the t function. Similarly as it is done in [react-i18next](https://react.i18next.com/latest/usetranslation-hook#loading-namespaces)

**Comment by aralroca** [comment]
@GrefriT thanks for the proposal 😊  It would be to load it dynamically, isn't it? Similar to the [DynamicNamespaces](https://github.com/vinissimus/next-translate#dynamicnamespaces) component but as a hook, that's what you say? because I find it difficult to load the namespace from SSR using a hook.

**Comment by GrefriT** [comment]
No, everything is much simpler than you think. Namespaces required still remain, I wanted to say something like this
`I18nProvider.js`
```
function t(key = '', query, options) {
    const k = Array.isArray(key) ? key[0] : key
    const [namespace, i18nKey] = k.split(/:(.+)/)
    const dic = allNamespaces[namespace || options.bind] || {}
   ...
  }
```
`useTranslation.js`
```
export default function useTranslation(bind){
  const { lang, t } = useContext(I18nContext)
  return { lang, t: (key, query, options) => t(key, query, {...options, bind})
}
```
I think the point is clear

**Comment by GrefriT** [comment]
And I also think that if the key is not found, then you should not return namespace along with the key. For example
```
function MyComponent(){
   const { t } = useTranslation();
   t("common:non-existent-key") // non-existent-key NOT common:not-existent-ley
}

**Comment by aralroca** [comment]
Ahh ok! Okay, I'm fine with this proposal, it's true that it's redundant without this. Ok, so let's implement it then! Thank you!

**Comment by aralroca** [comment]
@GrefriT I prereleased under (0.20.0-canary.2)[https://github.com/vinissimus/next-translate/releases/tag/0.20.0-canary.2], if you want to start using the feature you can do so without waiting for 0.20. It should work fine, anything you find please communicate here and I'll fix it. Thank you very much!
