### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by plaskaw** [vinissimus/next-translate#306]
I have, a problem with yarn build command with this package. Yarn dev works correctly.
My files looks like bellow (based on step 2 of implementation):

i18n.json
```
{
  "locales": ["en", "cs", "hr", "hu", "pl", "ro", "sk"],
  "defaultLocale": "en",
  "currentPagesDir": "_pages",
  "finalPagesDir": "pages",
  "localesPath": "locales",
  "pages": {
    "*": ["common", "languages"],
    "/404": ["error"],
    "/_error": ["error"],
    "/": ["home"],
    ...
  }
}
```

next.config
```
i18n: {
    locales,
    defaultLocale,
  },
```

package.json
```
"scripts": {
    "dev": "next-translate && next dev",
    "build": "next-translate && next build",
    "start": "next start -p 3005",
    "start-stage": "next start -p 3006",
    "start-master": "next start -p 3007"
  },
```
app.tsx
```
//@ts-ignore
import React from 'react';
import { AnimatePresence } from 'framer-motion';


function MyApp({ Component, pageProps }: any) {
  return (
    <AnimatePresence exitBeforeEnter>
      <Component {...pageProps} />
    </AnimatePresence>
  )
}

//@ts-ignore
export default MyApp;

```

Yarn dev works perfectly. But from some reason yarn build returns:
```
Type error: Type 'unknown' is not assignable to type 'string'.

  23 |     <PageLayout>
  24 |       <MetaSEO
> 25 |         title={t('about-us:meta_title', {})}
```
No matter what component i will used in every place, typescript stop my build on any t function with above error.
Can someone help me please :)

**Comment by aralroca** [comment]
Are you using v.`0.19.3`?

**Comment by plaskaw** [comment]
> Are you using v.`0.19.3`? Types are now available. Did you try to add this?
> 
> ```tsx
> import useTranslation from 'next-translate/useTranslation'
> import type { I18n } from 'next-translate/useTranslation'
> 
> // ...
> 
> const { t } : I18n = useTranslation()
> ```
> 
> CC:@croutonn

Yeah that's helped, with some update on my project connected with dipper components typescript references.
But now i have something different :)

```
> Build error occurred
Error: Export encountered errors on following paths:
        /cs/ _app
        /en/ _app
        /hr/ _app
        /hu/ _app
        /pl/ _app
        /ro/ _app
        /sk/ _app
    at exportApp (/Users/pawel.laskawiec/Development/dcs-tmobile/node_modules/next/dist/export/index.js:25:1103)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

So i don't know the typescript is good configured?
My ts.
```

{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noImplicitAny": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve"
  },
  "exclude": ["node_modules"],
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"]
}
```

**Comment by croutonn** [comment]
I just submitted a [PR to improve this problem](https://github.com/vinissimus/next-translate/pull/307).

If you do not cast the return value of the `t()` function with `as Type`, you will get a build error because you are not sure whether the type is a character, an object, or an array.

**Comment by aralroca** [comment]
@plaskaw I prerelesed the @croutonn code under [0.19.4-canary.2](https://github.com/vinissimus/next-translate/releases/tag/0.19.4-canary.2). Hope it helps

**Comment by plaskaw** [comment]
@aralroca unfortunately there is still something not working on build process.
I did quick repo based on my project setting. Maybe you will find something ;)

https://github.com/plaskaw/next-trans-test

**Comment by croutonn** [comment]
@plaskaw you must install v0.19.4-canary.2  as follows:
```sh
yarn add next-translate@0.19.4-canary.2
```

**Comment by plaskaw** [comment]
> @plaskaw you must install v0.19.4-canary.2 as follows:
> 
> ```shell
> yarn add next-translate@0.19.4-canary.2
> ```

That not change anything ;) Please see repo.

**Comment by croutonn** [comment]
@plaskaw The filename for `_ app.tsx` has a leading space 😛

**Comment by plaskaw** [comment]
@croutonn My gosh seriously. I hate typos ;) Thank a lot we can close this issue.

**Comment by aralroca** [comment]
nice, then I will release the 0.19.4 😜
