### ISSUE TITLE
[Typescript] Returntype of t

### ISSUE THREAD

**Issue by BjoernRave** [vinissimus/next-translate#308]
First of all I appreciate a lot to have native typescript support now.

However when using the `useTranslation` hook, the return type of `t` is `unknown`, but it should be string

**Comment by aralroca** [comment]
@BjoernRave I prereleased [0.19.5-canary.1](https://github.com/vinissimus/next-translate/releases/tag/0.19.5-canary.1) if you want to start using it! And if you can confirm that everything is fine it would be perfect 😊  

Thanks!!
