### ISSUE TITLE
Is there a workaround to use i18n with Export in NextJS 10?

### ISSUE THREAD

**Issue by jawil003** [vinissimus/next-translate#314]
I upgraded to Next Js 10 and now when I export it seems like it is not supported, so may I need to disable the i18n of Next JS to use it the old way?

**Comment by aralroca** [comment]
From 0.19 of next-translate the routing part used is the integration of Next 10, so it is **only possible with a next-translate version older than 0.19 + i18n of Next 10 deactivated**. 

I hope that in the future they will support i18n routing with `next export`. This new version of Next.js brings us many good things, but with it, also comes some things to give up temporarily, like this.

**Comment by jawil003** [comment]
Alright, I downgraded and now I'm fine, bad move from NextJS :(

**Comment by aralroca** [comment]
@jawil003 maybe you can take the old builder and bring it to your codebase, this way you can still use the latest version of the next-translate API. This is the file of the old builder: https://github.com/vinissimus/next-translate/blob/0.18.0/cli/builder.js

**Comment by Xairoo** [comment]
> I hope that in the future they will support i18n routing with `next export`. This new version of Next.js brings us many good things, but with it, also comes some things to give up temporarily, like this.

https://github.com/vercel/next.js/issues/18318#issuecomment-735695487

**Comment by zipme** [comment]
@jawil003 here is the workaround I use and you'd still be able to use the latest version of `next-translate`:
```js
// next.config.js
const nextTranslate = require('next-translate')

module.exports = {
  ...nextTranslate(),
  i18n: undefined,
}

```

**Comment by jcmpes** [comment]
However, this workaround will break the ability to actually change locale with nextTranslate, doesn't it?
