### ISSUE TITLE
Clean npm package 

### ISSUE THREAD

**Issue by popuguytheparrot** [vinissimus/next-translate#315]
Hi guys. Looked at how the package was built in dependencies and it's terrible.
This is not need in package.
* .vscode dir for what?
* docs is same, 
* duplicated _helpers in src
* src folder but no source map
* only transpileted code by babel
* CONTRIBUTING
* .all-contributorsrc

![image](https://user-images.githubusercontent.com/19804652/98683272-e41a3280-2375-11eb-913d-c793fb023ad7.png)

**Comment by aralroca** [comment]
Hey, good point! I just saw it a couple of days ago and taking advantage of the fact that for version 1.0 I am passing the project to TypeScript I will try to leave everything clean :)

**Comment by aralroca** [comment]
In [1.0.0-experimental.6](https://github.com/vinissimus/next-translate/releases/tag/1.0.0-experimental.6) prerelease everything is much cleaner 😊

* https://www.runpkg.com/?next-translate@1.0.0-experimental.6

**Comment by popuguytheparrot** [comment]
Cool. Great work!

**Comment by aralroca** [comment]
Closing this. Already fixed on [1.0.0-canary.1](https://github.com/vinissimus/next-translate/releases/tag/1.0.0-canary.1). The 1.0 will be released in approximately 1-2 weeks. 😊
