### ISSUE TITLE
Feature Request: support .js files for locales

### ISSUE THREAD

**Issue by jansepke** [vinissimus/next-translate#321]
Thank you for this great library. Do you think it would be possible to add support for .js or .ts files instead of .json files for storing locales. With this it would be possible to dynamically fetch the locales.

**Comment by aralroca** [comment]
@jansepke I encourage you to try the [1.0.0-experimental.4](https://github.com/vinissimus/next-translate/releases/tag/1.0.0-experimental.4) prerelease, you can achieve this with:

**i18n.js**

```js
module.exports = {
  locales: ["en", "ca", "es"],
  defaultLocale: "en",
  pages: {
    "*": ["common"],
    "/404": ["error"],
    "/": ["home"],
    "/dashboard": ["home"],
    "rgx:^/more-examples": ["more-examples"]
  },
  // this way you can load "ns.js" / "ns.json" / "ns/index.js". Or directly fetch to an API / cdn
  loadLocaleFrom: (lang, ns) => import(`./locales/${lang}/${ns}`).then(m => m.default)
}
```

There are some breaking changes, explained here https://github.com/vinissimus/next-translate/issues/303

**Comment by aralroca** [comment]
Anyway, from 0.19.5 you should be able to use .js or .json in your local files, have you tried it? I close issue because in principle from 0.19.5 you can do it only by renaming your .json files to .js.

**Comment by jansepke** [comment]
thank you, it is working as expected :+1:
