### ISSUE TITLE
Feature Request: Change Language persistence

### ISSUE THREAD

**Issue by afzaalahmad** [vinissimus/next-translate#323]
I've seen that right now, switch language feature is simply rerouting the user to selected language but persistence is missing from the package. If user has switched to french using switcher, for the time being during his interaction, he will be redirected to french routes but language preference is not getting persisted. If he comes back, he will be redirected to the default language instead of his preferred language.

It would be great to have some kind of configuration in i18n.js that whether we want user preference to be saved or not.

**Comment by aralroca** [comment]
A Locale can be forced by setting the NEXT_LOCALE cookie to a locale that is supported by the application. E.g. NEXT_LOCALE=nl

**Comment by aralroca** [comment]
@afzaalahmad Did the cookie work for you? I'm going to close this issue because currently with Next 10 you can do this.

**Comment by aralroca** [comment]
I added how to do this in the documentation in case someone else has doubts. 😊 👍
