### ISSUE TITLE
Context for keys

### ISSUE THREAD

**Issue by Cedric-Delacombaz** [vinissimus/next-translate#324]
Hi

First of all, thanks for this great package. I was struggling with other packages for the past few days and with next-translate, I got up and running really quickly :)

However, I couldn't do one thing. Is it somehow possible to pass a context to `t()` to access different keys based on the context?

I tried to play around with the examples in the docs related to passing variables or plural count, but I couldn't make it work.

Underneath you will find my example - but you can also see this in i18next docs: https://www.i18next.com/translation-function/context#context

**Example**

**declaration in /locales/en/common.json**
```
{
    "description": "a pretty long description",
    "description_mobile": "short desc"
}
```

**usage in index.jsx**
`{t('common:description')}`
=> passing no context returns the value of description
=> passing a context with empty string returns the value of description

`{t('common:description', {context: 'mobile'})}`

=> passing context of mobile will return the value of description_mobile

I would appreciate any help and if this is currently not possible, maybe this issue can become a feature request :)

Thanks!

**Comment by aralroca** [comment]
We can add it, I don't think it's very expensive, but I find it hard to see what this feature brings us. Can't it be done like that?

```js
const context = '_mobile'
const description = t(`common:description${context}`)
```

**Comment by Cedric-Delacombaz** [comment]
Thanks for the quick reply and for the suggested solution. This works fine and is definitely enough. Didn't think about that. Thanks!
