### ISSUE TITLE
Is it possible to transform yaml to json in `loadLocaleFrom`

### ISSUE THREAD

**Issue by josephfarina** [vinissimus/next-translate#327]
Does `loadLocaleFrom` need to return a dynamic import statement? I am wondering if it is possible to return a promise that reads a yaml file via `fs` and then transforms it into `json`.

If this isn't possible, is there any recommended way to use yaml translation files instead of json ones?

**Comment by aralroca** [comment]
You need to return a promise, using dynamic import the `.then((m) => m.default)` is necessary. So these examples are valid:

_Ex 1: Using dynamic import (.js, .json, .ts, .tsx, .jsx...)_

```js
{
  loadLocaleFrom: (lang, ns) =>
      import(`./locales/${lang}/${ns}`).then((m) => m.default),
}
```

_Ex 2: Fetching from somewhere_

```js
{
  loadLocaleFrom: (lang, ns) =>
      fetch(`https://cdn.mylocales.com/${lang}/${ns}`).then((res) => res.json()),
}
```

I guess that the easiest way to use yaml is to search for a suitable webpack loader like this one https://github.com/eemeli/yaml-loader. This way, you can still use dynamic import of _Ex 1_.

**Comment by josephfarina** [comment]
Ah okay great that makes sense. Thanks!

**Comment by aralroca** [comment]
@josephfarina I hope this resolves your doubt. I close the issue, if you have other doubts do not hesitate to open more issues. Thank you!

**Comment by gfortaine** [comment]
> You need to return a promise, using dynamic import the `.then((m) => m.default)` is necessary. So these examples are valid:
> 
> _Ex 1: Using dynamic import (.js, .json, .ts, .tsx, .jsx...)_
> 
> ```js
> {
>   loadLocaleFrom: (lang, ns) =>
>       import(`./locales/${lang}/${ns}`).then((m) => m.default),
> }
> ```
> 
> _Ex 2: Fetching from somewhere (using [unfetch](https://github.com/developit/unfetch))_
> 
> ```js
> {
>   loadLocaleFrom: (lang, ns) =>
>       fetch(`https://cdn.mylocales.com/${lang}/${ns}`).then((res) => res.json()),
> }
> ```
> 
> I guess that the easiest way to use yaml is to search for a suitable webpack loader like this one https://github.com/eemeli/yaml-loader. This way, you can still use dynamic import of _Ex 1_.

cc @aralroca It seems that the code for fetch should be : 


```js
{
  loadLocaleFrom: async (locale, namespace) => {
    try {
      const { apiGatewayMshURL } = await import('./pages/api/conf');
      const res = await fetch(`${apiGatewayMshURL}/v1/i18n/${locale}/${namespace}`);

      return res.json();
    } catch {
      const res = await import(`./locales/${locale}/${namespace}`);

      return res.default;
    }
  }
}
```

Otherwise there is a bug when we generate a build with next.js for static pages (by example 404) because the fetch throws an error. By the way, it looks like that we also need a local copy of all the translations files (empty json are ok for the ones not used by static pages) in `./locales/${locale}/${namespace}`
