### ISSUE TITLE
Question:  Can I use Translation outside react component ?

### ISSUE THREAD

**Issue by JbPons** [vinissimus/next-translate#329]
Hello,

I come from a big CRA project and I start to migrate it to Next.js. For translation i previously use [https://www.npmjs.com/package/@lingui/react](@lingui/react).

I find this library very interesting with the tree-shaking and all the feature i want except one I need to achieve the migration to next.js

Basically with the current project, I had specific case where I used the translate on Epic (Epic come from [https://redux-observable.js.org/](url) if you didn't know) in a redux store. 

So, Can I use the translation on a redux store (in an Epic in my case), outside a React component ?

**Comment by aralroca** [comment]
The `t` function uses the React context to know the available language and namespaces to use during the translation. Then, you can use the `t` function outside components as long as you pass the function:

```jsx
import useTranslation from 'next-translate/useTranslation'

function MyComponent() {
  const { t } = useTranslation()
  
  return getItems({ t }).map(item => <div key={item}>{item}</div>)
}

// using translations outside components
function getItems({ t }) {
   return Array.from({ length: 100 }).map((_, index) => t(`mynamespace:key_number_${index}`))
}

```

**Comment by JbPons** [comment]
Ok, I see your point. I think i need to rework some part to integrate it like this.

Thanks, have a good day

**Comment by aralroca** [comment]
You are welcome. Any other doubt or incident do not hesitate to report it! Thank you very much.

**Comment by aralroca** [comment]
@JbPons I have made a PR adding getT, with this you can use translations out of React, in places like `getStaticProps`, API routes, etc. https://github.com/vinissimus/next-translate/pull/383

**Comment by aralroca** [comment]
@JbPons I pre-released the change under **[1.0.0-canary.8](https://github.com/vinissimus/next-translate/releases/tag/1.0.0-canary.8)**. I would appreciate it if you could try it out on your project and give me feedback that everything is working well for you 😊 

If you wonder how to migrate to version 1.0, here is a guide:

- https://github.com/vinissimus/next-translate/blob/1.0.0-canary.8/docs/migration-guide-1.0.0.md

Any doubt, tell me. Thank you very much for reporting it 🙏 I guess that version 1.0 will be released soon.

**Comment by JbPons** [comment]
Oh thanks for this. I hesitated to test the 1.0.0 because I need to translate some content from the  _app.js file. And I see the #44 issue mentionning that the 1.0.0 solve this issue. Currently, I work hard on the migration to next.js. Since my project is pretty big ( around 400 react component), it's take time. But, I will test the 1.0.0 by the end of the week. Thanks for your hard work

**Comment by SakamotoKurome** [comment]
> The `t` function uses the React context to know the available language and namespaces to use during the translation. Then, you can use the `t` function outside components as long as you pass the `t` function:
> 
> ```js
> import useTranslation from 'next-translate/useTranslation'
> 
> function MyComponent() {
>   const { t } = useTranslation()
>   
>   return getItems({ t }).map(item => <div key={item}>{item}</div>)
> }
> 
> // using translations outside components
> function getItems({ t }) {
>    return Array.from({ length: 100 }).map((_, index) => t(`mynamespace:key_number_${index}`))
> }
> ```
> 
> Anyway, if you want to save translations inside a store, I would like to suggest that the translations are better not to be part of the state of the application

Thank you so much. It works, the key is to pass the context out, but the details may be different in different projects. I use lingui.js and it also works really well.
