### ISSUE TITLE
What's the core javascript package for translation? i18next or react-i18next ?

### ISSUE THREAD

**Issue by HsnVahedi** [vinissimus/next-translate#331]
Thanks for this nice way of internationalization.

I'm just wondering which javascript package is used for the actual translation: "i18next" or "react-i18next" ?

**Comment by aralroca** [comment]
Hi @HsnVahedi the next-translate package has no external dependencies, so the translations are implemented in the next-translate package itself. One of next-translate's goals is to be a small library, so having an external dependency like i18next was not an option. Hope it helps!

**Comment by HsnVahedi** [comment]
Oh! That's awesome. Actually I was wondering if the "<Trans />" component is the same as in "react-i18next". They offer [multiple ways of using "<Trans />" component](https://react.i18next.com/latest/trans-component).


But There's only one in "next-translate".

**Comment by aralroca** [comment]
@HsnVahedi in 0.20 version you probably will have another way: https://github.com/vinissimus/next-translate/issues/225 😊
