### ISSUE TITLE
process.env doesn't get processed when using "build step" method

### ISSUE THREAD

**Issue by andrehsu** [vinissimus/next-translate#342]
Environmental variables referenced with process.env in the "pages_" directory do not work.

Here is a demo of the problem: https://github.com/andrehsu/with-next-translate-app.

./.env
```
HELLO="Hello!"
```
./_pages/index.js, on line 24
```
<p>process.env.HELLO</p>
```

**Comment by aralroca** [comment]
@andrehsu This will be solved on 1.0.0, you can try the prerelease [1.0.0-experimental.13](https://github.com/vinissimus/next-translate/releases/tag/1.0.0-experimental.13). In 1.0 release the `pages_` workaround will no longer exist _(so you will be able to work with the pages directory normally)_, and the loading of translations is done by a Webpack loader. Here is the issue: https://github.com/vinissimus/next-translate/issues/303

**Comment by andrehsu** [comment]
Intended behavior of next.js, not related to next-translate.
