### ISSUE TITLE
Migrating to v1.0.0

### ISSUE THREAD

**Issue by dislick** [vinissimus/next-translate#348]
I've just updated to `1.0.0-experimental.15` and was looking for a migration guide. I couldn't find one so I wanted to open this issue to discuss whether you might want help with that. Here's a quick draft of steps I had to take in my project:

1. Run `npm install next-translate@1.0.0-experimental.15`
2. Update `next.config.js`:
```diff
-const { locales, defaultLocale } = require("./i18n.json");
+const nextTranslate = require("next-translate");

module.exports = {
-  i18n: { locales, defaultLocale },
+  ...nextTranslate(),
};
```
3. Remove unnecessary configuration from `i18n.json`:
```diff
{
  "locales": ["de", "fr", "it"],
  "defaultLocale": "de",
-  "currentPagesDir": "pages_",
-  "finalPagesDir": "pages",
-  "localesPath": "locales",
  "pages": {
    "*": ["common"],
    "rgx:^/products": ["products"]
  }
}
```
4. Remove build step in `package.json`:
```diff
"scripts": {
-  "dev": "next-translate && next dev",
-  "build": "next-translate && next build",
+  "dev": "next dev",
+  "build": "next build",
  "start": "next start"
}
```
5. Remove `.gitignore` entry
```diff
# local env files
.env.local
.env.development.local
.env.test.local
.env.production.local

-# i18n
-/pages
```

6. Move pages from `pages_` to `pages`:
```bash
rm -rf pages
mv pages_ pages
```

**Comment by aralroca** [comment]
@dislick thank you very much to share this. Yes, the migration guide has yet to be written (as it is still experimental). Everything went well for you, no problems?

Another breaking change introduced by `1.0.0-experimental.16` is to change the plurals `_plural` by `_other`. Since now we have expanded the plural forms support, adapted to http://cldr.unicode.org/index/cldr-spec/plural-rules

Besides, the `dynamic` property of `DynamicNamespaces` component is now optional.

What I have done is to update the README of the experimental branch: https://github.com/vinissimus/next-translate/blob/1.0.0-experimental/README.md maybe this helps.

Another thing that is still pending is to update the repo examples. I wanted to do it just today. 

If everything goes well, in a few days I will pass the version from experimental to canary, since it has that it looks that finally we will stay with this change.

**Comment by dislick** [comment]
Updating went great, no problems whatsoever! Yes I saw the new README on the experimental branch, thanks to that I was able to come up with the necessary steps to upgrade.

If you're interested I can open a PR with a migration guide, just tell me if you want it in the README or a separate file. I think you would then need to complete it with the plurals changes, but it might be a good starting point.

It's really a joy to use `next-translate`, please keep up the good work!

**Comment by fillon** [comment]
Updating to 1.0.0-experimental.16 went great too.

**Comment by aralroca** [comment]
@dislick this will be awesome! 🙏.  I had in mind to extend the documentation in the future, documents like `FAQ.md`,  and integrations like `with-mdx.md`, etc. So maybe it makes sense to put everything under the `/docs` directory. Perhaps `/docs/migration-guide-1.0.0.md` (or something like this) ?

**Comment by aralroca** [comment]
Can someone who has windows confirm that it works well in the development environment?

**Comment by popuguytheparrot** [comment]
is it possible to type locales with this feature?
https://devblogs.microsoft.com/typescript/announcing-typescript-4-1-beta/#template-literal-types

**Comment by aralroca** [comment]
I did a short demo video about 1.0:

- Demo video: https://www.youtube.com/watch?v=QnCIjjYLCfc 
- Code: https://github.com/vinissimus/next-translate/tree/1.0.0-experimental

I hope you find this useful 😊

_(sorry my English)_

**Comment by heshamz** [comment]
@aralroca I followed your nice video, but I am facing a strange issue, I even tried the basic example from next-translate, but with the same result, the page is always showing as below image.
![image](https://user-images.githubusercontent.com/8942729/100675487-1d8ffd80-3378-11eb-97ac-544e8bbbc4d9.png)
I am attaching the sample project as well
[dynamic-routing.zip](https://github.com/vinissimus/next-translate/files/5619199/dynamic-routing.zip)

**Comment by aralroca** [comment]
Closing this. Already added on [1.0.0-canary.1](https://github.com/vinissimus/next-translate/releases/tag/1.0.0-canary.1). The 1.0 will be released in approximately 1-2 weeks. 😊. Feel free to open PR in order to fix issues, typos or improve documentation / migration guide
