### ISSUE TITLE
webpack loader doesn't check for pages in src/pages (1.0.0-experimental.16)

### ISSUE THREAD

**Issue by pgrippi** [vinissimus/next-translate#351]
The webpack loader skips files that aren't in the `/pages` directory but doesn't check for files in `/src/pages`, resulting in translations not being injected into their `getXXXProps` methods

https://github.com/vinissimus/next-translate/blob/64293224996540399b8cb5a767cad9c0dfa8452b/src/plugin/loader.js#L9-L17

**Comment by aralroca** [comment]
Thank you @pgrippi ! fixed on 1.0.0-experimental.17 👍
