### ISSUE TITLE
Type issue with the WithTranslation HOC on Typescript

### ISSUE THREAD

**Issue by JbPons** [vinissimus/next-translate#353]
I experiment some typing issue with the current typescript implementation on the latest version 0.20.2.

I have lot of Class Component and I use the HOC WithTranslation. If i use the HOC on children component call on a parent component i have a typing issue with the i18n object. With the current implementation, The i18n object is add to the component type and when i call my component the compiler want the i18n object to be passed to the props like this `<MyComponent i18n={...} />`. 

But it's not the desired behavior, normally we just need to add manually the props injected by the HOC directly on Props type in the declaration of the component. An example of this good practice: [https://react-typescript-cheatsheet.netlify.app/docs/hoc/full_example](url)

So this is the current implementation found on my node_modules ( from `withTranslation.d.ts`: 
```typescript
declare function withTranslation<P = unknown>(
  component: React.ComponentType<P>
): React.ComponentType<P & { i18n: I18n }>
export default withTranslation
```

And I replace it by this code ( I adapt it from an another library I use on my project) : 
```typescript
import { WithTranslationProps } from './'

declare function withTranslation<P extends WithTranslationProps>(
  component: React.ComponentType<P>
): React.ComponentClass<Omit<P, keyof WithTranslationProps>> & { WrappedComponent: React.ComponentType<P> };

export default withTranslation
```
And I add an helper to pass props on my class Component in the `index.d.ts` file :
```typescript
export type WithTranslationProps = {
  i18n: I18n;
}
```

After that i can use it like this in my project : 
```typescript
import { withTranslation, WithTranslationProps } from 'next-translate';

interface MyProps {
// pass here all your props 
}
type Props = MyProps & WithTranslationProps;

class MyComponent<Props> {
// some stuff
}

export default WithTranslation(MyComponent);

// Now, I can call the component like this without any type issue
<MyComponent />
```

I don't have the time to create a PR, and i don't know if my fix is the best approach for this issue, but anyway I try something. 
Have a good day

**Comment by aralroca** [comment]
@JbPons I prereleased the [0.21.0-canary.2](https://github.com/vinissimus/next-translate/releases/tag/0.21.0-canary.2) with this fix👍
