### ISSUE TITLE
SSR support with appWithI18n

### ISSUE THREAD

**Issue by msojda** [vinissimus/next-translate#356]
Hey,

Thanks for the great work! The library itself is very promising and solves a lot of issues.

However my app uses SSR and renders everything on the server upfront. How can I use next-translate to render translated strings on the server side? Currently, when I look into the page source in the browser, it renders translation keys.

Thanks,
Matt

**Comment by aralroca** [comment]
@msojda if is rendering the translations keys means that it's not finding the translations. It may be for one of these reasons:

- You don't have the files under `locales/{locale}/{namespace}.json`, or as you specified in the configuration. You can see an example of how they are defined here: https://github.com/vinissimus/next-translate/tree/0.20.2/examples/with-appWithI18n/locales
- When you use the hook useTranslation you are not indicating the namespace + the key. You can see an example here: https://github.com/vinissimus/next-translate/blob/0.20.2/examples/with-appWithI18n/pages/index.js#L9 where it would be consuming the `locales/{locale}/home.json` namespace by looking up the key "description".
- You are not specifying in the configuration which namespaces should download each page. An example: https://github.com/vinissimus/next-translate/blob/0.20.2/examples/with-appWithI18n/i18n.js#L8

I hope you find it useful. If you see that the error persists it would help if you can make a reproducible example of the error and then we look in detail at what is wrong with it. Thanks. 😊

**Comment by msojda** [comment]
Thanks @aralroca. It seems to be the issue of not finding translations. I've verified my setup and providing namespace as an argument to `useTranslation` helped. It wasn't very clear at the beginning but everything's working as expected now. 😄

**Comment by aralroca** [comment]
Perfect @msojda ! If you think there is something to clarify in the documentation feel free to do PR!
