### ISSUE TITLE
Why is it necessary to use pages_ instead of normal pages?

### ISSUE THREAD

**Issue by aladinflux** [vinissimus/next-translate#36]
Couldn't we just use the folder pages as the default language, then copy it into localized subfolders? We won't have to use a special "pages_" folder in that case. Also, we won't have duplicate content (pages/index.js === pages/en/index.js) for the default language.

**Comment by aralroca** [comment]
Before the internal next.js build is necessary to prepare all the pages with the translations (only in the case that the website is static). You can use another name... `_pages` is just the default name... You can change it in the configuration to `views` or whatever... Then, if you add the `pages` folder on the `.gitignore` you can forget that this build-step exists...

**Comment by aralroca** [comment]
BTW; using a custom server you can work on normal pages without any transformation
