### ISSUE TITLE
Invalid compiled page name in windows on version 1.0.0-canary.1

### ISSUE THREAD

**Issue by vimutti77** [vinissimus/next-translate#361]
In next-translate v1.0.0-canary.1, If I have a page in `pages/foo/bar`. The compiled page pathname that need to use in `i18n.json` will be `/foar`.

## Expected behavior
**Page location:** `pages/foo/bar`
**Compiled page pathname:** `/foo/bar`

**Compiled log**
```
next-translate - compiled page: /foo/bar - locale: en - namespaces: common, error - used 
loader: getStaticProps
```

## Actual behavior
**Page location:** `pages/foo/bar`
**Compiled page pathname:** `/foar`

**Compiled log**
```
next-translate - compiled page: /foar - locale: en - namespaces: common, error - used 
loader: getStaticProps
```

**Comment by aralroca** [comment]
Already prereleased on [1.0.0-canary.2](https://github.com/vinissimus/next-translate/releases/tag/1.0.0-canary.2) 😜. Thanks @vimutti77
