### ISSUE TITLE
next-translate doesn't load if using styled components

### ISSUE THREAD

**Issue by dsauna** [vinissimus/next-translate#366]
When adding a configuration, I get an error in _document that says

`Class constructor App cannot be invoked without 'new'`

**Comment by aralroca** [comment]
It's weird because next-translate does nothing with the file _document.js. Is it the same with the canary version 1.0? Can you create a reproducible example?

**Comment by aralroca** [comment]
If in [1.0.0-canary.2](https://github.com/vinissimus/next-translate/releases/tag/1.0.0-canary.2) is already fixed I wouldn't worry too much because we will release it soon. Could you check it out? 

### Useful links:

- [How to migrate 0.x to 1.0](https://github.com/vinissimus/next-translate/blob/1.0.0-canary.2/docs/migration-guide-1.0.0.md)
- [Getting started with 1.0](https://github.com/vinissimus/next-translate/blob/1.0.0-canary.2/README.md#2-getting-started)
- [Plurals in 1.0](https://github.com/vinissimus/next-translate/blob/1.0.0-canary.2/README.md#5-plurals)
- [Examples with 1.0](https://github.com/vinissimus/next-translate/tree/1.0.0-canary.2/examples)

In 1.0 the `_document.js `file is not touched.

**Comment by dsauna** [comment]
Thanks, let me take a look

**Comment by dsauna** [comment]
I'm actually using canary 2.0 :(

**Comment by aralroca** [comment]
And removing next-translate it works? It's strange because we don't touch the `_document.js`. I think it would be best if you can create a reproducible example and then we look at it in detail. Thank you very much. 🙏

**Comment by dsauna** [comment]
Yes, removing it fixes it. Let me try adding a reprodusable example.

**Comment by aralroca** [comment]
@dsauna this would be very useful! Thank you!

**Comment by dsauna** [comment]
@aralroca I found the really weird issues. I don't think it has anything to do with styled components. 

The issue is that if you use next-translate and your _app.tsx/_app.js is a class component it will fail. Easy fix to not use a class component, you can see the issue here. Not sure if a bug, but it took me a while to realize. 

https://github.com/dsauna/next-translate-styled

**Comment by aralroca** [comment]
Thanks @dsauna, I'll look into it then! Well seen

**Comment by dsauna** [comment]
Thank you for putting the hard work into this. Let me know if you need any help

**Comment by aralroca** [comment]
@dsauna it would help if you provide your `_app.js` file. I just try it with:

```jsx
import React from 'react'
import type { AppProps } from 'next/app'

import '../styles.css'

class MyApp extends React.Component<AppProps> {
  render() {
    const { Component, pageProps } = this.props
    return <Component {...pageProps} />
  }
}

export default MyApp
```

On the repo example and seems that works well. So I see the differences between your `_app.js`  from mine...! Thank you very much! 🙏

**Comment by aralroca** [comment]
Ah sorry, I didn't see the repo https://github.com/dsauna/next-translate-styled, this works for me, thank you very much!

**Comment by aralroca** [comment]
@dsauna I have finally found the root of the problem. It seems that NextApp causes Next.js to serve its modified default `_app.js`.  Then, next-translate  misunderstood that it did not have a custom `_app.js` and it was overwriting the default `_app.js` causing the issue.

**Comment by aralroca** [comment]
I did a prerelease [1.0.0-canary.3](https://github.com/vinissimus/next-translate/releases/tag/1.0.0-canary.3), now it should work 👍

**Comment by dsauna** [comment]
ah! that's amazing, thanks so much
