### ISSUE TITLE
Testing with Jest a standalone function using getT => TypeError: Cannot read property 'loadLocaleFrom' of undefined

### ISSUE THREAD

**Issue by fillon** [vinissimus/next-translate#387]
Hi,

next-translate@1.0.0-canary.9

I am not sure if it's related to next-translate.

All my tests using `getT` in /api endpoint are passing.

The tests using `getT` in 'standalone function` are failing.

```js
it ('test getT', async () => {

  const t = await getT ('fr', 'common'); //// stops here

  const result = t ('Birthday');
  expect (result).toBe ('Anniversaire');
});
```

`TypeError: Cannot read property 'loadLocaleFrom' of undefined`

**Comment by aralroca** [comment]
seems not to be detecting the i18n configuration. This configuration is saved globally: `global.i18nConfig` in node or `window.i18nConfig` in the browser. And is the same content of the `i18n.js` file.

**Comment by fillon** [comment]
Thanks @aralroca 

I added these lines in `jest.setup.js`.

```
const i18n = require ('./i18n');
global.i18nConfig = i18n;
```

Now testing passing.

Thanks again :)
