### ISSUE TITLE
Language switch on urls with anchor tag doesn't work

### ISSUE THREAD

**Issue by Cedric-Delacombaz** [vinissimus/next-translate#398]
Hi

First of all, thanks for this amazing library and the new version 1.0.0. Makes everything way cleaner!!

I am using next-translate in a project where I have 2 languages, DE and EN. I noticed a bug during language switch when using anchor tags in the url. Somehow, if an anchor tag is present in the url, the language switch doesn't work.

**Example how to reproduce the bug:**

- Open https://codesandbox.io/s/next-translate-bug-report-1vbhe
- Click on "ABOUT WITH ANCHOR"
- Click on "DE" or "EN" to change language 

=> nothing happens

**Example with buggy solution:**

I tried to just get rid of the anchor tag in the href during language change. However, the first click still doesn't have any effect. The second click does translate though.

- Open the header component https://codesandbox.io/s/next-translate-bug-report-1vbhe?file=/components/Header.js
- Replace href={asPath) with href={path}
- Click on "ABOUT WITH ANCHOR"
- Click on "DE" or "EN" to change language (first click nothing will happen, second click it translates)

Do you have any idea how this can be solved?

Thanks!

**Comment by fillon** [comment]
@Cedric-Delacombaz 

It's working after adding the property `passHref` with your example.

```js
<Link href="/about#subtitle" passHref>
          <a>ABOUT WITH ANCHOR</a>
</Link>
```

**Comment by Cedric-Delacombaz** [comment]
@fillon thank you. I tried it out and unfortunately, I couldn't notice any different behavior.

I forked and created an example with passHref:  https://codesandbox.io/s/next-translate-bug-report-withpasshref-bufrv?file=/pages/index.js

If you manage to get a working example, could you please save and share the codesandbox?

**Comment by fillon** [comment]
@Cedric-Delacombaz that's weird

your latest codesandbox is working perfectly for me using macos and chrome 87

**Comment by aralroca** [comment]
@Cedric-Delacombaz Looking at the console there is an error from Next.js:

![image](https://user-images.githubusercontent.com/13313058/102060894-0c70d300-3df3-11eb-9fde-08a515b66342.png)

Looks like a Next.js error.  In fact, all [i18n routing](https://nextjs.org/docs/advanced-features/i18n-routing) is in the Next.js core not in next-translate.

I think it would be good to open the issue in the repo of next.js so they can fix it. It seems that when there is **an error on some link** then it doesn't have the props of the page that should have been loaded with `getStaticProps` / `getServerSideProps`.

![image](https://user-images.githubusercontent.com/13313058/102063985-07ae1e00-3df7-11eb-8df4-8db995e22072.png)

As a temporal workaround, after replacing `asPath` to  `asPath.split('#')[0]` on your `Header` component (to remove the anchor), it solves the problem.

**Comment by aralroca** [comment]
I reported the issue on the Next.js repo: https://github.com/vercel/next.js/issues/20160

**Comment by aralroca** [comment]
I close it becauseuse it is an issue of Next.js and not of this repo.

**Comment by cdelacombaz** [comment]
@aralroca thanks for having a look at it and reporting it to Next :)
