### ISSUE TITLE
How to handle big translation source files

### ISSUE THREAD

**Issue by jansepke** [vinissimus/next-translate#400]
Maybe this is a rather special case, but I have a problem when using bis translation source files in my translation files.

My setup is as follows:

i18njs:
```js
module.exports = {
  locales: ["en", "de"],
  defaultLocale: "de",
  loadLocaleFrom: (lang, ns) =>
    import(`./data/locales/${lang}/${ns}.js`).then((m) => m.default),
  pages: {
    "*": ["common"],
  },
};
```

data/locales/en/common.js:
```js 
const bigTranslationSource = require("../../bigTranslationSource.json");

const filteredTranslations = bigTranslationSource.filter(...);

module.exports = filteredTranslations;
```

As bigTranslationSource.json is very big >4MB and NextJS+Webpack+Hotreload will somehow cache every required file I get out of memory exceptions after a few changes during development. My current idea is to use `fs.readFileSync` to workaround the Webpack caching. But then I get `Module not found: Can't resolve 'fs'` error.

So one question I have is: How can I process a big translation source file in my translation file without the webpack caching issue. I know that preprocessing the file would be an option, but I would like to avoid an additional build step.

I would understand if you say that this is not really a problem of next-translate but rather a performance problem of NextJS hot reload mechanism (related: https://github.com/vercel/next.js/issues/15855) but maybe you have an idea how I could work around this with the features of next-translate.

next: 10.0.3
next-translate: 1.0.0

**Comment by aralroca** [comment]
@jansepke I'm not sure about this... but maybe you could try moving the big JSONs into `/public`, and fetch them with [isomorphic-unfetch](https://www.npmjs.com/package/isomorphic-unfetch)... Then, your  `i18n.js` could be like this:

```js
const fetch = require('isomorphic-unfetch')

module.exports = {
  locales: ["en", "de"],
  defaultLocale: "de",
  loadLocaleFrom: (lang, ns) =>
    fetch(`./data/public/bigJSONFile.json`).then((m) => m.json()).then(filterTranslations(lang, ns)),
  pages: {
    "*": ["common"],
  },
};
```

**Comment by aralroca** [comment]
@jansepke did you finally solve it?

**Comment by jansepke** [comment]
yes that helped, thank you :+1:
