### ISSUE TITLE
Doesn't work without _app.tsx (in a monorepo setup)

### ISSUE THREAD

**Issue by dimaip** [vinissimus/next-translate#401]
If my app doesn't have `_app.js`, this line never gets triggered: https://github.com/vinissimus/next-translate/blob/master/src/plugin/loader.ts#L28
Thus there's no I18nProvider being wrapped and the package doesn't work.
I can see that it works with the demos provided with the package, so I'm not sure what the issue really is.

My dependencies:
```
"dependencies": {
    "next": "^10.0.3",
    "next-compose-plugins": "^2.2.1",
    "next-translate": "^1.0.0",
    "next-transpile-modules": "^6.0.0",
    "react": "^17.0.1",
    "react-dom": "^17.0.1"
  },
```

I have a monorepo setup, here's my core package.json:
```
{
  "private": true,
  "workspaces": [
    "packages/*"
  ]
}
```

Here's my next.config.js:

```js
const withPlugins = require("next-compose-plugins");
const withTM = require("next-transpile-modules")(["@myapp/components"]);
const nextTranslate = require("next-translate");
module.exports = withPlugins([nextTranslate, withTM]);
```

I realise you'd want me to setup a demo to reproduce it, but I can do it right now unfortunately, already wasted 3 hours on this issue...

**Comment by aralroca** [comment]
thank you for reporting it

**Comment by aralroca** [comment]
@dimaip dimaipCan you try if the prerelease [1.0.1-canary.2](https://github.com/vinissimus/next-translate/releases/tag/1.0.1-canary.2) solves your problem? Thanks 🙏

**Comment by dimaip** [comment]
@aralroca I can confirm that it indeed does fix the problem for me! Thank you for being so responsive to this issue, let's hope it'd save some debugging nightmares for someone in the future :)

**Comment by aralroca** [comment]
@dimaip I close the issue, if you see something else do not hesitate to report it. Thank you!
