### ISSUE TITLE
Translation is not loaded

### ISSUE THREAD

**Issue by rafaelcruzazevedo** [vinissimus/next-translate#403]
I follow the setup guide and the provided examples but when i use the `useTranslation` the translation is not loaded, and the weird thing is the `lang` is empty.
Here my setup
```js
// ./i18n.js

module.exports = {
  defaultLocale: 'en',
  loadLocaleFrom: (locale, namespace) => {
    return import(`./public/static/locales/${locale}/${namespace}.json`).then((m) => m.default);
  },
  locales: ['en', 'pt'],
  pages: {
    '*': ['common'],
    '/': ['home']
  }
};
````

```js
// ./next.config.js

const nextTranslate = require('next-translate');

module.exports = {
  ...nextTranslate(),
  images: { ... },
  webpack: ...
};
```

```tsx
// ./public/static/locales/

├── en
│   ├── common.json
│   └── home.json
├── pt
    ├── common.json
    └── home.json
```

```tsx
// ./pages/index.tsx

import useTranslation from 'next-translate/useTranslation';

const Home = (props: Props) => {
  const { t } = useTranslation();

  return (
    <p>{t('home:title')}</p>
  );
}

export async function getServerSideProps() {
  return {
    props: {}
  };
}

export default Home;
```
and this renders the key instead of the value

```html
<p>home:title</p>
```

anything is wrong with this setup?

**Comment by aralroca** [comment]
@rafaelcruzazevedo maybe your webpack is crushing the next-translate plugin webpack... Have you tried this?

Instead of:

```js
module.exports = {
  ...nextTranslate(),
  images: { ... },
  webpack: ...
};
```

Do:

```js
module.exports = nextTranslate({
  images: { ... },
  webpack: ...
});
```

**Comment by rafaelcruzazevedo** [comment]
@aralroca ty, now it works good

**Comment by rafaelcruzazevedo** [comment]
Out of the topic, @aralroca you know if is possible to do this:
to translate the urls
```tsx
pages
├── [downloads]
│   ├── index.tsx
│   └── [slug].tsx
├── [faqs]
│   ├── index.tsx
│   └── [slug].tsx
| index.tsx
```

**Comment by aralroca** [comment]
Yes, but you should provide the getStaticPaths, and take care switching to another language using the correct url.

**Comment by rafaelcruzazevedo** [comment]
wouldn't it be interesting to save the locale in a cookie too?
To be used outside the components or pages!
Or already exists? I have a case, where i need to inject the locale in requests but i need to pass alaways from pages to request.

**Comment by aralroca** [comment]
@rafaelcruzazevedo By default, no cookies are stored. But if you want to save the locale in a cookie, we recommend that you use the name `NEXT_LOCALE` for that cookie, this way Next.js already takes care of saving the user's preferred language, and the next time the user enters the site it will be shown in their language.

docs: https://github.com/vinissimus/next-translate/blob/1.0.0/README.md#10-how-to-save-the-user-defined-language
