### ISSUE TITLE
i18n.lang is empty when component tested with jest

### ISSUE THREAD

**Issue by RobinSCU** [vinissimus/next-translate#404]
Hi, 

we have a lot of class components that use the withTranslation function component so that we can access the current language and the translation method.

```
class Test extends React.Component<any,any> {
   render(): JSX.Element {
       const {i18n} = this.props;
       return <>i18n.lang</>
   }
}

export default withTranslation(Test)
```
The problem is that when we test a component with Jest the lang in the component is empty.

I tried to add the I18nProvider in the test

```
it('render delivery time productInfoStatus_begin with deliveryId=5', function testDeliveryTime() {
    const wrapper = mount(
        <I18nProvider lang="en">
            <Test />
        </I18nProvider>);

    expect(wrapper..text()).toEqual('en');
});
```

But then I get this error:
``Error: Uncaught [TypeError: router_1.useRouter is not a function]``  

I also tried to add ``global.i18nConfig = i18n;`` to my jest.setup.js

Is there a trick to get the language?

We use the latest next-translate and next.js version

Thanks
Robin

**Comment by aralroca** [comment]
@RobinSCU maybe it helps you to see [our tests of the Trans component](https://github.com/vinissimus/next-translate/blob/master/__tests__/Trans.test.js#L8), we use the I18nProvider. You can pass the config as a prop, apart from the namespace + lang to use.

**Comment by aralroca** [comment]
@RobinSCU can you finally solve it? 😊

**Comment by fuzunspm** [comment]
how did you fix empty lang key issue?
