### ISSUE TITLE
i18n.json should be read from target root when using `next dev ./my_folder` command

### ISSUE THREAD

**Issue by elbopha** [vinissimus/next-translate#405]
Hello,

This is a suggestion.

When I run `next dev ./my_folder`, `./my_folder/next.config.js` is read if `./next.config.js` is missing.

It would be good if `./my_folder/i18n.json` is also read if `./i18n.json` is missing?

Regards,

**Comment by aralroca** [comment]
@elbopha Now this can be defined as follows:

```js
const withNx = require('@nrwl/next/plugins/with-nx');
const nextTranslate = require('next-translate')

module.exports = withNx(nextTranslate({ dir: __dirname })); 
```

Or simple using `process.env.NEXT_APP_PATH` env variable.

Changes: https://github.com/vinissimus/next-translate/pull/407/files#diff-21682b68ed82193995e01bd3585b2a596634ce8bb436f9cc0c3c9a39af8e2f40R7

Prerelease: [1.0.1-canary.2](https://github.com/vinissimus/next-translate/releases/tag/1.0.1-canary.2)

Can you confirm if it works for you? 🙏

**Comment by elbopha** [comment]
@aralroca, it works with `1.0.1-canary.2` and adding `dir: __dirname`.

**Comment by aralroca** [comment]
Nice, maybe it can be renamed or changed before 1.0.1.

**Comment by aralroca** [comment]
@elbopha probably in canary.3 we remove this double configuration in order to use `NEXT_TRANSLATE_PATH` env variable.

Changes: https://github.com/vinissimus/next-translate/pull/409
