### ISSUE TITLE
Interpolation with component

### ISSUE THREAD

**Issue by elbopha** [vinissimus/next-translate#408]
Hello,

Maybe I was wrong but I might see a class named `Interpolate` before.

How do you use interpolation with component?
I cannot find any example.

I am expecting something similar to this.
`<Interpolate key='my_key' var1='World' var2={<MyComponent />} />`

Where (as example)
```
{
  "my_key": "Hello {{var1}} {{var2}}!"
}
```

Regards,

**Comment by aralroca** [comment]
The Interpolation class never exists. I think you have confused it with the Trans component, which allows you to put components and html in the translations.

```jsx
// The defined dictionary enter is like:
// "example": "<0>The number is <1>{{count}}</1></0>",
<Trans
  i18nKey="common:example"
  components={[<Component />, <b className="red" />]}
  values={{ count: 42 }}
/>
```

Docs: https://github.com/vinissimus/next-translate#trans-component

**Comment by elbopha** [comment]
@aralroca, it works with `<Trans />`

Maybe I will only suggest for standalone component, we could use something like `The number is <MyComponent />` instead of `The number is <MyComponent></MyComponent>`.
It's minor thing actually.
