### ISSUE TITLE
Add documentation on how to use nextConfig with the plugin

### ISSUE THREAD

**Issue by tperamaki** [vinissimus/next-translate#418]
There is a possibility to add a nextConfig when calling `nextTranslate()`, but it's not documented. It would be nice to know how to add custom webpack configuration when using this plugin.

https://github.com/vinissimus/next-translate/blob/master/src/plugin/index.ts#L3

I believe something like this works:
```
module.exports = nextTranslate({
  webpack: (config, { isServer, webpack }) => {
    ...
  }
});
```

**Comment by aralroca** [comment]
@tperamaki feel free to PR!
