### ISSUE TITLE
Document YAML alternative to JSON locale files, avoid escaping JSON

### ISSUE THREAD

**Issue by ecoreng** [vinissimus/next-translate#428]
I usually don't prefer yaml over the alternatives, but in this case I think it's superior due to the fact that you don't have to escape special characters and strings can be managed in their original form. Example:

locale file in JSON
```
{
  "translation-to-spanish": "traducción a español"
}
```
is not valid JSON due to the lack of escaping of the `ñ` and `ó`

The valid alternative is:
```
{
  "translation-to-spanish": "traducci\u00F3n a espa\u00F1ol"
}
```

However:

```yaml
translation-to-spanish: traducción a español
```
is valid YAML

you only need to add `yaml-loader` to `webpack` config and manually tell `next-translate` to load `yaml`s instead of json

install:
```
npm i yaml-loader
```

next.config.js
```
module.exports = nextTranslate({
 ...
  webpack: config => {
    config.module.rules.push({
      test: /\.ya?ml$/,
      type: 'json',
      use: 'yaml-loader',
    });
    return config;
  },
});
```

i18n.js
```
module.exports = {
  ...
  loadLocaleFrom: (lang, ns) => import(`./locales/${lang}/${ns}.yaml`).then(m => m.default),
  ...
}

```

**Comment by aralroca** [comment]
@ecoreng It is not clear to me if it works and you want to provide it as documentation, or it does not work for you and you are reporting some issue. Could you clarify this?

In case it is an issue, it would be great to provide what is wrong so that we can see and correct it.

In case you want to provide documentation on how to use YAML, it would be great if you create a PR by adding a markdown explaining it in:

* https://github.com/vinissimus/next-translate/tree/1.0.1/docs

Thank you very much for your contribution 🙏  😊

**Comment by aralroca** [comment]
@ecoreng By the way, where did you get that it is not a valid JSON with characters like `ñ` or `í`? We are using `í` in the example, and it works well because is valid UTF-8: https://github.com/vinissimus/next-translate/blob/1.0.1/examples/basic/locales/es/common.json#L2

**Comment by ecoreng** [comment]
You are right, it is in the JSON official spec that it MUST support UTF8:
https://tools.ietf.org/html/rfc8259

However, for some reason my webpack failed to load it.
It may be worth adding the YAML alternative as a slightly less verbose option then I guess.

Yeah, next-translate works as expected and provides everything you need to load YAML if necessary thanks for that :+1:  . I'm just pointing out that YAML could be another option :). I guess it's submitting a PR to document it, I'll try to submit it myself soon.
Thanks
