### ISSUE TITLE
add documentation on how to change language

### ISSUE THREAD

**Issue by BjoernRave** [vinissimus/next-translate#43]
It would be good if you could explain somewhere what is the best way to switch between languages, maybe even expose a `changeLang` function in the `useTranslation` hook

**Comment by aralroca** [comment]
Ok! For the simple way as possible, you don't need any API of this lib to change the language. You can do it directly with `<Link>` component or `Router.push` of next.js.

``` jsx
import React from 'react'
import useTranslation from 'next-translate/useTranslation'

import i18nConfig from '../i18n.json'

function ChangeLanguage() {
  const { t, lang } = useTranslation()

  return i18nConfig.allLanguages.map(lng => {
    if(lng === lang) return null

    const languageName = t(`layout:lang-${lng}`)
     // Or you can attach the current pathame at the end
    const href = `/${lang}`

    return (
      <Link href={href} key={lng}>
        {languageName}
      </Link>
    )
  })
}
```

We can provide some examples in the docs. But there isn't a `changeLang` function.

**Comment by BjoernRave** [comment]
@aralroca thanks, alot, cant wait on this, to finally replace my old lib with this :)

**Comment by BjoernRave** [comment]
I came up with this function to change the language, I might do a PR to the lib to add this function to `useTranslation` once I figure out how to access `router`

```
  const changeLanguage = (lng: string) => {
    if (router.pathname === "/") {
      router.push(`/${lng}`);
    } else {
      let routes = router.pathname.split("/");
      if (allLanguages.includes(routes[1])) {
        routes[1] = lng;
      } else {
        routes.splice(1, 0, lng);
      }
      router.push(routes.join("/"));
    }
  };
```

It would also be good to have a `Link` component which extends the `Link` Component from next.js, but persists the language on route changes

This is my custom Link Component:

```
import { FC } from "react";
import NextLink, { LinkProps } from "next/link";
import { useRouter } from "next/router";
import { allLanguages, defaultLanguage } from "../i18n.json";

const Link: FC<LinkProps> = ({ children, href, ...props }) => {
  const router = useRouter();

  const getCurrentLanguage = () => {
    if (router.pathname === "/") {
      return defaultLanguage;
    } else {
      let routes = router.pathname.split("/");
      if (allLanguages.includes(routes[1])) {
        return routes[1];
      } else {
        return defaultLanguage;
      }
    }
  };

  return (
    <NextLink href={`/${getCurrentLanguage()}${href}`} {...props}>
      {children}
    </NextLink>
  );
};

export default Link;
```

**Comment by aralroca** [comment]
Ok @BjoernRave, if you do a PR of `Link` and `changeLanguage` we can add them to our API. However, I am in favor of do it separately of `useTranslation` hook, in order to take advantage of tree-shaking. Because in most cases you need to change the language in a modal, and then in all other pages you don't need that extra code. And we want to keep a tiny size of this lib.

Ex of possible imports:

```js
import Link from 'next-translate/Link'
import changeLanguage from 'next-translate/changeLanguage'
```
