### ISSUE TITLE
Support for YAML translation files

### ISSUE THREAD

**Issue by xcrzx** [vinissimus/next-translate#436]
Using JSON format for localization strings is not always convenient. It has problems with multiline strings, quotes, comments, etc. So it is common practice to use more human-friendly formats for documents that are frequently edited by hand.

I'm trying to set up `next-translate` to work with YAML files instead. Here are my current configs:

**i18n.js**
```js
module.exports = {
  // ...rest of config
  loadLocaleFrom: (lang, ns) =>
    import(`./locales/${lang}/${ns}.yaml`).then((m) => m.default),
}
```

**next.config.js**
```js
const withNextTranslate = require('next-translate')

module.exports = withNextTranslate({
    webpack: (config) => {
      config.module.rules.push({
        test: /\.ya?ml$/,
        type: 'json',
        use: 'yaml-loader',
      })

      return config
    },
)
```

Localization strings are loaded with the app as expected. However, when I edit any locales, changes don't get picked up by hot reloading. Page refresh doesn't help either. And only dev server restart helps.

Any ideas what could cause that behavior?

**Comment by aralroca** [comment]
@xcrzx I think is not related to YAML, is related to this another issue: https://github.com/vinissimus/next-translate/issues/411 I close it because it seems to be duplicated. In principle it will be 1.1.0. Thanks for reporting it anyway.
