### ISSUE TITLE
IE 11 support not working with next-translate

### ISSUE THREAD

**Issue by 1R053** [vinissimus/next-translate#449]
**What version of Next.js are you using?**

latest

**What version of Node.js are you using?**

14.15.3

**What browser are you using?**

IE 11

**What operating system are you using?**

Windows

**How are you deploying your application?**

next start, next dev

**Describe the Bug**

In my application IE 11 support is not working. JS code breaks with errors, since the code is not transpiled properly.
This can be reproduced with the example app from the NextJs repo:  
https://github.com/vercel/next.js/tree/canary/examples/with-next-translate

just run the app and open it with IE 11

interestingly, other apps using other libraries works fine in IE 11, e.g.
https://github.com/vercel/next.js/tree/canary/examples/blog-starter-typescript
https://github.com/vercel/next.js/tree/canary/examples/with-mobx

I tried using polyfills, but had no success so far.

What can be done, to get it running in IE11? Is there a working example somewhere?

**Expected Behavior**

The example
https://github.com/vercel/next.js/tree/canary/examples/with-next-translate

should work in IE 11

**To Reproduce**

run
```
yarn create next-app --example with-next-translate with-next-translate-app
cd with-next-translate-app
yarn dev
```
then open http://localhost:3000 in IE 11 and look at the errors in developer mode

**Comment by aralroca** [comment]
@1R053 Maybe this helps you: https://github.com/vinissimus/next-translate/issues/435#issuecomment-758244298

**Comment by 1R053** [comment]
great, the workaround to include this in _app.js worked:
```
import '@formatjs/intl-getcanonicallocales/polyfill';
import '@formatjs/intl-locale/polyfill';
import '@formatjs/intl-pluralrules/polyfill'
import '@formatjs/intl-pluralrules/locale-data/en'
import '@formatjs/intl-pluralrules/locale-data/ru'
```

thanks for you quick response
