### ISSUE TITLE
Ignore markdown file in /locales

### ISSUE THREAD

**Issue by cdelacombaz** [vinissimus/next-translate#454]
Hi

Is it possible to ignore markdown files or some specific files from the /locales folder?

I am working on a project with some other developers and we like to have a readme file with some guidelines on how to structure the folders and files. We now always get a warning in the console.

![Screenshot 2021-01-19 at 08 33 41](https://user-images.githubusercontent.com/45405753/105002311-5459ca00-5a31-11eb-88ef-0fe89076c285.png)

![Screenshot 2021-01-19 at 08 33 55](https://user-images.githubusercontent.com/45405753/105002318-591e7e00-5a31-11eb-8c0f-699cdac0e550.png)

We are using next 10.0.3 and next-translate 1.0.0.

BR, Cedric

**Comment by aralroca** [comment]
I think this is the problem of the dynamic import of webpack. By doing [this](https://github.com/vinissimus/next-translate/blob/master/src/plugin/utils.ts#L6), it causes all the files that exist inside `locales` to be created as chunks.  Including the markdown file, which complaints about not having a proper loader. I am not very clear how from next-translate we can solve this...

**Comment by aralroca** [comment]
A solution you could choose is to use a different structure and overwrite the import in the property `loadLocalesFrom`. 

I'm not sure if replacing `./locales/${lang}/${ns}` to `./locales/${lang}/${ns}.json` (adding the `.json`) is enough or not. We do not put an extension to give the opportunity to work by default also with other types  like `.js`.

```js
{
  // ...rest of config
  "loadLocaleFrom": (lang, ns) =>
    // Adding the .json at the end to tell webpack that you only want the .json files
    import(`./locales/${lang}/${ns}.json`).then((m) => m.default),
}
```

**Comment by cdelacombaz** [comment]
> A solution you could choose is to use a different structure and overwrite the import in the property `loadLocalesFrom`.
> 
> I'm not sure if replacing `./locales/${lang}/${ns}` to `./locales/${lang}/${ns}.json` (adding the `.json`) is enough or not. We do not put an extension to give the opportunity to work by default also with other types like `.js`.
> 
> ```js
> {
>   // ...rest of config
>   "loadLocaleFrom": (lang, ns) =>
>     // Adding the .json at the end to tell webpack that you only want the .json files
>     import(`./locales/${lang}/${ns}.json`).then((m) => m.default),
> }
> ```

Thanks for the quick response! This worked :)
