### ISSUE TITLE
Failing to build on vercel after upgrade to 1.0.2-canary.2

### ISSUE THREAD

**Issue by vimutti77** [vinissimus/next-translate#459]
After upgrade next-translate version from `1.0.2-canary.1` to `1.0.2-canary.2`. I get these errors when building on vercel.
```
21:30:40.344 | 🚨 [next-translate] In Next 10.x.x there is an issue related to i18n and getInitialProps. We recommend to replace getInitialProps to getServerSideProps on /_error.tsx. Issue: https://github.com/vercel/next.js/issues/18396
-- | --
21:30:40.346 | 🚨 [next-translate] In Next 10.x.x there is an issue related to i18n and getInitialProps. We recommend to replace getInitialProps to getServerSideProps on /404.tsx. Issue: https://github.com/vercel/next.js/issues/18396
21:30:40.348 | 🚨 [next-translate] In Next 10.x.x there is an issue related to i18n and getInitialProps. We recommend to replace getInitialProps to getServerSideProps on /index.tsx. Issue: https://github.com/vercel/next.js/issues/18396

... (The errors occur on every page)
```
It only fail to build on vercel. I can still build on my local computer.

**Comment by aralroca** [comment]
@vimutti77 In theory these are just warnings... Maybe Vercel doesn't like getInitialProps? Maybe the question here is to see why he is using getInitialProps? Could you share your code to see why it uses getInitialProps? Thanks!

**Comment by vimutti77** [comment]
It's just a static page without getInitialProps or getServerSideProps.

This is my build logs of version `1.0.2-canary.1`
![image](https://user-images.githubusercontent.com/27840664/105390755-f48b3b00-5c4b-11eb-9bdc-c8c8ef65b581.png)

This is my build logs of version `1.0.2-canary.2`
![image](https://user-images.githubusercontent.com/27840664/105391206-77ac9100-5c4c-11eb-9983-6154f7fae361.png)

i18n.js
```
module.exports = {
  locales: ['en', 'th'],
  defaultLocale: 'en',
  loadLocaleFrom: (locale, namespace) =>
    import(`@next-translate-root/src/locales/${locale}/${namespace}`).then((m) => m.default),
  pages: {
    '*': ['common', 'error', 'app', 'enum'],
    '/404': [],
    '/': ['p.Index'],
    ...
  },
}
```

next.config.js
```
const nextTranslate = require('next-translate')

module.exports = nextTranslate({
  distDir: 'build',
})
```

**Comment by aralroca** [comment]
@vimutti77 it is possible to share your `_error.tsx` or `index.ts` code?

**Comment by vimutti77** [comment]
@aralroca  Look like the cause of the problem is from `NextPage`

404.tsx (error)
```
import { NextPage } from 'next'
import useTranslation from 'next-translate/useTranslation'
import React from 'react'

const NotFoundPage: NextPage = () => {
  const { t } = useTranslation()
  return <div>{t('error:page-not-found')}</div>
}

export default NotFoundPage
```

404.tsx (no error)
```
import useTranslation from 'next-translate/useTranslation'
import React from 'react'

const NotFoundPage = () => {
  const { t } = useTranslation()
  return <div>{t('error:page-not-found')}</div>
}

export default NotFoundPage
```

**Comment by aralroca** [comment]
@vimutti77 Ok, we have to add this failing case in the hasHOC helper test... The helper gets confused and thinks it is a HOC. Thanks for sharing the code.

**Comment by aralroca** [comment]
@vimutti77 I prereleased [1.0.2-canary.6](https://github.com/vinissimus/next-translate/releases/tag/1.0.2-canary.6) with this change. Is it working now for you? I'm going to close the issue. Feel free to reopen or comment if you have any trouble! Thanks!
