### ISSUE TITLE
Is this library supported with nextjs/serverless?

### ISSUE THREAD

**Issue by karthikeyan676** [vinissimus/next-translate#468]

**Comment by aralroca** [comment]
Yes, it is.

**Comment by karthikeyan676** [comment]
Hi @aralroca nexts/serverless is still not supported. I just deployed the code to aws and I'm getting Access denied

**Comment by aralroca** [comment]
@karthikeyan676 can you share your code to reproduce it? Thanks

**Comment by karthikeyan676** [comment]
Hey, I tried the new version of next/serverless framework. It's working fine now. Thanks.
