### ISSUE TITLE
Automatic Static Optimization breaks with next-translate on pages with dynamic routes

### ISSUE THREAD

**Issue by clementoriol** [vinissimus/next-translate#469]
# Issue

By default, Next.js statically optimize pages if they don't use `getServerSideProps` and `getInitialProps`

From their doc :
```
Next.js automatically determines that a page is static (can be prerendered) if it has no blocking data requirements. This determination is made by the absence of getServerSideProps and getInitialProps in the page.
```

This works on pages with or without dynamic routes (routes with query params).

**However, this behavior is not kept when using next-translate.**
Pages without dynamic routes are still statically optimized, but pages with dynamic routes are rendered with server-side rendering.

Which means that a route that doesn't fetch data, or only do it client-side, will compile the pages on each request, for nothing. 

This issue exists on every version starting with v1 from what I've seen (1.0.0, 1.0.1, and the latest 1.0.2 canary versions)

# Expected behavior 

Pages not using `getServerSideProps` or `getInitialProps` should always be statically optimized

# Reproduction 

- clone [this repo](https://github.com/clementoriol/with-next-translate-sso-dynamic-route-issue) (based on the `with-next-translate` template)
- check that the `pages/[id].js` page does not use `getServerSideProps` or `getInitialProps`
- run `yarn build`
- index.js is statically optimized, [id].js is not : 
![Capture d’écran 2021-01-25 à 13 42 30](https://user-images.githubusercontent.com/3337108/105707408-300b5b00-5f13-11eb-895c-a56c7aca5c9f.png)

**Comment by clementoriol** [comment]
Ok, reading https://github.com/vinissimus/next-translate#how-are-translations-loaded I realize that this might be expected behavior.

However, I'd like to point 2 things : 
- The difference of behavior between vanilla Next.js and Next.js with next-translate on this point is very confusing. I feel like we should at lease get SSG by default on pages without `getServerSideProps` or `getInitialProps`, even with dynamic routes 
- Even knowing how translations are loaded, I don't how to to avoid SSG in my use (pages with static skeletons and client-side queries). I feel like this is a valid use case and there should be some option for me to get an precompiled page shell with translations

What do you think about all this ?

**Comment by aralroca** [comment]
@clementoriol  In these pages, you need to define the  `getStaticPaths` manually, next-translate can't do it for you. If you define the `getStaticPaths`, then next-translate will use `getStaticProps` by default.

**Comment by clementoriol** [comment]
But sometimes using getStaticPaths is not an option. If you render public, SEO pages, sure, fetch all the slugs in getStaticPaths.
But if you're rendering a private page like some payment dashboard pages, with multiple dynamic params in the route, sometimes you just want to get a static page shell and do the queries from the front-end.

Next.js allows that by default, it just precompiles the shell and you know the query params will be empty on the first render, and then rehydrated client-side.
This is an awesome feature that allows to render a page skeleton quickly from vercel cdn, then when the client gets the params to fetch the data client-side.

It's a bit of a bummer to see this gone with next-translate.

Don't you think there's a way we could get closer to this default behavior ?

**Comment by aralroca** [comment]
Next-translate uses a loader to load the translations for each locale. And even if you don't have one, it needs one. And this is what the Webpack loader does. In dynamic pages is not possible to use `getStaticProps` without `getStaticPaths`, this is why (by default) it uses `getServerSideProps` to load the translations. But again, you can just write the `getStaticPaths` and it's going to use the automatic static optimization for dynamic pages.

in versions prior to 0.19 of next-translate we used a workaround to compile under `_pages` a static structure, however, since version 10 of Next.js we opted to adapt to the new i18n routing feature of Next.js. This change provided many good things, but this one, in particular, is a bit of a setback to deal with.

**Comment by clementoriol** [comment]
@aralroca Thank you for taking the time to detail this :) This is way more clear to me now.
I'll be closing this, hopes this serves as reference for people confused about this behavior.

I guess the best approach for this use case would be to use : 
```
export const getStaticPaths = async () => {
  return {
    paths: [],
    fallback: "blocking"
  };
};
```

or even 
```
export const getStaticPaths = async () => {
  return {
    paths: [],
    fallback: true,
  };
};
```
But in this last case locales won't be available, so you have to make sure your loading skeleton doesn't display any.

**Comment by berndartmueller** [comment]
@clementoriol Why are locales not available in the last case you mentioned (with `fallback: true`)?

**Comment by EyadAlghamdi** [comment]
@clementoriol be careful with this approach, if you have for example a dynamic page, you will be asking nextjs to create a cache version of EACH page with a unique id..
that means, for example, if you have IDs of 10,000 items, every time an item is visited, a page is created and cached, until you have 10k pages... 

if you dont have that much data its fine, but just a thought for others

**Comment by bryantobing12** [comment]
@EyadAlghamdi   so how did you manage to only load the translation necessary for the dynamic page?
