### ISSUE TITLE
Adding ESLint

### ISSUE THREAD

**Issue by andrehsu** [vinissimus/next-translate#474]
I am thinking of adding ESLint to this project. I would
1. add ESLint,
2. add ESLint to husky,
3. use the `eslint:recommended` and the `plugin:typescript-eslint/recommended` rule sets. They are both semantic lint rules, not stylistic lint rules, and
4. fix the problems highlighted by the new lint rules.

Part of the rule set would, for example, require that all exported functions have a defined returned type, which would greatly improve type safety. Adding ESLint would highlight some hidden issues, prevent technical debt going forward, and ensure that future contributions meet a minimum standard.

@aralroca what do you think?

**Comment by aralroca** [comment]
Okay @andrehsu , that might be a good idea. It will have to be integrated with prettier as well, right?

**Comment by andrehsu** [comment]
@aralroca they'll run separately since the rules in those two ESLint rule sets don't deal with style
