### ISSUE TITLE
Plurals aren't working in my Next.js v10 project

### ISSUE THREAD

**Issue by meerita** [vinissimus/next-translate#477]
I am trying to use plurals and they don't work at all.

I've tried to use useTranslate or Trans and they don't work basically with the _0, _one, _two, etc.

In my common .json file somewhere I have setup this:

```
{
 "postFile": {
 "comment_0": "{{count}} comentarios",
  "comment_one": "{{count}} comentario",
  "comment_two": "{{count}} comentarios",
  "comment_other": "{{count}} comentarios",
  }
}
```

Then in my code, i have this translate instruction:

```
<a>{t('common:postItem.comment', { count: comments })}</a>
```

This basically don't render properly my, all i see is:

```
common:postItem.comment
```

I've tried to use useTranslation and Trans methods and both fails. What I am doing wrong with plurals?

**Comment by aralroca** [comment]
@meerita ok, looks an issue related to nested objects + plural form. Moving the comment at the first level works for you?

```json
{
 "comment_0": "{{count}} comentarios",
 "comment_one": "{{count}} comentario",
 "comment_two": "{{count}} comentarios",
 "comment_other": "{{count}} comentarios",
}
```

**Comment by aralroca** [comment]
In [Spanish](https://unicode-org.github.io/cldr-staging/charts/37/supplemental/language_plural_rules.html#es) there is only one plural form (`_other`)... The other plural forms are not applicable in Spanish:

```
_zero
_one (singular)
_two (dual)
_few (paucal)
_many (also used for fractions if they have a separate class)
```

The numbers `_0`, `_12` is for the exact match! not for the plural form.

**Comment by meerita** [comment]
How I interpret the plurals cases:

```
_zero // 0 comentarios
_one (singular) // 1 comentario
_two (dual) // 2 comentarios
_few (paucal) // unos pocos comentarios
```
So for my code, I only need 3 cases:

{
 "comment_0": "{{count}} comentarios",
 "comment_one": "{{count}} comentario",
 "comment_other": "{{count}} comentarios",
}

**Comment by aralroca** [comment]
@meerita We are following the CLDR Specification, and you want this:

_0 // 0 comentarios
_1  // 1 comentario
_2  // 2 comentarios
_other // unos pocos comentarios

The only plural form here is `_other` (because Spanish only have 1 plural form), the other are exact matches.

**Comment by meerita** [comment]
Oh, great it worked!

**Comment by aralroca** [comment]
Nice !👍  😊  I'll close the issue then! Feel free to report more issues if you have more troubles / dubts
