### ISSUE TITLE
Error: i18n support is not compatible with next export.

### ISSUE THREAD

**Issue by elbopha** [vinissimus/next-translate#482]
Hello,

Can we do `next export` when using `next-translate`?
Is there other way to generate static HTML page with translation?

I got this error when using `next export` with `next-translate` [basic example](https://github.com/vinissimus/next-translate/tree/master/examples/basic).
`Error: i18n support is not compatible with next export.`

Regards,

**Comment by aralroca** [comment]
We are using Next.js i18n routing underneath, and until Next.js supports it, it will not be possible. 

Reference: https://nextjs.org/docs/advanced-features/i18n-routing#how-does-this-work-with-static-generation

> Note that Internationalized Routing does not integrate with next export as next export does not leverage the Next.js routing layer. Hybrid Next.js applications that do not use next export are fully supported.
