### ISSUE TITLE
Lang detection is wrong after updating to v1.0.2

### ISSUE THREAD

**Issue by clementoriol** [vinissimus/next-translate#487]
Juste updated from `1.0.1` to `1.0.2` and seeing new issues with lang detection.
The lang from the `useTranslation` hook doesn't match the router lang.
This wasn't a problem before.

Current route is `http://localhost:3000/fr/auth/login`,  so I expect the lang to be `fr`.

Logging lang from the Page component : 
```
function Login() {
  const router = useRouter();
  const { t, lang } = useTranslation();

  console.log({ lang, routerLang: router.locale });
  (... other code)
}
```

gives me 
```
{lang: "en", routerLang: "fr"}
``` 
and translations are showing up in english.

here is my `i18n.js` config file : 
```
const hoistNonReactStatics = require("hoist-non-react-statics");

module.exports = {
  locales: ["en", "fr"],
  defaultLocale: "en",
  staticsHoc: hoistNonReactStatics,
  pages: {
    "*": ["common", "yup"],
    "/auth/login": ["auth"],
    (... other routes)
  },
};
```

I'll see if I can make a minimal reproduction repository

**Comment by clementoriol** [comment]
Did some extra tests, issue starts with `1.0.2-canary.2`

Looks like it's an issue with the HoC detection, I start getting this warnings in `1.0.2-canary.2` where it breaks : 
```
🚨 [next-translate] In Next 10.x.x there is an issue related to i18n and getInitialProps. We recommend to replace getInitialProps to getServerSideProps on /auth/login.tsx. Issue: https://github.com/vercel/next.js/issues/18396
```

Page is structured like this : 
```
[redacted imports for readability]

export type LoginType = "email" | "phone";
export const isLoginType = (s: string): s is LoginType =>
  s === "email" || s === "phone";

export const loginSchema = yup.object({
  loginType: yup.string().oneOf(["email", "phone"]).defined(),
  email: yup
    .string()
    .email()
    .when("loginType", (loginType: LoginType, schema: any) => {
      if (loginType === "email") {
        return schema.defined();
      }
    }),
  phone: yup.string().when("loginType", (loginType: LoginType, schema: any) => {
    if (loginType === "phone") {
      return schema.defined();
    }
  }),
});

function Login() {
  const router = useRouter();
  const { t, lang } = useTranslation();

  return (
    <>
      <Head title="Login" />
      <div>Page content</div>
    </>
  );
}

export default withLayout(<LoginLayout />)(Login);
```

**Comment by aralroca** [comment]
`getInitialProps` has a known issue on Next.js: https://github.com/vercel/next.js/issues/18396 ...

**Comment by clementoriol** [comment]
Yeah sorry about that, just found out and edited my second post. 
I'm closing this as you're aware and there's not much we can do right now, let's just hope this gets sorted on Next side because it's confusing if you don't know the whys and the hows.

**Comment by binajmen** [comment]
> ```
> export function getServerSideProps() { return { props: {} }; }
> ```

Quick fix that is fine for me for the time being, thank you! Hope `Next.js` will react fast.

I'd suggest to use `getStaticProps()` (works too) when you don't need server rendering, just for pure optimization.

```js
export function getStaticProps() { return { props: {} }; }
```
