### ISSUE TITLE
Unlocalize the routes

### ISSUE THREAD

**Issue by HoekWax** [vinissimus/next-translate#492]
Hello,

For now my site is using "en" and "fr" languages, "en" by default.
When I switch the lang to french the url is localhost/fr

Is it possible to have the site in french or any other language and have the site still on localhost/ ?

I didn't find the answer in the doc, sorry if I missed it.

Thanks

**Comment by aralroca** [comment]
I don't understand the question sorry

**Comment by HoekWax** [comment]
Currently, if I open localhost/post/1234 , the post will be in english, if I change the language to french, it will open localhost/fr/post/1234

Is it possible to change the language to french and still have the url as localhost/post/1234 ?
Without the /fr being shown

**Comment by aralroca** [comment]
@HoekWax all the i18n routing part is part of Next.js. I recommend taking a look at the [Next.js documentation](https://nextjs.org/docs/advanced-features/i18n-routing). There are 2 strategies:

## [Sub-path Routing](https://nextjs.org/docs/advanced-features/i18n-routing#sub-path-routing)

Sub-path Routing puts the locale in the url path.

**i18n.js**
```js
module.exports = {
    locales: ['en-US', 'fr', 'nl-NL'],
    defaultLocale: 'en-US',
}
```

With the above configuration en-US, fr, and nl-NL will be available to be routed to, and en-US is the default locale. If you have a pages/blog.js the following urls would be available:

- /blog
- /fr/blog
- /nl-nl/blog

The default locale does not have a prefix.

## [Domain Routing](https://nextjs.org/docs/advanced-features/i18n-routing#domain-routing)

By using domain routing you can configure locales to be served from different domains:

**i18n.js**
```js
module.exports = {
    locales: ['en-US', 'fr', 'nl-NL', 'nl-BE'],
    defaultLocale: 'en-US',

    domains: [
      {
        domain: 'example.com',
        defaultLocale: 'en-US',
      },
      {
        domain: 'example.fr',
        defaultLocale: 'fr',
      },
      {
        domain: 'example.nl',
        defaultLocale: 'nl-NL',
        // specify other locales that should be redirected
        // to this domain
        locales: ['nl-BE'],
      },
    ],
 }
```

For example if you have pages/blog.js the following urls will be available:

- example.com/blog
- example.fr/blog
- example.nl/blog
- example.nl/nl-BE/blog


-----

If you want to use the same locale for the same page (although this is not recommended), you will have to opt to manage it yourself using next-translate's [I18nProvider](https://github.com/vinissimus/next-translate/tree/1.0.2#i18nprovider).

**Comment by HoekWax** [comment]
Thanks I'll look into this
