### ISSUE TITLE
Setup dynamic paths in i18n to recognize multiple paths

### ISSUE THREAD

**Issue by meerita** [vinissimus/next-translate#494]
This is my i18n.json file and I want to setup my settings.json to be used under any URL like /settings/about, /settings/about/password, etc. like I can do with common "*" but without having to specify "/settings", "/settings/about", etc. Is there any way to make a regex pattern?

<pre>{
  "locales": ["en", "es", "jp"],
  "defaultLocale": "en",
  "pages": {
    "*": ["common"],
    "/recent": ["recent"],
    "/login": ["login"],
    "/register": ["register"],
    "/recover_password": ["recover_password"],
    "/settings": ["settings"],
    "/settings/account": ["settings"]
  }
}</pre>

What would be nice is to do something like this:

<pre>{
  "locales": ["en", "es", "jp"],
  "defaultLocale": "en",
  "pages": {
    "*": ["common"],
    "/recent": ["recent"],
    "/login": ["login"],
    "/register": ["register"],
    "/recover_password": ["recover_password"],
    "/settings/*": ["settings"],
  }
}</pre>

**Comment by aralroca** [comment]
Yes!! It is!! You can do it in this way:

```diff
{
  "locales": ["en", "es", "jp"],
  "defaultLocale": "en",
  "pages": {
    "*": ["common"],
    "/recent": ["recent"],
    "/login": ["login"],
    "/register": ["register"],
    "/recover_password": ["recover_password"],
-    "/settings/*": ["settings"],
+    "rgx:^/settings": ["settings"],
  }
}
```

Example: https://github.com/vinissimus/next-translate/blob/1.0.2/examples/complex/i18n.js#L9

**Comment by meerita** [comment]
Thanks! this would be helpful on the readme!

**Comment by aralroca** [comment]
It is, in the configuration section 😊

![image](https://user-images.githubusercontent.com/13313058/107257539-11d94b00-6a3b-11eb-9dca-b899532a9eca.png)
