### ISSUE TITLE
Removed returning objects from t in 1.0.2?

### ISSUE THREAD

**Issue by lorenzosignoretti** [vinissimus/next-translate#495]
Hi team,

I had been using the t function to **return objects as array** using the `{returnObjects: true}` argument. More specifically I would cast the return object of the function to an array with some syntax along the lines of:
```javascript
  const comparisonItems = t<Array<T>>("namespace:key", {}, { returnObjects: true })
```

**In 1.0.2 this is no longer possible**, in spite of the fact that the documentation [suggests otherwise](https://github.com/vinissimus/next-translate#7-nested-translations). In fact, the type Translation of the function t has been changed to
```javascript
export type Translate = (
  i18nKey: string | TemplateStringsArray,
  query?: TranslationQuery | null,
  options?: { returnObjects?: boolean; fallback?: string | string[] }
) => string
```
from
```javascript
export interface Translate {
    <T = string>(i18nKey: string | TemplateStringsArray, query: TranslationQuery | null | undefined, options: {
        returnObjects?: boolean;
        fallback?: string | string[];
    }): T;
    (i18nKey: string | TemplateStringsArray, query: TranslationQuery | null | undefined): string;
    (i18nKey: string | TemplateStringsArray): string;
}
```
in 1.0.0.

I would like to understand the reasons for this change. Do you recommend returning arrays in some other ways? If this is an unintended bug, I am happy to open a PR with changes to restore the functionality.

Thanks.

**Comment by aralroca** [comment]
@lorenzosignoretti this should be already solved in **1.0.3-canary.1**. Was introduced in 1.0.2 after a mistake in a refactor (sorry)
