### ISSUE TITLE
How to make it work in a HOC.

### ISSUE THREAD

**Issue by mateus-schultz** [vinissimus/next-translate#500]
In my app, I have some routes to protect... so the best way I found to do this was to make a HOC component (I'm using NextJs btw).

```
  const withAuth = (Component: React.ComponentType & NextComponentType) => {
    const Auth = () => {
      const router = useRouter();
      const token = useSelector<ApplicationState, string>(
        state => state.auth.token,
      );
  
      if (!token) {
        router.push('/login');
      }
  
      return <Component />;
    };
  
    // Copy getInitial props so it will run as well
    if (Component.getInitialProps) {
      Auth.getInitialProps = Component.getInitialProps;
    }
  
    return Auth;
  };
  
  export default withAuth;
```
With this HOC, I surround some pages like so...

```
const Dashboard: React.FC = () => {
  const router = useRouter();
  const { t } = useTranslation('dashboard');

  return (
    <div>
      <Link locale="en-US" href={router.pathname}>
        Change to english
      </Link>
      <Link locale="pt-BR" href={router.pathname}>
        Change to portuguese
      </Link>

      <h1>{t('hello')}</h1>
    </div>
  );
};

export default withAuth(Dashboard);
```
My problem is that when I do this, the page isn't compiled with the translations, so I believe something is missing in my HOC(I know this because the translation works when I remove the withAuth() in the page). Can someone help me on this please.

**Comment by mateus-schultz** [comment]
OK guys, I found a correction for this problem.

my _app.tsx was like this and the translation wasn't working
```
...
export default function MyApp({ Component, pageProps }) {
  const router = useRouter();

  const noLayout = ['/login', '/logout', '/forget-password'];

  return (
    <Provider store={store}>
      <PersistGate persistor={persistor}>
        {noLayout.includes(router.pathname) ? (
          <Component {...pageProps} />
        ) : (
          <Layout>
            <Component {...pageProps} />
          </Layout>
        )}
      </PersistGate>
    </Provider>
  );
}
```

I don't know why, but I changed this component to look like this
```
...
import { AppProps } from 'next/app';

const MyApp: React.FC<AppProps> = ({ Component, pageProps }) => {
  const router = useRouter();

  const noLayout = ['/login', '/logout', '/forget-password'];

  return (
    <Provider store={store}>
      <PersistGate persistor={persistor}>
        {noLayout.includes(router.pathname) ? (
          <Component {...pageProps} />
        ) : (
          <Layout>
            <Component {...pageProps} />
          </Layout>
        )}
      </PersistGate>
    </Provider>
  );
};

export default MyApp;
```

Just typescripting the function, the translation worked again. I have no idea of why this happened and why it is fixed. LOL

**Comment by aralroca** [comment]
> OK guys, I found a correction for this problem.
> 
> my _app.tsx was like this and the translation wasn't working
> 
> ```
> ...
> export default function MyApp({ Component, pageProps }) {
>   const router = useRouter();
> 
>   const noLayout = ['/login', '/logout', '/forget-password'];
> 
>   return (
>     <Provider store={store}>
>       <PersistGate persistor={persistor}>
>         {noLayout.includes(router.pathname) ? (
>           <Component {...pageProps} />
>         ) : (
>           <Layout>
>             <Component {...pageProps} />
>           </Layout>
>         )}
>       </PersistGate>
>     </Provider>
>   );
> }
> ```

This is transpiled by next-translate 1.0.2 to:

```js
import __i18nConfig from "@next-translate-root/i18n";
import __appWithI18n from "next-translate/appWithI18n";

const __Page_Next_Translate__ = function MyApp({ Component, pageProps }) {
  const router = useRouter();

  const noLayout = ["/login", "/logout", "/forget-password"];

  return (
    <Provider store={store}>
      <PersistGate persistor={persistor}>
        {noLayout.includes(router.pathname) ? (
          <Component {...pageProps} />
        ) : (
          <Layout>
            <Component {...pageProps} />
          </Layout>
        )}
      </PersistGate>
    </Provider>
  );
};

export default __appWithI18n(__Page_Next_Translate__, {
  ...__i18nConfig,
  isLoader: true,
  skipInitialProps: false,
  loadLocaleFrom: (l, n) =>
    import(\`@next-translate-root/locales/${l}/${n}`).then((m) => m.default),
});
```


> I don't know why, but I changed this component to look like this
> 
> ```
> ...
> import { AppProps } from 'next/app';
> 
> const MyApp: React.FC<AppProps> = ({ Component, pageProps }) => {
>   const router = useRouter();
> 
>   const noLayout = ['/login', '/logout', '/forget-password'];
> 
>   return (
>     <Provider store={store}>
>       <PersistGate persistor={persistor}>
>         {noLayout.includes(router.pathname) ? (
>           <Component {...pageProps} />
>         ) : (
>           <Layout>
>             <Component {...pageProps} />
>           </Layout>
>         )}
>       </PersistGate>
>     </Provider>
>   );
> };
> 
> export default MyApp;
> ```
> 
> Just typescripting the function, the translation worked again. I have no idea of why this happened and why it is fixed. LOL

And this is transpiled to:

```ts
import __i18nConfig from "@next-translate-root/i18n";
import __appWithI18n from "next-translate/appWithI18n";

import { AppProps } from "next/app";

const MyApp: React.FC<AppProps> = ({ Component, pageProps }) => {
  const router = useRouter();

  const noLayout = ["/login", "/logout", "/forget-password"];

  return (
    <Provider store={store}>
      <PersistGate persistor={persistor}>
        {noLayout.includes(router.pathname) ? (
          <Component {...pageProps} />
        ) : (
          <Layout>
            <Component {...pageProps} />
          </Layout>
        )}
      </PersistGate>
    </Provider>
  );
};

const __Page_Next_Translate__ = MyApp;

export default __appWithI18n(__Page_Next_Translate__, {
  ...__i18nConfig,
  isLoader: true,
  skipInitialProps: false,
  loadLocaleFrom: (l, n) =>
    import(`@next-translate-root/locales/${l}/${n}`).then((m) => m.default),
});
```

@mateus-schultz Apparently, I don't see any problems during transpilation.... What version of next-translate do you use?

**Comment by mateus-schultz** [comment]
@aralroca , Thanks for your reply.
This is the version:
"dependencies": {
    "next": "10.0.4",
    "next-translate": "^1.0.2",
    "react": "17.0.1",
    "react-dom": "17.0.1",
 }

**Comment by soulcactus** [comment]
it really works!

> OK guys, I found a correction for this problem.
> 
> my _app.tsx was like this and the translation wasn't working
> 
> ```
> ...
> export default function MyApp({ Component, pageProps }) {
>   const router = useRouter();
> 
>   const noLayout = ['/login', '/logout', '/forget-password'];
> 
>   return (
>     <Provider store={store}>
>       <PersistGate persistor={persistor}>
>         {noLayout.includes(router.pathname) ? (
>           <Component {...pageProps} />
>         ) : (
>           <Layout>
>             <Component {...pageProps} />
>           </Layout>
>         )}
>       </PersistGate>
>     </Provider>
>   );
> }
> ```
> 
> I don't know why, but I changed this component to look like this
> 
> ```
> ...
> import { AppProps } from 'next/app';
> 
> const MyApp: React.FC<AppProps> = ({ Component, pageProps }) => {
>   const router = useRouter();
> 
>   const noLayout = ['/login', '/logout', '/forget-password'];
> 
>   return (
>     <Provider store={store}>
>       <PersistGate persistor={persistor}>
>         {noLayout.includes(router.pathname) ? (
>           <Component {...pageProps} />
>         ) : (
>           <Layout>
>             <Component {...pageProps} />
>           </Layout>
>         )}
>       </PersistGate>
>     </Provider>
>   );
> };
> 
> export default MyApp;
> ```
> 
> Just typescripting the function, the translation worked again. I have no idea of why this happened and why it is fixed. LOL
