### ISSUE TITLE
Duplicate nested routes for default locale

### ISSUE THREAD

**Issue by lorenzosignoretti** [vinissimus/next-translate#501]
Hi team,

I came across the following issue: all routes generated for a specific locale seem to be accessible when nested behind the default locale path. That is, a page like `www.website.com/it/my-page` is also accessible from `www.website.com/en/it/my-page`.

Is there any way to prevent this from happening? I am assuming it may be something in the way the regex expression parsing the url determines valid urls. However, I did not dig deep enough in the code to find exactly why this is happening.

 Note that I am currently using next-translate 1.0.0 (because of [this issue](https://github.com/vinissimus/next-translate/issues/495)) with next 10.0.6, but I had experienced the same problem on 1.0.2.

Thank you in advance for your help :).

**Comment by lorenzosignoretti** [comment]
HI @aralroca any news on this behaviour? Is it something you were already aware of

**Comment by aralroca** [comment]
@lorenzosignoretti  It's a bug from Next.js, not Next-translate. I can reproduce the same error with the i18n routing example: https://github.com/vercel/next.js/tree/master/examples/i18n-routing

Next-translate uses the i18n routing feature of Next.js. I think the best thing to do would be to report this bug directly to the Next.js repo so they can fix it since there is little we can do from Next-translate. Thank you very much.

**Comment by lorenzosignoretti** [comment]
For reference of anyone facing the same issue a temporary (brutal) workaround could be to leverage [next's redirects](https://nextjs.org/docs/api-reference/next.config.js/redirects) as follows:
```javascript
module.exports = {
// ... your existing next.config.js
  i18n: {
    locales: ["en", "it", "es"],
    defaultLocale: "en",
    localeDetection: false,
  },

  async redirects() {
    return [
      {
        source: "/en/it/:slug*/",
        destination: "/it/:slug*/", // automatically passes the locale on
        locale: false,
        permanent: true,
      },
]
}
}
```

**Comment by aralroca** [comment]
@lorenzosignoretti it would be great if you report this issue in the Next.js repo so they can fix it.
