### ISSUE TITLE
When using the en/ru prefix in the url path, getServerSideProps query.page is not available

### ISSUE THREAD

**Issue by Svyatoslav16** [vinissimus/next-translate#503]
When 

when the page is loaded or reloaded for the first time, query.page is available, but if you use the back arrows in the browser query.page is no longer available, but only if you use a prefix in the url

**Without prefix**

![Screenshot from 2021-02-12 11-29-12](https://user-images.githubusercontent.com/44878382/107745607-9ff84e80-6d25-11eb-9faa-1f5fcac26504.png)

![Screenshot from 2021-02-12 11-24-14](https://user-images.githubusercontent.com/44878382/107746046-493f4480-6d26-11eb-9efd-cb2c5a34d641.png)

**With prefix**
![Screenshot from 2021-02-12 11-35-50](https://user-images.githubusercontent.com/44878382/107746210-7e4b9700-6d26-11eb-9e25-40b6086802a0.png)

![Screenshot from 2021-02-12 11-24-07](https://user-images.githubusercontent.com/44878382/107746300-a5a26400-6d26-11eb-9903-98ec26156a86.png)

![Screenshot from 2021-02-12 11-23-58](https://user-images.githubusercontent.com/44878382/107746235-89062c00-6d26-11eb-9196-4cc82d745444.png)

Links are made with the help of the

```import Link from 'next/link'```

**Comment by aralroca** [comment]
@Svyatoslav16 This doesn't look like a next-translate bug, it's the behavior of Next.js, without next-translate it happens too, right?

**Comment by Svyatoslav16** [comment]
> @ Svyatoslav16 Это не похоже на ошибку next-translate, это поведение Next.js, без next-translate тоже происходит, верно? https://nextjs.org/docs/advanced-features/i18n-routing

Apparently so

**Comment by quyphan97** [comment]
Have you fixed this error yet? please help me
