### ISSUE TITLE
rewrites to api are broken

### ISSUE THREAD

**Issue by indeedhat** [vinissimus/next-translate#504]
- next: 10.0.2
- next-translate: 1.0.2

with next-translate in my project i am no longer able to use the rewrites() entry in the next config to rewrite to api endpoints.
I have tried this with multiple different api endpoints.
> it is worth noting that rewrites seem to work fine if im not routing to the api

if i remove the nextTranslate() from my config then the rewrites start working again but obviously translations dont work

the error
```
Error: Objects are not valid as a React child (found: [object Promise]). If you meant to render a collection of children, use an array instead.
```
```js
../pages/_document.tsx (90:33) @ Function.getInitialProps

  88 |     }
  89 | 
> 90 |     const { html, head } = await ctx.renderPage({ enhanceApp })
     |                                 ^
  91 |     const styles = [...flush()]
  92 |     return { html, head, styles }
  93 |   }
```

my config
```js
module.exports = nextTranslate({
    ....
    rewrites() {
        return [
            ...
            {
                source: '/:file.txt',
                destination: '/api/txt?file=:file'
            }
        ];
    }
};
```

**Comment by aralroca** [comment]
@indeedhat do you have a reproducible example? 🙏 Thanks

**Comment by indeedhat** [comment]
Thanks for the quick response, ill knock together an example project for and link it here tomorrow.

**Comment by indeedhat** [comment]
I have spent the last hour or so trying to get this to happen on a fresh project and no matter what i do it just works this time so the issue really might have very little to do with next-translate.

I assumed thats was where the issue was because if i removed the call to `nextTranslate()` from my config it worked fine, but now im questioning it.

As soon as i get time ill try stripping back the project i am having the issue with and see if i cant work out what is going on. If i do manage to find the issue ill report back but for now its probably worth going with "This is not an issue with next-translate".

Sorry for the waste of time.

**Comment by indeedhat** [comment]
After trying to strip back my project to get the rewrites working i realised i was an idiot.

The example project was setup using next: 10.0.7 not 10.0.2.

With the later version of next it works perfectly so the issue was with them.
