### ISSUE TITLE
Blocking error on Safari v. 12.x

### ISSUE THREAD

**Issue by CleverUpEng** [vinissimus/next-translate#508]
Good morning,
on Safari on iOS version 12.4 we're having a blocking error that prevents even site loading:
`TypeError: undefined is not a constructor (evaluating 'new Intl.PluralRules(lang)')`

The line throwing the error is the following, inside file I18nProvider.js:
`var pluralRules = new Intl.PluralRules(lang)`

After some research it seems to be an issue with retro-compatibility, as this feature [seems to be supported on Safari from v. 13](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/PluralRules)

Again, the site doesn't load at all, neither in dev nor in production, while with recent browsers everything works fine.
Is there a solution and/or a workaround you can suggest to get our site working again?

Thanks in advance

**Comment by joaovbibiano** [comment]
I`m getting the same error!

Please, can you help us?

![alt text](https://user-images.githubusercontent.com/29175815/107154891-38c94b80-696d-11eb-8bc8-07a1f0482f14.jpg)

![alt text](https://user-images.githubusercontent.com/29175815/107154893-3bc43c00-696d-11eb-859d-41e078e7ff15.jpg)

**Comment by joaovbibiano** [comment]
> Good morning,
> on Safari on iOS version 12.4 we're having a blocking error that prevents even site loading:
> `TypeError: undefined is not a constructor (evaluating 'new Intl.PluralRules(lang)')`
> 
> The line throwing the error is the following, inside file I18nProvider.js:
> `var pluralRules = new Intl.PluralRules(lang)`
> 
> After some research it seems to be an issue with retro-compatibility, as this feature [seems to be supported on Safari from v. 13](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/PluralRules)
> 
> Again, the site doesn't load at all, neither in dev nor in production, while with recent browsers everything works fine.
> Is there a solution and/or a workaround you can suggest to get our site working again?
> 
> Thanks in advance

I could solve my problem installing on the project this polyfill 

https://github.com/eemeli/intl-pluralrules

Can you test? It solved my problem.

**Comment by CleverUpEng** [comment]
It works with your suggestion! 
Thank you so much!!
