### ISSUE TITLE
Key and not translation shown on first SSR

### ISSUE THREAD

**Issue by darren-charterindex** [vinissimus/next-translate#509]
Hi,

In a functional component upon first render on the server the key is shown and not the translation. Is this by design?

For example:

```
// some.json
{
  example: 'Test'
}

// some.component.js
...
const { t } = useTranslation()
console.log(t('some:example'))
...

// First render = 'some:example'
// Second render = 'Test'
```

This is unfortunate as I'm attempting to use the translated key for params.

**Comment by aralroca** [comment]
No, this is not correct. It looks that you have something wrong configured. Can you share your configuration? @darren-charterindex

**Comment by hobbydevs** [comment]
This issue is probably related to this one #411

**Comment by darren-charterindex** [comment]
The configuration is standard. When I refer to render, to avoid any confusion I'm referring to each time the function is parsed on the server, which tends to be a couple of times at least, so by the time it reaches the client it'll be correct. However I am attempting to use the translated key in a useQuery hook on the server.

Here is the config:

// i18n.json
```
{
  "locales": ["en"],
  "defaultLocale": "en",
  "pages": {
    "*": ["common", "search"]
  }
}
```

// some.component.js
```
function SomeComponent() {
  cont { t } = useTranslation()
  const { data, loading } = useQuery(gql`query someQuery() {}, { value: t('common:some-value') }`)
}
```

**Comment by darren-charterindex** [comment]
@hobbydevs you're right, this only happens in development

**Comment by hobbydevs** [comment]
When a hot reload happens, the `getStaticProps` are not reloaded/recalculated (the method next-translate uses to get the translations).
Then the translate method don't know the new keys/values, which results in keys only being rendered in the view.

**Comment by darren-charterindex** [comment]
This doesn't appear to be limited to hot reloads, with the behaviour described above being evident prior to a hot reload.

**Comment by aralroca** [comment]
It will be useful a reproducible example @darren-charterindex

**Comment by darren-charterindex** [comment]
hi @aralroca, I'm no longer trying to use translated keys with an API and so this is no longer an issue for me.
