### ISSUE TITLE
Add language detection

### ISSUE THREAD

**Issue by BjoernRave** [vinissimus/next-translate#51]
It would be great if the library could detect the language of the user and change accordingly. 

There is this library which could be a good way to achieve that: 

https://github.com/UnlyEd/universal-language-detector

**Comment by aralroca** [comment]
In my opinion, I think that it's better to don't bring this responsibility to the lib, because there are a lot of different cases depending on the project. In our case, for example, we have the same webpage in different domains and only one language per domain.

**Comment by BjoernRave** [comment]
fair enough, I will try to make the above library work like that then. I will post how I did it here, so people looking for that feature can copy it

**Comment by aralroca** [comment]
Perfect! If you pasted here your solution I'm sure it will be useful for a lot of people 😄Thanks!

**Comment by n1kio** [comment]
@BjoernRave Anything new on this?
