### ISSUE TITLE
Change in the order of Hooks called by I18nProvider

### ISSUE THREAD

**Issue by iksent** [vinissimus/next-translate#512]
Hello!

1. I am having this issue:

![Снимок экрана 2021-02-15 в 21 14 14](https://user-images.githubusercontent.com/32956521/107970675-3dc47580-6fd3-11eb-9e6d-8a1d523e0905.png)
This happens after any change inside `_app.tsx`.

2. After every warning I am getting the next error with process fall:

<img width="1352" alt="Снимок экрана 2021-02-15 в 21 16 39" src="https://user-images.githubusercontent.com/32956521/107970660-39985800-6fd3-11eb-887d-3077287ffcc9.png">

**Comment by aralroca** [comment]
Can you give a reproducible example to see if there is something wrong? Thanks

**Comment by aralroca** [comment]
@iksent ping on this. Without a reproducible example is difficult to fix! Thanks 🙏

**Comment by iksent** [comment]
Sorry, my code is private, can't share it.
I don't think, that the problem inside `next-translate`, because I saw this error with another's lib trace log.
I'll reopen it, if I have same problems again, sorry for inconvenience!
