### ISSUE TITLE
Namespaces are not loaded if .babelrc with plugin(s) are used

### ISSUE THREAD

**Issue by srigi** [vinissimus/next-translate#514]
I'm using superjson together with Babel plugin, so I don't need to transform `Date`s loaded from DB in `getServerSideProps()` function:

[package.json]
```json
{
  ...
  "dependencies": {
    "@babel/core": "^7.12.10",
    "babel-plugin-superjson-next": "^0.2.1",
    ...
    "next": "10.0.3",
    "next-translate": "^1.0.2",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "superjson": "~1.6.1",
  },
  ...
}

```

[.babelrc]
```json
{
  "presets": ["next/babel"],
  "plugins": ["superjson-next"]
}

```

With this setup the `useTranslate()` hook cannot find translation namespaces:

```
[next-translate] "common:title" is missing in current namespace configuration. Try adding "title" to the namespace "common".
```

I have to opt into usage with the `loader:false` option. Can this be solved in more pragmatic way?

**Comment by aralroca** [comment]
@srigi can you confirm if it works for you on **1.0.5-canary.2**?

**Comment by srigi** [comment]
@aralroca It is fixed! But with one caveat - I have to update Next.js too. I have to use 10.0.3 specifically because newer versions fail to build in Azure app-service deployment.

Anyway, I believe, that this issues is resolved (with Next.js 10.0.7) and can be closed.
