### ISSUE TITLE
Support more glob patterns for namespaces

### ISSUE THREAD

**Issue by BjoernRave** [vinissimus/next-translate#52]
It would be great if I could define my namespaces with patterns like the following:

```
{
    "*/new": ["forms"],
    "*/[id]/edit": ["forms"]
}
```

**Comment by aralroca** [comment]
I thought about this 🙂Ok, let's do it!

**Comment by BjoernRave** [comment]
@aralroca when you see my config you will know why :D

**Comment by aralroca** [comment]
@BjoernRave what do you think if instead of glob patterns, we will support regExp when it exist the prefix `rgx:`?

Ex:

```js
{
 'rgx:^.*/test/.*/example$': ['namespace']
}
```
In this case, we can provide more flexibility without bringing extra code. The problem of Glob is that we need to do all the conversions or use an external library. In static websites is not a problem because this code is only for the CLI, but in the case of `appWithI18n` is going to increase the size of that package.

**Comment by BjoernRave** [comment]
@aralroca not sure. I myself am not super fluent with regexes, same for many people I think. 

Glob patterns seem to be like a standard for this kind of configuration.

Also can you maybe make a release of the `/api` feature :)

**Comment by Hanzo93** [comment]
I like the idea of regex support, since its native in javascript it would keep the library tiny

**Comment by aralroca** [comment]
Ok @BjoernRave @Hanzo93 . Let's do a list of pros and cons:

|  Pros/Cons                |  Globbing                                                                                                                                                                                                                                                                                                                                                                                                                                                               |    Regex                   |
| ----------------------- | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------- | 
| **Versatility**      |       👎Good enough, but regex is much richer.                                                                                                                                                                                                                                                                                               | 👍 You can do far more complicated things with regular expressions.                                                                   |
|  **Lib size**         | 👎Requires to implement a glob to regex conversor or to import an external lib... So is adding extra `kb` to the bundle size.                                                                                                                                                                                                                                                                                                                                                                                                                  | 👍Is native in JavaScript, so is possible to implement without writing so much code.   |
|  **Maintenance**         | 👎  We will need to maintain that extra code of Glob to Regex conversor.                                                                                                                                                                                                                                                                                                                                                                                                               | 👍TC39 is mantaining the RegExp for us.   |
|  **Easy to use**         | 👍Easy to learn and remember, is very simple.                                                                                                                                                                                                                                                                                                                                                                                                               | 👎Hard to learn and sometimes can be frustrating.   |
|  **Performance**         | 👎 Similar performance than regex but with an additional step to convert Glob to Regex.                                                                                                                                                                                                                                                                                                                                                                                                                | 👍Very similar to glob, but without the additional step.   |

Do you want to add any points to the list? 

I researched and there are a lot of libraries, like `webpack`, `jest`, `babel` that are using regex in their configurations.

**Comment by BjoernRave** [comment]
@aralroca thanks for that comparison. I guess looking at it, Regexes make more sense. It's fine by me if you guys prefer it. Will be a way to improve my Regex game :D

**Comment by aralroca** [comment]
@BjoernRave can you confirm that with the new `0.9.0` release is working well in your project?

Your example:

```json
{
    "*/new": ["forms"],
    "*/[id]/edit": ["forms"]
}
```

Should be:

```json
{
    "rgx:/new$": ["forms"],
    "rgx:/\\[id\\]/edit$": ["forms"]
}
```

or with both rules:

```json
{
    "rgx:(/new|/\\[id\\]/edit)$": ["forms"],
}
```

**Comment by BjoernRave** [comment]
Maybe it's the regex, but I tried it with this:

```
{
  "allLanguages": ["en", "pt", "es"],
  "defaultLanguage": "es",
  "currentPagesDir": "pages_",
  "finalPagesDir": "pages",
  "localesPath": "public/locales",
  "pages": {
    "*": ["common"],
    "/": ["forms", "account"],
    "rgx:/new$": ["forms"],
    "rgx:/\\[id\\]/edit$": ["forms"],
    "/logout": ["forms", "account"],
    "/inventory": ["table"],
    "/movements/import": ["forms", "table"],
    "/movements": ["table"],
    "/partners/import": ["forms", "table"],
    "/partners": ["table"],
    "/products": ["table"],
    "/transportagencies": ["table"],
    "/users": ["table"],
    "/warehouses": ["table"]
  }
}

```

and it didn't work.

**Comment by BjoernRave** [comment]
@aralroca when I install `latest` I only get `0.8.0`

**Comment by aralroca** [comment]
@BjoernRave you are right, I forgot to publish to npm, now is ready https://www.npmjs.com/package/next-translate?activeTab=versions

**Comment by BjoernRave** [comment]
@aralroca can confirm, that it works, good job :)
