### ISSUE TITLE
[Bug] setLanguage have no TypeScript declaration

### ISSUE THREAD

**Issue by Divlo** [vinissimus/next-translate#522]
Hey :wave:, 

I'm glad that the `setLanguage` feature has been released, however when I upgraded to `next-translate@1.0.3`, I've got this error when I'm importing `setLanguage` :

```ts
import setLanguage from 'next-translate/setLanguage
```

`Could not find a declaration file for module 'next-translate/setLanguage'.`

I know I am the guy who introduce this bug but I don't know how to fix it, could be cool, if we can fix it for the release `1.0.4`. :smile: 

**EDIT**: I found a way to fix, hopefully, it is working now!
See #524

**Comment by aralroca** [comment]
@Divlo feel free to PR
