### ISSUE TITLE
Intl.Pluralrules not supported in iOS 12.4 and lower

### ISSUE THREAD

**Issue by RobinSCU** [vinissimus/next-translate#525]
Hi,

it seems that iOS 12.4 doesn't Support Intl.Pluralrules (https://caniuse.com/intl-pluralrules) what you are using in the https://github.com/vinissimus/next-translate/blob/master/src/getT.tsx

Because of this we get a infinte loop of this error:
![image](https://user-images.githubusercontent.com/50205066/109028206-dc329400-76c1-11eb-8be9-6e07a397cae1.png)

I'm not sure if you want to polyfill this or it is jsut not supported by this project.

The iPhone 5S was the last the device that is currently on iOS 12.4 (https://support.apple.com/de-de/guide/iphone/iphe3fa5df43/ios)

**Comment by aralroca** [comment]
@RobinSCU hope it helps: https://github.com/vinissimus/next-translate/issues/508#issuecomment-778663166

**Comment by RobinSCU** [comment]
Ahh searching was to easy... thansk!
