### ISSUE TITLE
Translate return type missing Object

### ISSUE THREAD

**Issue by sebascomeau** [vinissimus/next-translate#531]
I'm trying to use the option returnObjects = true but the return type is only string and Typescript complains.

https://github.com/vinissimus/next-translate/blob/8c0bd3a65a97fcdcba77b83b1f7c26c7dc28026e/src/index.tsx#L9

I think you should add string | object... In my case the returned object is an array.

Maybe you have a suggestion on how to make it works.

**Comment by sebascomeau** [comment]
common.json
```json
{
    "links": [
        { "text": "Social media", "href": "https://example.com/social.html" },
        { "text": "Mobile applications", "href": "https://example.com/mobile.html" }
    ]
}
```

index.tsx
```javascript
{t<[{ text: string; href: string }]>('common:links', {}, { returnObjects: true }).map(({ text, href }) => (
    <li key={text}>
        <a href={href}>{text}</a>
    </li>
))}
```

**Comment by aralroca** [comment]
Is this happening in `1.0.4`? Feel free to PR to fix it

**Comment by sebascomeau** [comment]
Im using version 1.0.4

```
"next-translate": "^1.0.4",
```

**Comment by aralroca** [comment]
duplicated of https://github.com/vinissimus/next-translate/issues/521
