### ISSUE TITLE
Feature request : Access namespaces from useTranslation

### ISSUE THREAD

**Issue by slevy85** [vinissimus/next-translate#532]
Hi thank you for this great library !

I am trying to access the namespaces from a component and I didn't find a straightforward way, is it possible to be able to do this ?
```
const { t, ns } = useTranslation()
```
I see that the namespaces are in `InternalContext` so I don't want to use it.

Thank you very much.

**Comment by aralroca** [comment]
I'm curious, why do you want to access the namespace? 😕  remember that the translations are dynamic, so you will not have all the interpolations calculated.

Did you consider using the nested translations feature with the `returnObjects`? 

https://github.com/vinissimus/next-translate#7-nested-translations

**Comment by slevy85** [comment]
Thank you very much, I didn't know about `returnObjects` and i think that this answer my need so i can close this issue.

For information my use case is that I have a legacy application that I am migrating to next.js, the server-side translations are made by next-translate, but the client-side translations use another package, and I need to give to this package access to the namespaces via `window`.
Because it is a legacy application I can't modify the client-side code, I use next.js only to generate the html and i use `unstable_runtimeJS: false` in the pages which tells next.js to not ship any js with the pages.

**Comment by aralroca** [comment]
The SSR namespaces are currently avalaible on `window.__NEXT_DATA__.props.namespaces` 😊
