### ISSUE TITLE
can't access properties set on NextPage

### ISSUE THREAD

**Issue by electather** [vinissimus/next-translate#536]
hi, 
in my project I pass data from page to _app to pass layout and page access level by attaching them as properties to page component

```ts
ReceiptPage.routeAccessType = "authenticated";

ReceiptPage.getLayout = page => (
    <Box w={[" full", "md", "lg", "2xl"]} mx="auto" className="content">
        {page}
    </Box>
);
```
and access them in _app using:

```ts
    const getLayout = Component.getLayout || ((page: any) => page);
```

everything works fine with this design until v1.0.1, after that it seems like there was a breaking change that wraps my pages and i can't access my properties anymore.
is there any way I can fix this issue?

**Comment by aralroca** [comment]
@electather Maybe this can help you: https://github.com/vinissimus/next-translate/blob/master/docs/hoist-non-react-statics.md

**Comment by electather** [comment]
@aralroca thanks for the fast response, i'll check it out RN

**Comment by aralroca** [comment]
Perfect @electather!  I close the issue then 😊  other problems/suggestions feel free to report

**Comment by 5alidz** [comment]
having the same issue and `hoist-non-react-statics` is not working.
the file is located in: `/users/search/index.tsx` and the component has `getInitialProps` and `getLayout`

the error:

`ReferenceError: UserSearch is not defined`

```
> UserSearch.getLayout = getLayout
 __Page_Next_Translate__.getInitialProps = async (ctx: NextPageContext) => {
 // is it a handler? is it a contact
 // parse the `q` key on ctx.query to figure out if it's a handler or contact
```
