### ISSUE TITLE
Query string undefined when changing language

### ISSUE THREAD

**Issue by mateus-schultz** [vinissimus/next-translate#537]
I'm having a problem when changing language in a page where there's a query string.
version: "next-translate": "^1.0.2"

first page
```
http://localhost:3000/users?test=true

const router = useRouter();
console.log(router.query.test) // true
```
when I change language...
```
http://localhost:3000/en-US/users?test=true

const router = useRouter();
console.log(router.query.test) // undefined
```

Maybe I'm missing some configuration here.

**Comment by aralroca** [comment]
How are you changing the language @mateus-schultz  ? with `setLanguage('en')` ?

**Comment by mateus-schultz** [comment]
@aralroca, I have a topbar dropdown thingy that calls a function
```
function changeLanguage(locale) {
    router.push(router.pathname, router.asPath, {
      locale,
    });
  }
```
then I call it like
```
onClick={() => changeLanguage('en-US')}
```

**Comment by mateus-schultz** [comment]
changing from
```
router.push(router.pathname, router.asPath, {
      locale,
});
```
to
```
router.push(router.asPath, router.asPath, {
      locale,
});
```
solved my problem

**Comment by aralroca** [comment]
Cool @mateus-schultz. Anyway, if there are bugs in the navigation with locale, you should report them in Next.js repo, not here, since all the i18n routing used in Next-translate is implemented in Next.js core. The only different thing Next-translate does is to download the necessary translations so that they can be consumed on each page.

**Comment by iksent** [comment]
Faced exactly the same problem.
@mateus-schultz, did you find any solution? Updating Next didn't help.
