### ISSUE TITLE
_one plural form doesn't seem to work

### ISSUE THREAD

**Issue by justincy** [vinissimus/next-translate#540]
1. The [docs](https://github.com/vinissimus/next-translate#5-plurals) say that `_one` should work, especially in English:
    > English has only two: `_one` and `_other`
2. However, [the code](https://github.com/vinissimus/next-translate/blob/08faabe9e03bcde58bf10bdc1109e8a0e766c131/src/transCore.tsx#L119) doesn't allow `count=1` to use the plural form `_one` because of the `> 1` check.
3. Tests expect either a [non-suffixed key `withsingular`](https://github.com/vinissimus/next-translate/blob/08faabe9e03bcde58bf10bdc1109e8a0e766c131/__tests__/useTranslation.test.js#L296) or a [number key `withsingular_1`](https://github.com/vinissimus/next-translate/blob/08faabe9e03bcde58bf10bdc1109e8a0e766c131/__tests__/useTranslation.test.js#L332). So the tests aren't even testing `_one`.

**Comment by aralroca** [comment]
@justincy I prereleased the fix under `1.0.5-canary.3`
