### ISSUE TITLE
Invalid hook call error when using withTranslation in class component

### ISSUE THREAD

**Issue by richardhsueh** [vinissimus/next-translate#547]
```js
class PageTitle extends React.Component {
  render() {
    const { t } = this.props;
    return (
      <div>
        {t(pageTitle)}
      </div>
    );
  }
}

PageTitle.propTypes = {};

export default withTranslation('common')(PageTitle);
```

![Screenshot 2021-03-12 at 12 14 48 PM](https://user-images.githubusercontent.com/33024986/110891340-c31a1c00-832c-11eb-97c8-f8ea67803b40.png)

Somehow when i try to use `withTranslation` in a class component, it will throw a hooks related error 

My package version
"next": "10.0.6"
"next-translate": "^1.0.2"

**Comment by RandomDude123** [comment]
@richardhsueh according to the documentation (1.0.2) it should look like this:

```
class PageTitle extends React.Component {
  render() {
    const { t } = this.props.i18n;
    return (
      <div>
        {t('pageTitle')}
      </div>
    );
  }
}

PageTitle.propTypes = {};

export default withTranslation(PageTitle, 'common');
```

Does this fix your issue?

**Comment by richardhsueh** [comment]
@RandomDude123 I have tried your suggestion, but the error still appear. 
I guess that is because inside the `withTranslation`, they are actually using `useTranslation` 

![Screenshot 2021-03-16 at 5 42 00 PM](https://user-images.githubusercontent.com/33024986/111288216-f0ddc880-867e-11eb-9e26-0bdb4c0fffa8.png)

**Comment by RandomDude123** [comment]
No that should be fine. You can't use hooks inside class components but [you can mix classes and function components with hooks in a single tree](https://reactjs.org/docs/hooks-faq.html#should-i-use-hooks-classes-or-a-mix-of-both). Can you show me the whole file so i can reproduce the error.

**Comment by RandomDude123** [comment]
this code still includes the bugs i mentioned above!

`export default withTranslation("common")(PageTitle);` -> `export default withTranslation(PageTitle, "common");`
`{t(pageTitle)}` -> `{t('pageTitle')}`

Does this change anything? Where do you use this PageTitle component?

**Comment by richardhsueh** [comment]
Oh, my bad. I missed that part.😓
The error is gone now. I guess I am too used to `react-i18next`'s API 😅

**Comment by RandomDude123** [comment]
np. consider using TS as well as move away from class components :)

**Comment by richardhsueh** [comment]
Sure，thanks for the help 👍
