### ISSUE TITLE
Intl.PluralRules not available everywhere

### ISSUE THREAD

**Issue by BjoernRave** [vinissimus/next-translate#551]
On Sentry I got the error:

```
undefined is not a constructor (evaluating 'new Intl.PluralRules(g)')
```

for a Mobile Safari Browser.

Seems like that API is not available in every browser

**Comment by aralroca** [comment]
@BjoernRave maybe this helps you: https://github.com/vinissimus/next-translate/issues/508#issuecomment-778663166

**Comment by BjoernRave** [comment]
ah yeah, I should've searched properly before. Thanks alot. Do you think this should be included into `next-translate` or at least have a place in the Readme?

**Comment by aralroca** [comment]
@BjoernRave It would be great if it were documented in the README. We don't want to add polyfill directly in the library, but better to document it in the README.
