### ISSUE TITLE
Set another defaultLocale ?

### ISSUE THREAD

**Issue by joeleduardo** [vinissimus/next-translate#555]
is possible set another `"defaultLocale`? im looking to get Spanish as default

**Comment by aralroca** [comment]
@joeleduardo I don't understand when you say "another"...  Is the `defaultLocale` not working for you?

**Comment by joeleduardo** [comment]
Well if I set up `defaultLocal: “es”` always load as default `en`

**Comment by aralroca** [comment]
I guess it's in english because is detecting the language of your browser. You can set `localeDetection: false`

https://nextjs.org/docs/advanced-features/i18n-routing#disabling-automatic-locale-detection

**Comment by joeleduardo** [comment]
@aralroca works!!! thanks

**Comment by aralroca** [comment]
Perfect @joeleduardo!  I close the issue then 😊  other problems/suggestions feel free to report
