### ISSUE TITLE
next-translate/lib/esm/plugin - Module not found: Error: Can't resolve 'fs' 

### ISSUE THREAD

**Issue by guicsou-lw** [vinissimus/next-translate#561]
I just want to share a simple code fix that to an error that haunted me for ours:

I've migrated from **i18next** to **next-translate** recently and applied the package `next-translate/useTranslation` basically everywhere.

Everything was fine running locally, but when I was deploying the code to Vercel and/or building the application, I started to see the following error:
`ModuleNotFoundError: Module not found: Error: Can't resolve 'fs' in 'pathtomycode/node_modules/next-translate/lib/esm/plugin'`

I literally spent hours trying to solve this issue and searching, but the fix, in fact, was very obvious and simple.
In one (of many) pages I imported the useTranslation wrong and was trying to import lilke this:
`import useTranslation from 'next-translate';`

With this, my code was trying to import 'fs' out of StaticProps and that's why the error was being raised.

I am used to do imports as below (maybe that's what confused to me) but this doesn't work for next-translate package (would be a nice addition, tho):
`import { useTranslation } from 'next-translate';`

**Comment by aralroca** [comment]
We recommend using `import useTranslation from 'next-translate/useTranslation'`, this way there aren't tree-shaking issues with Webpack.
