### ISSUE TITLE
TypeError: Cannot read property 'loadLocaleFrom' of undefined

### ISSUE THREAD

**Issue by guydumais** [vinissimus/next-translate#577]
My API code is working well on LOCALHOST but failing once deployed on VERCEL with this error message:
```
TypeError: Cannot read property 'loadLocaleFrom' of undefined
    at /var/task/node_modules/next-translate/lib/cjs/getT.js:60:37
    at step (/var/task/node_modules/next-translate/lib/cjs/getT.js:33:23)
    at Object.next (/var/task/node_modules/next-translate/lib/cjs/getT.js:14:53)
    at /var/task/node_modules/next-translate/lib/cjs/getT.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/var/task/node_modules/next-translate/lib/cjs/getT.js:4:12)
    at getT (/var/task/node_modules/next-translate/lib/cjs/getT.js:48:12)
```

Line 55 to 60 in getT.js:
```
55: config = getConfig_1.default();
.
.
.
.
60: loader = config.loadLocaleFrom || defaultLoader;
```

getConfig_1 is defined at line 42:
```
var getConfig_1 = __importDefault(require("./getConfig"));
```

Here's the getConfig.js file content:
```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
function getConfig() {
    var g = typeof window === 'undefined' ? global : window;
    return g.i18nConfig;
}
exports.default = getConfig;
```

Because the api function is run from the server-side, I guess the **var g** is assigned the value global which is a **NodeJS.Global** object type of **globalThis**.

Here's a code snippet from the js file calling the getT function:
```
import getT from 'next-translate/getT'
.
.
.
export async function sendEmail({ name, email, message, locale }) {
const t = await getT(locale, 'contact')
.
.
.
```

Again, everything is working fine on localhost but once deployed on VERCEL hosting it doesn't seems to find the i18n config file defined at line 60 in getT.js. Is this a bug in next-translate or a bad usage of getT?

Any clue would be welcome.

Thanks in advance.

**Comment by aralroca** [comment]
I think is related with this issue https://github.com/vinissimus/next-translate/issues/484

**Comment by aralroca** [comment]
I close it since it is duplicated
