### ISSUE TITLE
Rediect '/' to exist i18n subpath like '/pt'

### ISSUE THREAD

**Issue by luotongzhou** [vinissimus/next-translate#578]
When I visit some path like 'xxx.com/a', my default language is PT,  but my 'accept-language' header is 'en', I want my page can redirect to 'xxx.com/en/a' autolly, what should I do? 
```
locales: ['en', 'pt', 'es'],
  defaultLocale: 'pt',
 ```
 when i visit a path, if the url dosen't contain a subpath and  the 'accept-language' header  is one of `locales` in `i18n.js`,  the page can redirect to the url that contain subpath

**Comment by aralroca** [comment]
You can disable the automatic locale detection. More info: https://nextjs.org/docs/advanced-features/i18n-routing#disabling-automatic-locale-detection
