### ISSUE TITLE
[Question] Can you also use this for non static nextjs pages

### ISSUE THREAD

**Issue by WardVH** [vinissimus/next-translate#58]
Hi there,

I'm looking to replace our current translations setup with this package but I was wondering if you can use this without the static generation of the pages.

Can we also enhance the middleware to determine the language based upon a header that the server receives? In our current setup, we have subdomains for each locale, so there is no need for the `/en`, `/fr`, `/it` approach... Every subdomain has its hard-coded locale header that get's send with every request to the express server.

Looking forward to your insights and keep up the good work! 

Kind regards,
Ward

**Comment by aralroca** [comment]
Yes, it's possible. However, you need to implement your own language detector middleware.

Right now, the provided middleware on this lib is based on `/lang` on the url:

* https://github.com/vinissimus/next-translate/blob/master/src/i18nMiddleware.js

If you implement your own middleware to detect the language, the only thing is to return the `lang` as query param:

```js
function myCustomI18nMiddleware(){
  return (req, res, next) => {
    req.query = {
       ...req.query, 
       lang: myCustomLangDetector(req)
     }
    next()
  }
}
```

And then the [appWithI18n](https://github.com/vinissimus/next-translate#appwithi18n) is going to look at `req.query.lang` and it's going to download the necessary dictionaries and provide the necessary things to be consumed.

**Comment by aralroca** [comment]
@WardVH I hope that your question is answered now. I'm going to close the issue. If you have more doubts, do not hesitate to ask!
