### ISSUE TITLE
DefaultLocale in other language instead en

### ISSUE THREAD

**Issue by ferranpuigmar** [vinissimus/next-translate#586]
I want to do that my site will be loading by default in spanish, but if I change my defaultLocale to es, always load the page with /en, instead /

Is it a bug or a mistake of mine?

i18n.json
---------
{
  "locales": ["es", "en"],
  "defaultLocale": "es",
  "pages": {
    "*": ["common"]
  }
}

next.config.js
--------------
const nextTranslate = require('next-translate')

module.exports = nextTranslate({
  webpack: (config, { isServer, webpack }) => {
    return config
  },
  env: {
    BASE_URL: process.env.BASE_URL,
    API_URL: process.env.API_URL,
    API_KEY: process.env.API_KEY,
  },
  async rewrites() {
    return [
      {
        source: '/',
        destination: `/mainLanding`,
      },
      {
        source: '/:brand',
        destination: `/brandProduct/:brand`,
      },
    ]
  },
})

**Comment by aralroca** [comment]
@ferranpuigmar By default, it uses the browser language, in case your browser does not have a language supported by your app, as fallback it uses the defaultLanguage. You can disable the automatic detection with `localeDetection: false`. More info: https://nextjs.org/docs/advanced-features/i18n-routing#disabling-automatic-locale-detection

**Comment by ferranpuigmar** [comment]
Thanks!

**Comment by aralroca** [comment]
@ferranpuigmar I close the issue, if you have more questions feel free to report it! thanks!
