### ISSUE TITLE
graphql

### ISSUE THREAD

**Issue by andresantiagohellmann** [vinissimus/next-translate#595]
First of all I would like to thank you for the resource!
I would like to know if it would be possible to get help to know the best way to do this integration using GRAPHQL. Thank you very much in advance.

**Comment by martinmunillas** [comment]
I don't think there is anything special with the graphql integration, unless i'm understanding wrong your question... do you have like a more specific question? or any error you're having? as far as i know both graphql and next-translate shouldn't have a problem together.

So if i would tell you to just use graphql as the documentation says, and use next-translate as the documentation says, and i don't see why you should have any problem

**Comment by camodigital** [comment]
Thank you very much for your feedback. Sorry I haven't been clear enough. I was just wondering if there is "the best way" to do this. But I did the implementation using loadLocaleFrom importing the JS.

**Comment by andresantiagohellmann** [comment]
Thank you very much for your feedback. Sorry I haven't been clear enough. I was just wondering if there is "the best way" to do this. But I did the implementation using loadLocaleFrom importing the JS.
