### ISSUE TITLE
Translations in shared layouts don't work in 1.0.6, while they work in 1.0.5

### ISSUE THREAD

**Issue by srflp** [vinissimus/next-translate#604]
It seems like 1.0.6 introduces some breaking changes, because some of strings in my app just stopped being translated.

This regression applies only to the translations that are in a shared layout (shared via `_app.js`).

I prepared a reproduction repo: https://github.com/srflp/next-translate-bug

How does it behave?
- 1.0.5:
![b3a0a9f7d528f9e5ec9e2daa6a56b9a9](https://user-images.githubusercontent.com/17103865/116722231-6fe45180-a9de-11eb-8ac7-1ee802eecc38.gif)

- 1.0.6 (useTranslation in a shared layout stopped working): 
![3e5fc69963bce682f2a277764ea16db0](https://user-images.githubusercontent.com/17103865/116721840-0a906080-a9de-11eb-8381-0ea60a609153.gif)

**Comment by aralroca** [comment]
@srflp I guess is introduced by https://github.com/vinissimus/next-translate/pull/574, can you confirm if `1.0.6-canary.2` works for you and `1.0.6-canary.3` no?  I think we can revert the PR, because it also does not solve the problem it was trying to solve. Thanks!

**Comment by aralroca** [comment]
@srflp it should work again on [1.0.7-canary.3](https://github.com/vinissimus/next-translate/releases/tag/1.0.7-canary.3) 👍

**Comment by srflp** [comment]
Awesome, it works again, thanks! 😊
