### ISSUE TITLE
defaultLocale not working

### ISSUE THREAD

**Issue by quarterpound** [vinissimus/next-translate#607]
Hello everybody. Im doing a small project for a client. Im using next-translate for internationalization.

My i18n.json file is as follows:

```
{
  "locales": ["az", "en", "ru"],
  "defaultLocale": "az",
  "pages": {
    "*": ["common"],
    "/contact": ["contact"],
    "/": ["renovation"]
  }
}
```

Even though I am specifiying a default locale. When i open the website I still get the english version of the website. How can I fix this?

**Comment by aralroca** [comment]
Is working. But the order is:

NEXT_LOCALE locale saved in a cookie -> browser language (if is one of the locales list) -> defaultLocale as fallback

You can disable the automatic browser language detection with `localeDetection: false` on the `i18n.js` file. More info:

https://nextjs.org/docs/advanced-features/i18n-routing

**Comment by aralroca** [comment]
I close the issue, if what I have said does not solve it, you will comment it and we will reopen it, but I think that is it.

**Comment by quarterpound** [comment]
Thank you it solved my problem
