### ISSUE TITLE
how to import in next.config

### ISSUE THREAD

**Issue by kotsh23** [vinissimus/next-translate#613]
i have this in my next.config.js

`const nextTranslate = require("next-translate");

module.exports = {
  images: {
    domains: ["cdn.ztona.org"],
  },
  serverRuntimeConfig: {
    mySecret: "secret",
    xauth: process.env.XAUTH,
    url: process.env.URL,
  },
  publicRuntimeConfig: {
    // Will be available on both server and client
    staticFolder: "/static",
    xauth: process.env.XAUTH,
    url: process.env.URL,
    siteName: process.env.SITE_NAME,
  },
};`

how i can import with nextTranslate() plugin please

**Comment by aralroca** [comment]
This should work

```js
const nextTranslate = require("next-translate");

module.exports = nextTranslate({
  images: {
    domains: ["cdn.ztona.org"],
  },
  serverRuntimeConfig: {
    mySecret: "secret",
    xauth: process.env.XAUTH,
    url: process.env.URL,
  },
  publicRuntimeConfig: {
    // Will be available on both server and client
    staticFolder: "/static",
    xauth: process.env.XAUTH,
    url: process.env.URL,
    siteName: process.env.SITE_NAME,
  },
});
```

**Comment by aralroca** [comment]
@kotsh23 I close the issue, if you are still having problems or have other questions please do not hesitate to ask

**Comment by kotsh23** [comment]
thank you for your help @aralroca 

but when i do it i get this error

Loaded env from /Users/kotsh/Desktop/codes/shopping-site/.env.local
Error: Cannot find module '/Users/kotsh/Desktop/codes/shopping-site/i18n'
Require stack:
- /Users/kotsh/Desktop/codes/shopping-site/node_modules/next-translate/lib/cjs/plugin/index.js
- /Users/kotsh/Desktop/codes/shopping-site/node_modules/next-translate/lib/cjs/index.js
- /Users/kotsh/Desktop/codes/shopping-site/next.config.js
- /Users/kotsh/Desktop/codes/shopping-site/node_modules/next/dist/next-server/server/config.js
- /Users/kotsh/Desktop/codes/shopping-site/node_modules/next/dist/next-server/server/next-server.js
- /Users/kotsh/Desktop/codes/shopping-site/node_modules/next/dist/server/next.js
- /Users/kotsh/Desktop/codes/shopping-site/node_modules/next/dist/server/lib/start-server.js
- /Users/kotsh/Desktop/codes/shopping-site/node_modules/next/dist/cli/next-dev.js
- /Users/kotsh/Desktop/codes/shopping-site/node_modules/next/dist/bin/next
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at nextTranslate (/Users/kotsh/Desktop/codes/shopping-site/node_modules/next-translate/lib/cjs/plugin/index.js:34:14)
    at Object.<anonymous> (/Users/kotsh/Desktop/codes/shopping-site/next.config.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/kotsh/Desktop/codes/shopping-site/node_modules/next-translate/lib/cjs/plugin/index.js',
    '/Users/kotsh/Desktop/codes/shopping-site/node_modules/next-translate/lib/cjs/index.js',
    '/Users/kotsh/Desktop/codes/shopping-site/next.config.js',
    '/Users/kotsh/Desktop/codes/shopping-site/node_modules/next/dist/next-server/server/config.js',
    '/Users/kotsh/Desktop/codes/shopping-site/node_modules/next/dist/next-server/server/next-server.js',
    '/Users/kotsh/Desktop/codes/shopping-site/node_modules/next/dist/server/next.js',
    '/Users/kotsh/Desktop/codes/shopping-site/node_modules/next/dist/server/lib/start-server.js',
    '/Users/kotsh/Desktop/codes/shopping-site/node_modules/next/dist/cli/next-dev.js',
    '/Users/kotsh/Desktop/codes/shopping-site/node_modules/next/dist/bin/next'
  ]
}
npm ERR! code 1
npm ERR! path /Users/kotsh/Desktop/codes/shopping-site
npm ERR! command failed
npm ERR! command sh -c next dev

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kotsh/.npm/_logs/2021-05-20T21_25_50_481Z-debug.log
kotsh@MacBook-Air-Ahmed shopping-site %

**Comment by aralroca** [comment]
You need to create the file `i18n.js` in the root of the project with the next-translate configuration 😉

**Comment by kotsh23** [comment]
@aralroca Thank you bro worked fine but i have another problem :D

now i have inside pages/[category]/index.js and [single].jsx

if i switch lang to another i have new name space localhost:3000/ar 

and i use router.query to fetch category name now system read "ar" as category , (router.query.category)

any hint how to fix it , i dont need to add name space at url or any idea about how to handle it 👯
