### ISSUE TITLE
well done! so sad that I didn't find out her before

### ISSUE THREAD

**Issue by Meeken1998** [vinissimus/next-translate#62]
I realized the translation module by myself in [my blog](https://github.com/Meeken1998/maotang) (based on nextjs), and then I saw yr module today TAT

**Comment by aralroca** [comment]
Hey @Meeken1998 thank you. Maybe if our API fits with your goals, you can migrate to our lib. Our solution is thought to be performant and also to work without the need of a server (also possible with a server). Just consider It! I'm sure you can improve your PageSpeed Insights score with this change.
