### ISSUE TITLE
Namespace for /_error page

### ISSUE THREAD

**Issue by vadymshymko** [vinissimus/next-translate#620]
Common namespaces (*: [....]) are not added to the custom error page (_error.(ts|js)). Also, creating a separate namespace  for '/_error' is not possible.

next.js v10.2.2
next-translate v1.0.7

**Comment by vadymshymko** [comment]
> Common namespaces (*: [....]) are not added to the custom error page (_error.(ts|js)). Also, creating a separate namespace for '/_error' is not possible.
> 
> next.js v10.2.2
> next-translate v1.0.7

@aralroca Hi! maybe you can help me with this problem?

**Comment by aralroca** [comment]
@vadymshymko I tried and it works well:

![image](https://user-images.githubusercontent.com/13313058/132222085-422d86b6-cdfa-4a0d-8ce7-c9d45aaaa13f.png)

Would you create a repo with the error to see what could be wrong? Thanks.

**Comment by vadymshymko** [comment]
> @vadymshymko I tried and it works well:
> 
> ![image](https://user-images.githubusercontent.com/13313058/132222085-422d86b6-cdfa-4a0d-8ce7-c9d45aaaa13f.png)
> 
> Would you create a repo with the error to see what could be wrong? Thanks.

Oh sure. I will create and add a link to it here
