### ISSUE TITLE
translations not working in vercel

### ISSUE THREAD

**Issue by xerenahmed** [vinissimus/next-translate#623]
when i do `next build && next start` in my local it works but not in vercel

<img width="732" alt="Screen Shot 2021-05-31 at 09 07 41" src="https://user-images.githubusercontent.com/35738714/120147648-a8e73000-c1ef-11eb-8de7-34159de3d5e0.png">

i18n.js
```js
module.exports = {
  locales: ['en', 'tr'],
  defaultLocale: 'en',
  pages: {
    '*': ['common', 'fields', 'layout'],
  },
  loadLocaleFrom: (lang, ns) =>
    import(`./locales/${ns}/${lang}.json`).then(m => m.default),
};
```

**Comment by aralroca** [comment]
@xerenahmed I need more details. Do you have a reproducible example? I personally have several Vercel projects using Next-translate and I have no problem.

**Comment by xerenahmed** [comment]
worked now, I guess the reason is cache. Sorry, thanks for your help.
