### ISSUE TITLE
Null locale with useTranslation in custom _document with getInitialProps

### ISSUE THREAD

**Issue by MitchellWestcott** [vinissimus/next-translate#624]
I've seen previous users find methods of using documentLang which is now deprecated. Is there a current solution for accessing locale using next-translate in custom Head elements?

Sorry if formatting is an issue on this one it's my first issue. If anyone needs further clarification I can run through my process / create repeatable steps. The issue is I'm using styled-components which forces me to use getIinitialProps ¯\_(ツ)_/¯

**Comment by aralroca** [comment]
`documentLang` is deprecated because Next.js handles automatically the `<Html lang />` attribute.

if you need the locale, maybe as a workaround you can retrieve it from `__NEXT_DATA__`.

```js
const props = this.props.__NEXT_DATA__.props
const locale = props.pageProps.__lang || props.__lang
```

This `__lang` property is injected by Next-translate.
