### ISSUE TITLE
Locale Sub-routing doesn't work

### ISSUE THREAD

**Issue by ykyp** [vinissimus/next-translate#627]
Hi,

I've got this configuration on my next js with next-translate:

Inside `next.config.js`
```
const nextTranslate = require('next-translate');

module.exports = nextTranslate({
   webpack: (config, { isServer, webpack }) => {
      return config;
   },
   target: 'serverless'
});

```

And inside `i18n.json`
```
{
   "locales": [
      "en",
      "gr"
   ],
   "defaultLocale": "gr",
   "pages": {
      "*": [
         "common"
      ],
      "/": [
         "home"
      ],
      "/about": [
         "about"
      ]
   }
}

```

The problem I'm facing is when switching the locale to `en` all blog posts are broken e.g
http://localhost:3000/blog/test <- Works

http://localhost:3000/en/blog/test <- 404 not found

Any ideas what I should do to make the sub-routing work correctly?

Thanks

**Comment by aralroca** [comment]
Would be great to provide a reproducible repo in order to help you. With the provided info it should work well...

**Comment by alexfrancavilla** [comment]
@aralroca I have seen the same thing happening but only on `pages/[slug].tsx` pages that also provide a `getStaticPaths` function. In my case, the `getStaticPaths` function was extremely simple (reading a list of allowed pages from a config with `fallback: false` to trigger 404 pages for everything else).

As soon as I removed the function, the pages worked again including translations. However you do loose static page generation then, if you don't provide the function.

I'm a bit in a rush to finish a project so I can't provide a full repository to demonstrate right now, maybe I'll come back to this in a few days.

**Comment by ykyp** [comment]
Yeap confirming that's same issue as reported by @alexfrancavilla . In my case removing `getStaticPaths` breaks the application

**Comment by ykyp** [comment]
Here's[ a reproducible repo](https://github.com/ykyp/nextjs-blog-translate) with the issue: 

### Steps to reproduce
- Clone repo and run `npm i` and `npm run dev`
- Click on `Change to English`
- Click on `Markdown Primer 2020-01-02`
- Redirects to 404

### Expected behaviour: 
- Redirect to the same md file without the `/en` inside the URL

**Comment by ykyp** [comment]
@aralroca Any updates on this issue?

**Comment by pix2D** [comment]
Having the same issue. If `getStaticPaths` is present dynamic routes (e.g. `/de/post/[...slug]`) do not work with `fallback: false`. They do work with `fallback: true` but there is a momentary flash of non-translated content (I think this may be #575) however the translations do load in after that.

**Comment by aralroca** [comment]
@ykyp You need to add the locales to the getStaticPaths:

```js
export async function getStaticPaths({ locales }) {
   const paths = getAllPostIds(locales);
   return {
      paths,
      fallback: false,
   };
}
```

and your function:

```js
export function getAllPostIds(locales) {
   const fileNames = fs.readdirSync(postsDirectory);

   return fileNames.flatMap((fileName) => {
      const params = {
         id: fileName.replace(/\.md$/, ""),
      }

      return [
         { params },
         ...locales.map(locale => ({ params, locale })),
      ]
   });
}
```

**Comment by aralroca** [comment]
@ykyp I close the issue, is re

**Comment by ykyp** [comment]
Thanks a lot @aralroca confirming this has now fixed my issue 🙏
