### ISSUE TITLE
Add CLI support for Windows: next-translate syntax incorrect, command failed

### ISSUE THREAD

**Issue by mataslib** [vinissimus/next-translate#63]
# Actual behaviour

Running the command `yarn next-translate` throws errors: "The syntax of the command is incorrect.", "Command failed: mkdir pages/cs"

# Expected behaviour

New localised pages inside `pages/[locale]/` dir.

# Environment

- Win10
- git bash
- next-translate 0.9.0
- node 12.4.0

![image](https://user-images.githubusercontent.com/5154014/76031202-8bb5aa00-5f37-11ea-9473-3c07ace7be22.png)

**Comment by aralroca** [comment]
Hey @matasek, yes, the CLI tool for static pages right now is only compatible in Unix. However, thank you to report it. A good consideration is to also support Windows for the CLI. Let's keep open the issue and I will take a look in a few days.

**Comment by aralroca** [comment]
Hey @mataslib , this fix will be released on `0.14.0`, however, you can try it now in `0.14.0-canary.1`, please, can you confirm that it is working on your computer?

https://github.com/vinissimus/next-translate/releases/tag/0.14.0-canary.1

Thank you a lot 👏

**Comment by mataslib** [comment]
Hello, I've tried it, it's not working properly yet. It now works in git bash (MinGW) 👍, however still does not work in Win cmd/powershell.

PS: I thank you! 

![image](https://user-images.githubusercontent.com/5154014/77827909-a931fa00-7118-11ea-997e-de795f7f2824.png)

**Comment by aralroca** [comment]
In, in that case, I reopen the issue to fix this on 0.14.2

**Comment by heatseeker76** [comment]
I created a PR to fix the last issue. #111 
I tested it on windows. It is working correctly.

**Comment by aralroca** [comment]
@mataslib @heatseeker76 we created a prerelease 0.14.2-canary.2 with this fix! Can you verify that it works? 👏

**Comment by mataslib** [comment]
@aralroca Great news! It works great now. Thanks! 👍

When I was testing it, I've just noticed that modifying files starting with underscore _(document|app).js does not trigger rebuild (in both cmd and bash so it seems to be non-related issue). Is this also happening to you?

**Comment by aralroca** [comment]
> @aralroca Great news! It works great now. Thanks! 👍
> 
> When I was testing it, I've just noticed that modifying files starting with underscore _(document|app).js does not trigger rebuild (in both cmd and bash so it seems to be non-related issue). Is this also happening to you?

Yes. It's a known problem commented on #56, the same thing is happening in `/api` routes. 

Nevertheless, I think that we can fix it now. I'm going to change the milestone of #56 to 0.15.0 in order to prioritize the issue! Thanks to report it!

**Comment by heatseeker76** [comment]
Hi @aralroca 
Sorry I did not follow the PR I initiated. I was too busy at work and could not follow properly.
I installed and tested it and I just deployed the lastest version to prod.

@aralroca  you are exceptional. The fact you took time to explain your change request says a lot about you. 💯 

Thanks a lot !
