### ISSUE TITLE
SerializableError: Error serializing `.__namespaces.intro` returned from `getStaticProps` in "/". Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.

### ISSUE THREAD

**Issue by jahirfiquitiva** [vinissimus/next-translate#633]
Hello

I am getting this error and I don't know how to fix it :/

```gradle
SerializableError: Error serializing `.__namespaces.intro` returned from `getStaticProps` in "/".
Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.
```

Here's my i18n.JSON
```json
{
  "locales": ["en", "es"],
  "defaultLocale": "en",
  "pages": {
    "*": [
      "intro",
      "post",
      "find",
      "support",
      "video",
      "listen"
    ]
  }
}
```

And this is how my locales look like

<img width="180" alt="Shot 2021-06-21 at 13-53-41@2x" src="https://user-images.githubusercontent.com/10360816/122813085-21458c00-d298-11eb-92fb-b685f0af7241.png">

I'm using Next `11.0.0` and next-translate `1.0.7`

**Comment by jahirfiquitiva** [comment]
Same happens with next `10.1.3` and next-translate `1.0.5`

**Comment by aralroca** [comment]
`Error serializing` looks that the content of the `intro.json` is not a correct JSON. If is an empty file it should be an empty object `{}`

**Comment by jahirfiquitiva** [comment]
@aralroca

this is the content of that file:

```json
{
  "travelairs": "Travelairs"
}
```

I think that's a correct json 🤔

**Comment by jahirfiquitiva** [comment]
Just found that it was due to missing files... not all of the files mentioned in `pages` existed, so that's why it failed.

Would be nice if it just ignored missing files instead of breaking the whole site

Thanks anyways
