### ISSUE TITLE
Pluralisation not working using "one" and "other" in some situations - specifically for Welsh

### ISSUE THREAD

**Issue by jgbharris** [vinissimus/next-translate#634]
We experienced an issue where pluralisation was not working on certain pages but did not fail in every case.

Specifically we were using x-hours-duration with the "_one" or "_other" keys and feeding the {{count}} in for "_other".

e.g. 

 "x-hours-duration": {
    "one": "1 hour",
    "other": "{{count}} hours"
  },

We found that for the Welsh language we needed to all keys to be filled out i.e: _one, _two, _few, _many and _other.

We were wondering whether this was by design as we read that: "All other plural forms depends on locale. For example English has only two: _one and _other (1 cat vs. 2 cats). Some languages have more, like Russian and Arabic."

Does this mean that to guard against this issue going forward, we will need to fill out all keys, as certain languages with different pluralisation rules to English cannot realy on just "_one" or "_other"?

Thanks

James

**Comment by aralroca** [comment]
Sorry @jgbharris, this is not an issue, this is how the plurals work. We are following the CLDR Specification. I invite you to read this:

- http://cldr.unicode.org/index/cldr-spec/plural-rules
- https://unicode-org.github.io/cldr-staging/charts/37/supplemental/language_plural_rules.html#sl

**Comment by aralroca** [comment]
exact value is for numbers only. `_1` is exact one, and `_one` is the [plural rule](https://cldr.unicode.org/index/cldr-spec/plural-rules) for one (is different depending the language). It is already explained in the [docs](https://github.com/aralroca/next-translate?tab=readme-ov-file#5-plurals):

<img width="862" alt="Screenshot 2024-01-28 at 01 48 06" src="https://github.com/aralroca/next-translate/assets/13313058/232d54bf-df87-46cd-806f-dc0abc8364c1">

**Comment by luixo** [comment]
@aralroca 
I suggest either change the description in README or add the fallback.
Currently, it's not clear that if I just add `other` - the library will silently fail in rendering the data, waiting for a specific suffix.

It's either a one-line non-breaking solution that will better some folks' DX or a one **bold** line in a readme file.
