### ISSUE TITLE
getInitialProps is not called

### ISSUE THREAD

**Issue by viperin** [vinissimus/next-translate#642]
getInitialProps is not called on my page when I use next-translate.
I missed something on using next-translate configuration ?

**Comment by aralroca** [comment]
@viperin Would you share more information for some context? Naturally, the loader you have (getInitialProps, getServerSideProps, or getStaticProps) should work.

**Comment by viperin** [comment]
@aralroca my bad, it was a problem with using mobx observer on _app.js

**Comment by aralroca** [comment]
@viperin I'm glad you got it fixed. I close the issue then!
