### ISSUE TITLE
How to set default locale when we have different conditions 

### ISSUE THREAD

**Issue by gauravverma029** [vinissimus/next-translate#648]
How to set default locale because I have some conditions first I have to check URL params if in URL params I have lang=en then I have to set  'en' and second case I will check cookie and third case is will check Navigator userAgent.And where we can check all conditions and set language. Which code should i use?

**Comment by aralroca** [comment]
@gauravverma029 You can save a cookie named `NEXT_LOCALE` to save the language of a specific user.

Here there is an example: https://github.com/vinissimus/next-translate#10-how-to-save-the-user-defined-language

I hope it helps you 😊

**Comment by aralroca** [comment]
I close the issue. If you have more questions don't hesitate to ask again
