### ISSUE TITLE
Error testing with jest and react testing library

### ISSUE THREAD

**Issue by AlejandroGutierrezB** [vinissimus/next-translate#649]
Package is working great, however all my test in which a reference DOM element by text are broken as its rendering not translated strings such as "common:nested.child1".
I get I can just change my test to match that string, however I will actually like to write a test that finds that kind of string by regex to make sure we don't ship not translated string because that key is not matching an existing one.

I tried wrapping my render with i18n provider as with any other provider (common practice recommended by official testing library docs) https://testing-library.com/docs/react-testing-library/setup/

```js
const Providers = ({ children }) => {
  return (
      <I18nProvider lang={'en'} namespaces={{ commonEN, homeEN }}>
        {children}
      </I18nProvider>
  );
};
```

Is there any way of making the translations available in tests?
Or any recommendation on what would be a better approach?

**Comment by semajtwin** [comment]
@AlejandroGutierrezB I had the same issue last week until I realised that I was still importing the `render` function from `testing-library` instead of the custom `render` function from `test-utils.js`. The code below is how I managed to set it up:

```javascript
// test-utils.js

import React from 'react'
import { render } from '@testing-library/react'
import I18nProvider from 'next-translate/I18nProvider'

const namespaces = {
   common: {
      search: { placeholder: 'search items' }
   }
}

const AllProviders = ({children}) => {
  return (
    <I18nProvider lang='en' namespaces={namespaces}>
      {children}
    </I18nProvider>
  )
}

const customRender = (ui, options) => render(ui, { wrapper: AllProviders, ...options })

export * from '@testing-library/react'

export { customRender as render }
```

Remember to import from `test-utils` not `testing-library`:

```javascript
// Search.test.js

import React from 'react'
// import { render } from '@testing-library/react'
import { render } from '../test-utils'

import Search from '../../containers/Search/Search'

describe('search', () => {
  test('render search', () => {
    render(
      <Search />
    )

    const searchInput = screen.getByPlaceholderText(/search items/i)
    expect(searchInput).toBeInTheDocument()
  })
})
```

**Comment by aralroca** [comment]
So it seems to happen with the new version of testing-library? I close the issue because it doesn't seem to be a bug of next-translate 😊
