### ISSUE TITLE
different locales, different style and directions

### ISSUE THREAD

**Issue by vahidtakro** [vinissimus/next-translate#653]
Hello, thanks for building this amazing package.
I am a new nextjs learner, so the question may be very basic.

How can I make it possible when user changes locale, the direction (rtl/ltr) changes too? how can I set different style files for each locale?

**Comment by aralroca** [comment]
@vahidtakro The language is in the `html` element.

![image](https://user-images.githubusercontent.com/13313058/130264657-9323ff41-6ced-4bbf-9445-a1f465034b1a.png)

You can directly use `html[lang=es]` in CSS files to make the styles affect only the Spanish language.

However, at any point, you can access the language with the `useTranslate` hook, and create your own classes wherever you want.

If you don't mind I move the issue as a discussion. All questions and answers are best asked there 😊
