### ISSUE TITLE
[Doc] Does the variable-example in the readme need to be updated?

### ISSUE THREAD

**Issue by G11Max** [vinissimus/next-translate#660]
[Create your namespaces files](https://github.com/vinissimus/next-translate#create-your-namespaces-files):
> in the file content section:
```json
{
  "title": "Hello world",
  "variable-example": "Using a variable {{count}}"  // it's not working
}
```

Should the template syntax be updated to ```${}```? for example, ```${count}```

**Comment by aralroca** [comment]
No, is `{{` as default prefix and `}}` as default suffix. You can change it in the [configuration](interpolation) with the `interpolation` entry.
