### ISSUE TITLE
Using translation array with Trans component?

### ISSUE THREAD

**Issue by tvanantwerp** [vinissimus/next-translate#664]
I've got an array of translations, which is easy enough to pull using the `useTranslation` hook with `{ returnObjects: true }`. But these translations also have HTML inside them, and need to be processed by the `<Trans />` component. Since `Trans` takes a single `i18nKey`, I'm not sure how I could take this array and map over it while also processing the strings to HTML with `Trans`.

react-i18next seems to handle it [this way](https://react.i18next.com/latest/trans-component#using-with-lists-v-10-5-0), but I haven't seen any similar function documented here.

**Comment by aralroca** [comment]
@tvanantwerp Trans component doesn't support arrays directly right now, but there is a way to solve it. I hope this help you https://github.com/vinissimus/next-translate/discussions/626

**Comment by tvanantwerp** [comment]
@aralroca This is massively helpful, thank you!
