### ISSUE TITLE
Make pages directory customisable

### ISSUE THREAD

**Issue by sketchbuch** [vinissimus/next-translate#682]
I see in file: "next-translate/lib/cjs/plugin/index.js" that the pages folder is looked for in ./src/pages or ./pages. Is there anyway to change this? It seems hard coded.

My pages are in src/renderer/pages as I'm building an electron app and want main and renderer as subfolders of src.

I'm using next-translate v1.0.7

**Comment by aralroca** [comment]
@sketchbuch this is a restriction of Next.js not from this library: https://nextjs.org/docs/advanced-features/src-directory

**Comment by skyksandr** [comment]
@aralroca this is partially true. You can run `next dev ./my-custom-folder`, and next will look for `pages` and `src/pages` inside `my-custom-folder`.
Today, after adding next-translate to the project it stopped working due to
```
Error: ENOENT: no such file or directory, scandir repo_root/pages
```

**Comment by aralroca** [comment]
@skyksandr Ok thanks, I didn't know this. Is it something new? In this case we should see what environment variable next.js uses to read it.

**Comment by skyksandr** [comment]
It seems it is available for roughly 3 years. I have found it here: https://github.com/vercel/next.js/issues/4789#issuecomment-405594107

I have looked through the next.js codebase and did not find this `dir` to be assigned to some env variable. It starts from here:
https://github.com/vercel/next.js/blob/canary/packages/next/cli/next-dev.ts#L53

**Comment by skyksandr** [comment]
I found a way to make it work by using `NEXT_TRANSLATE_PATH` env variable like
```
NEXT_TRANSLATE_PATH='./frontend' yarn dev
```

however if I put this variable to `.env` plugin seems not be able to access it

**Comment by aralroca** [comment]
I added the  `pagesInDir` configuration property in [1.1.1-canary.2](https://github.com/vinissimus/next-translate/releases/tag/1.1.1-canary.2). Also, I improved the default behavior to fix https://github.com/vinissimus/next-translate/issues/675
