### ISSUE TITLE
The the default locale according to the language of the user's browser

### ISSUE THREAD

**Issue by jim-king-2000** [vinissimus/next-translate#688]
**Description**
I setup a Next.js web site with `next-translate` successfully. It works fairly well. The default locale is not English. When we type `localhost:3000` to visit the first page of the web site, we find it jumps to `http://localhost:3000/en`. That is NOT what we expect. We expect it shows the default locale(which is `http://localhost:3000/`) in the configuration.

**Question**
1. How to get default locale initially?
2. Is it possible to select the locale initially according to the browser language?

**Comment by aralroca** [comment]
@jim-king-2000 all the i18n routing part is from Next.js https://nextjs.org/docs/advanced-features/i18n-routing with the information about [Automatic Locale Detection.
](https://nextjs.org/docs/advanced-features/i18n-routing#automatic-locale-detection) 

The next-translate library only merges the i18n routing logic of Next.js with the possibility to manage the translations of each page (logic of this library), but the language detection is not part of this library, it's from the Next.js core and is better to report this kind of issues on the Next.js GitHub.

**Comment by jim-king-2000** [comment]
I resolved the question 1 by adding this:

```javascript
// next.config.js
module.exports = {
  i18n: {
    localeDetection: false,
  },
}
```

Thanks.

**Comment by jim-king-2000** [comment]
And for question 2, the current logic works well. The issue is caused by the typo of the national acronym.
