### ISSUE TITLE
Allow to disable console log colors

### ISSUE THREAD

**Issue by rubenmoya** [vinissimus/next-translate#697]
Hello!

We're sending the Next.js logs to Amazon Cloudwatch, and the coloring of the terminal makes the logs unreadable:

```text
[36mnext-translate[0m - compiled page: [36m/[0m - locale: [36men[0m - namespaces: [36mheader, footer, common, home[0m - used loader: [36mgetInitialProps[0m
```

We had the same problem with Next.js logs, but using `FORCE_COLORS=0` solved the problem becuase they are using [chalk](https://github.com/chalk/chalk/) which handles that under the hood.

My first thought was to open a PR adding `chalk` to handle the coloring, which won't increase the users bundle size since Next.js already needs it, but one of the features of next-translate is _No dependencies_, so I'm not sure if that's the approach you would follow.

Another approach could be adding a small utility function, which won't cover all the use cases that [supports-color](https://github.com/chalk/supports-color) (the dependency used in `chalk`) does but it would solve my problem and it doesn't add a dependency.

What do you think?

**Comment by aralroca** [comment]
Prereleased under [1.1.1-canary.1](https://github.com/vinissimus/next-translate/releases/tag/1.1.1-canary.1). Thanks for the contribution

**Comment by rubenmoya** [comment]
Thank you for the quick response! :rocket:
