### ISSUE TITLE
Next Translate stops working with `pageExtensions`

### ISSUE THREAD

**Issue by einazare** [vinissimus/next-translate#703]
Hello guys,

Thank you for your awesome plugin.

I am trying to use your plugin with `pageExtensions` from NextJS (https://nextjs.org/docs/api-reference/next.config.js/custom-page-extensions). This is due to the fact that we want to build only certain pages, for different use cases. For example, we will have some pages for admin users, and some pages for simple users. And we will deploy these pages on different hosts, but we will also have some use cases where we'll need both the pages for admin and users to be built.
For this, we have decided to rename our pages from `pageName.js` (example: `/admin/search.js`) to `pageName.userType.js` (example: `/admin/search.admin.js`) and inside our `next.config.js` we specify using the `pageExtensions` which types of pages to be built (example: `pageExtensions: ["admin.js"]`). When doing this, the internationalization fails to load.

I've created here a reproduction repo: https://github.com/einazare/next-translate-demo
When you start it and navigate to http://localhost:3000/admin/search or http://localhost:3000/ro/admin/search, you will see that `{t("admin-search:input")}` will display `admin-search:input` instead of the value of that i18n variable, which is `Hey input` or `Salut intrare`.
The start the project, you can run in your terminal the following command:
- linux/mac: `npm run install && npm run dev`
- windows: `npm run install ; npm run dev`

I've tried using the `extensionsRgx` that you guys offer, but it doesn't work either. I've tried using it like `extensionsRgx: /\.(admin|user)\.(js)$/`.

Do you guys have any idea what am I doing wrong?

Live long and prosper, 🖖 
Manu

**Comment by kuus** [comment]
Actually @einazare after my comment I tried to use this library and it works with `pageExtensions`, here's my `i18n.js` in the project's root folder:

```js
module.exports = {
  locales: ["nl"],
  defaultLocale: "nl",
  extensionsRgx: /\.page\.(tsx|ts|js|mjs|jsx)$/,
  loadLocaleFrom: (locale, namespace) =>
    import(`./public/locales/${locale}/${namespace}.json`).then(
      (m) => m.default
    ),
  pages: {
    "*": ["common", "Header", "Footer"],
    "/": ["home"],
    "/article/[slug]": ["Article"],
    "rgx:^/articles": ["articles"]
  },
};
```
This is the bit of your interest:

```js
  extensionsRgx: /\.page\.(tsx|ts|js|mjs|jsx)$/,
```

**Comment by w4zZz4p** [comment]
Do you know how to define `extensionsRgx` in .json format? @kuus

**Comment by aralroca** [comment]
It's great to know that this works @kuus. Thanks! I hope it works for @einazare as well. 

I didn't remember that @berndartmueller implemented just that for page extensions in https://github.com/vinissimus/next-translate/pull/589 Do you think it should be better documented?

**Comment by w4zZz4p** [comment]
I think in case of `json` config its used as a string not regex

**Comment by kuus** [comment]
@w4zZz4p haven't tested id but I guess you need to escape the slashes

```json
  "extensionsRgx": "/\\.page\\.(tsx|ts|js|mjs|jsx)$/",
```

@aralroca 
>Do you think it should be better documented?

yes I think it's not documented, I don't remember if I got it from the source code or from that PR you linked ;)

**Comment by kuus** [comment]
Hi @aralroca a small thing missing is the `extensionsRgx` key in the `I18nConfig` interface: https://github.com/vinissimus/next-translate/blob/master/src/index.tsx#L48-L67
maybe you can add it in next release,
thanks in advance :)!

**Comment by aralroca** [comment]
Thanks @kuus
