### ISSUE TITLE
First try

### ISSUE THREAD

**Issue by Ali-Hussein-dev** [vinissimus/next-translate#708]
Hi, I am giving next-translate a try, but too early it is not working.

result -> common:cancel

expected: abrechnen

## Error messages

"[next-translate] "common:cancel" is missing in current namespace configuration. Try adding "cancel" to the namespace 'common' "

## Project structure

- root
  - locales
    - de
      - common.json
    - en-US
      - common.json
  - src
    - pages
      - index.tsx
  - next.config.js
  - i18n.js

## next.config.js

```js
const withPlugins = require('next-compose-plugins');
const withPWA = require('next-pwa');
const nextTranslate = require('next-translate');
const withBundleAnalyzer = require('@next/bundle-analyzer')({
  enabled: process.env.ANALYZE === 'true',
});

const nextConfig = (phase, config) => {
  const customConfig = {
    ...config,
    i18n: { locales: ['de', 'en-US'], defaultLocale: 'de' },
    experimental: { esmExternals: true },
    async headers() {
      return [
        {
          source: '/(.*)',
          headers: securityHeaders,
        },
      ];
    },
  };
  return customConfig;
};
module.exports = withPlugins(
  [
    [withBundleAnalyzer],
    [withPWA({ pwa: { dest: 'public' } })],
    [
      nextTranslate({
        webpack: (config) => {
          return config;
        },
      }),
    ],
  ],
  nextConfig()
);
// ...rest
```

## i18n.js

```js
module.exports = {
  locales: ['en-US', 'de'],
  defaultLocale: 'de',
  pages: {
    '*': ['common'],
    '/': ['home'],
    '/about': ['about'],
  },
};
```

## `src/pages/index.tsx`

```js
import * as React from 'react';
import useTranslation from 'next-translate/useTranslation';

const HomePage: React.FC = () => {
  const { t } = useTranslation();
  return (
    <main>
      <button>{t('common:submit')} </button>
      <button>{t('common:cancel')} </button>
    </main>
  );
};
export default HomePage;
```

**nextjs version** ^11.1.2

**next-translate version** ^1.1.1

**Comment by lil12t** [comment]
@Ali-Hussein-dev 
Rename pages folder and it will start to work
P.S. it took me hours to figure it out

**Comment by devpolo** [comment]
> @Ali-Hussein-dev Rename pages folder and it will start to work, for example src/pages/index.tsx -> src/atoms/index.tsx
> 
> P.S. it took me hours to figure it out

Not sure I got your point :/ Could you explain please ?

**Comment by Ali-Hussein-dev** [comment]
@devpolo I think I forgot what I was doing, I am using a new library sorry!
