### ISSUE TITLE
Per-page layouts are not rendering

### ISSUE THREAD

**Issue by carlosriveroib** [vinissimus/next-translate#717]
I'm using per-page layouts as described here https://nextjs.org/docs/basic-features/layouts#per-page-layouts and when I use them with next-translate the layout is not rendering. Can I get some help? Thank you very much

nextJS version: 11.1.2 and 12.0.1 (tried both)
next-translate version: 1.1.1

```js
// Layout.tsx

export const Layout = ({ children }: PropsWithChildren<unknown>): JSX.Element => {
  return (
    <main>
      {children}
    </main>
  );
};
```

```js
// index.tsx

import { Layout } from '@components';

const Home = (): JSX.Element => {
  const { t } = useTranslation();

  return (
    <div>
        {t('home:description')}
    </div>
  );
};

Home.getLayout = (page: PageProps) => <Layout>{page}</Layout>;

export default Home;
```

```js
// _app.tsx

function MyApp({ Component, pageProps }: Props): JSX.Element {
  const getLayout = Component.getLayout || ((page) => page);

  return getLayout(
    <>
      <CssBaseline />
      <Component {...pageProps} />
    </>
  );
}

export default MyApp;
```

**Comment by aralroca** [comment]
@carlosriveroib Can you try to add `hoist-non-react-statics` to copy the statics properties of components `getLayout`?

- docs: https://github.com/vinissimus/next-translate/blob/master/docs/hoist-non-react-statics.md

It's not included by default in order not to include more kb than necessary (static values different than getInitialProps in the pages are rarely used).

I hope it works.

**Comment by carlosriveroib** [comment]
Hi @aralroca, thanks for your answer. I just tried and still not working.
This is my i18n.js config file

```js
const hoistNonReactStatics = require('hoist-non-react-statics');

module.exports = {
  locales: ['en', 'es'],
  defaultLocale: 'en',
  pages: {
    '*': ['common'],
    '/': ['home'],
    staticsHoc: hoistNonReactStatics,
  },
  loadLocaleFrom: (locale, namespace) =>
    import(`./src/i18n/translations/${locale}/${namespace}`).then((m) => m.default),
};
```

and my next.config.js

```js
const nextTranslate = require('next-translate');

module.exports = nextTranslate({
  images: {
    formats: ['image/avif', 'image/webp'],
  },
  reactStrictMode: true,
});
```

**Comment by aralroca** [comment]
Change this:

```diff
odule.exports = {
  locales: ['en', 'es'],
  defaultLocale: 'en',
  pages: {
    '*': ['common'],
    '/': ['home'],
-    staticsHoc: hoistNonReactStatics,
  },
+ staticsHoc: hoistNonReactStatics,
  loadLocaleFrom: (locale, namespace) =>
    import(`./src/i18n/translations/${locale}/${namespace}`).then((m) => m.default),
};
```

**Comment by carlosriveroib** [comment]
Ok, now is working. So sorry, I didn't realize about that huge mistake...

Now it's working.
On the other hand, do you recommend me that? Should I avoid this? What will be a better approach to handle this?

Thank you

**Comment by aralroca** [comment]
no problem, we all make mistakes ! I'm glad it's working for you then. I close the issue

> do you recommend me that? Should I avoid this? 

It's good that you do it this way, it doesn't take up that much `hoist-non-react-statics` (1.2kb) and it's used by most libraries that use HOC to copy everything.

**Comment by rmlevangelio** [comment]
Thanks @aralroca for this solution!
