### ISSUE TITLE
Dynamic Import Language File 

### ISSUE THREAD

**Issue by dopt** [vinissimus/next-translate#718]
Hi, I am trying out the library, however it seems the build version will import all languages by default in user's browser.

### Github Repo
https://github.com/vercel/next.js/tree/master/examples/with-next-translate

### Reproduction
Download and run the repo, `npm run build`, visit [localhost:3000](url)
Inspect the Network, check the languages file downloaded. All languages has been downloaded in browsers regardless of select language.

### Expectation
Only en.json should be downloaded.

**Comment by aralroca** [comment]
It looks that the `<Link>` component that links to other lang pages, doesn't has `prefetch={false}`, and `prefetch` by default is `true` and it downloads content such as translations.

**Comment by dopt** [comment]
understood and I recalculated after using `prefetch={false}` and it doesn't import others json anymore. thanks for the prompt response.
