### ISSUE TITLE
apply translations in a route and all its sub-routes

### ISSUE THREAD

**Issue by Codeia** [vinissimus/next-translate#722]
Trying to apply translation to the following pages under `/onboarding`

**/onboarding**/1
**/onboarding**/2
**/onboarding**/3
**/onboarding**/success

Here's my code:

```
{
  "locales": ["he","en"],
  "defaultLocale": "he",
  "pages": {
    "*": ["common", "navigation"],
    "/onboarding/*": ["onboarding"]
  }
}
```

This doesn't seem to apply the "onboarding" namespace translations. 
Is there a right way to do this?

**Comment by aralroca** [comment]
Yes, with a regex.

```json
{
  "locales": ["he","en"],
  "defaultLocale": "he",
  "pages": {
    "*": ["common", "navigation"],
    "rgx:^/onboarding": ["onboarding"]
  }
}
```

**Comment by Codeia** [comment]
thank you so much! it helped me very much.
I have another question, not so related to the main thread.
How would you handle translation of Months, currencies, etc?
For example:
```
/pl/months.json
/es/months.json
```
Or is there a better way for this?

**Comment by aralroca** [comment]
In [1.2.0-canary.1](https://github.com/vinissimus/next-translate/releases/tag/1.2.0-canary.1)  (next 1.2 version) you can use the formatter function to simplify this: 

- PR https://github.com/vinissimus/next-translate/pull/712/ thanks to @j-schumann


You can format params using the `interpolation.formatter` config function.

in `i18n.js`:

```js
const formatters = {
  es: new Intl.NumberFormat("es-ES"),
  en: new Intl.NumberFormat("en-EN"),
}
return {
  // ...
  interpolation: {
    format: (value, format, lang) => {
      if(format === 'number') return formatters[lang].format(value)
      return value 
    }
  }
}
```

In English namespace:

```json
{
  "example": "The number is {{count, number}}"
}
```

In Spanish namespace:

```json
{
  "example": "El número es {{count, number}}"
}
```

**Comment by Codeia** [comment]
Worked like magic! Thank you! @aralroca  and thank you @j-schumann
