### ISSUE TITLE
webpack5 issue

### ISSUE THREAD

**Issue by fabien** [vinissimus/next-translate#728]
Hi, thanks for this great plugin! I've been using this in my apps with NextJS 10 for a while now.

At the time, I set `future.webpack5` to `false`. However, when I switch to `true` I'm having compile issues. The same goes for Upgrading to NextJS 11 or 12 (which implicitly use webpack5). The error I get relates to `getT` and `useTranslation`.

When I stub out those functions, the error goes away, so it definitely appears to happen within those.

```
Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading 'default')
```

**Comment by aralroca** [comment]
@fabien Do you have an example to reproduce the issue? In [our example](https://github.com/vinissimus/next-translate/tree/master/examples/complex) we actually have webpack 5 and it works correctly. Thanks!

**Comment by fabien** [comment]
@aralroca I managed to solve the issue. I was re-exporting some helper methods as part of a library (index.js) file:

It all worked after changing the code from this:

```javascript
export { default as getTranslation } from 'next-translate/getT';
export { default as useTranslation } from 'next-translate/useTranslation';
```

To this:

```javascript
import getT from 'next-translate/getT';
import useT from 'next-translate/useTranslation';

export const getTranslation = (...args) => getT(...args);
export const useTranslation = (...args) => useT(...args);
```
