### ISSUE TITLE
Unable to translate key with dot in its name

### ISSUE THREAD

**Issue by fritzlolpro** [vinissimus/next-translate#731]
Hello.
Im currently migrating our project on Nextjs and this library fits perfect for translations, but there is a problem as we have couple of thousands translations with dots in names something like
```
main.page.header
main.page.subheader
```
and so on.

Not the cleverest design but I cant change it.

In transCore.js in function getDicValue all words are split with .split('.') so translations break down. 
![image](https://user-images.githubusercontent.com/10850158/141995766-02ba21f5-8882-4bb7-b69f-bee8a2120ff3.png)

The simplest solution in my opinion is to let user set custom nesting separator with "." as default and in getDicValue use .split(nestingSeparator) instead of hardcoded one and also use this separator in plural function where dot is also hardcoded.
This shouldn't break backwards compatibility and also will solve issues like mine and possible similar problems.
If Im correct I can do a pr

Probably Im doing everything wrong and missed something important or my solution wouldn't work at all, could you please help me.

**Comment by aralroca** [comment]
@fritzlolpro Take a look this PR that @testerez did: https://github.com/vinissimus/next-translate/pull/729 a new configuration property is added to [1.3.0-canary.2](https://github.com/vinissimus/next-translate/releases/tag/1.3.0-canary.2) version (future 1.3.0).   I hope it solves your problem.

**Comment by fritzlolpro** [comment]
Yes! It looks like my problem-solver, thanks a lot!

Hope this release will be on npm soon.

This issue is resolved.

**Comment by testerez** [comment]
It's good to see it's already helping someone else ! 👏

> Hope this release will be on npm soon.

Actually it is: `yarn add next-translate@1.3.0-canary.2`
