### ISSUE TITLE
Multiple translation variables with similar names are not translating correctly (regression in 1.2.0)

### ISSUE THREAD

**Issue by pgrippi** [vinissimus/next-translate#737]
Starting in 1.2.0 if a translation includes variables that start with the same prefix (like `{{budget}} and {{budgetType}}`), the longer variables are replaced with the shorter variables

With this translation:

```
{
  "budgetExample": "Budget: {{budget}}, Type: {{budgetType}}"
}
```

Using `t('budgetExample', { budget: 20, budgetType: 'per person' })`:

* In 1.1.1 it correctly translates to `Budget: 20, Type: per person`
* In 1.2.0 it incorrectly translates to: `Budget: 20, Type: 20`

Example repo: https://github.com/pgrippi/next-translate-multiple-variable-bug. If you downgrade to 1.1.1 you can see the translation change to the correct one.

**Comment by aralroca** [comment]
Probably introduced in this PR https://github.com/vinissimus/next-translate/pull/729 from @testerez. This test was missing. Thanks for reporting it.

**Comment by pgrippi** [comment]
This was fixed in https://github.com/vinissimus/next-translate/pull/782
