### ISSUE TITLE
LocaleKeys Generator

### ISSUE THREAD

**Issue by saschahapp** [vinissimus/next-translate#747]
Hello dear next-translate community,

I opened this issue, to present some idea which we use in our companies project. Of course using your package as well. 
One thing in advance if this what I present already exists in a similar way, then remove this issue and I have to apologise.

<img width="1028" alt="Screenshot 2021-12-10 at 11 36 57" src="https://user-images.githubusercontent.com/71318727/145560803-b9d556ee-d0bf-4ef8-9446-7a2d0b0dea78.png">
<img width="1046" alt="Screenshot 2021-12-10 at 11 37 39" src="https://user-images.githubusercontent.com/71318727/145560872-cba1c309-dbbd-4380-a5d2-c00fdd9ae1f6.png">

this file will be generated, and it gives you all the possible translation keys to access. Of course with IDE support, that you can see the actual translation value. This helps for not making any typo, not searching the keys with the corresponding translation in the .json files and if keys change it will throw an error when the key in not available any more.

This examples present only a little idea with a prototype to see the possible result. 

Have a nice day!

**Comment by bperun123** [comment]
Great idea!

**Comment by ajmnz** [comment]
If you're using TypeScript, see [this solutions](https://github.com/vinissimus/next-translate/issues/721#issuecomment-966266255)

**Comment by saschahapp** [comment]
possible package: https://github.com/saschahapp/next-translate-localekeys-generator/packages/1448830
