### ISSUE TITLE
Add "revalidate" to the getStaticProps generated by the webpack loader

### ISSUE THREAD

**Issue by bmvantunes** [vinissimus/next-translate#754]
Currently the loader creates a getStaticProps function that returns:
```
return { props: { ..... } }
```

Would you accept if I create a PR to add an optional property called `revalidate`?

For example if we have `revalidate:20` inside the i18n.json file the loader would produce:
```
return { revalidate: 20, props: { ..... } }
```

That feature would be very useful for people that keep their translation files externally to their app.
For example: In that scenario if the translations change, the app would "automatically" regenerate after the given `revalidate` time. Without a new deployment we would have the latest translations.

If people don't pass the `revalidate` property, then everything should behave exactly like it does today.

**Comment by aralroca** [comment]
I don't understand why is necessary to define this inside `i18n.json` file. Do you mean as a default if the `getStaticProps` is not defined in the page? Currently, it overwrites only the `props` of your `getStaticProps`:

https://github.com/vinissimus/next-translate/blob/master/src/plugin/templateWithLoader.ts#L86

So if you already have a `getStaticProps` with `revalidate` it should respect it.

If it is as default when there is no `getStaticProps` in the page then maybe it makes sense. Feel free to do the PR! Thanks for the suggestion @bmvantunes!

**Comment by bmvantunes** [comment]
Yes @aralroca exactly what you described in your last paragraph :)
PR is opened :)
