### ISSUE TITLE
getStaticProps is not called

### ISSUE THREAD

**Issue by MLerasle** [vinissimus/next-translate#76]
I just tried to migrate from getInitialProps to getStaticProps but the new method is never called.

Just try with the documentation example to reproduce:

```
import fetch from 'node-fetch'

function Blog({ posts }) {
  return (
    <ul>
      {posts.map(post => (
        <li>{post.title}</li>
      ))}
    </ul>
  )
}

export async function getStaticProps() {
  console.log('Call getStaticProps')
  const res = await fetch('https://.../posts')
  const posts = await res.json()

  return {
    props: {
      posts
    }
  }
}

export default Blog
```

**Comment by BjoernRave** [comment]
@MLerasle should be fixed with: https://github.com/vinissimus/next-translate/pull/75 . Just update to 0.10.6 and it should work :)

**Comment by MLerasle** [comment]
@BjoernRave wow 7 minutes to solve the issue and reply, thank you very much :) 
This is working like a charm!
