### ISSUE TITLE
Plural key for count == 0 is incorrectly ignored.

### ISSUE THREAD

**Issue by Maczuga** [vinissimus/next-translate#771]
Used version: 1.2.0

I have a simple translation:
```tsx
<span>{t("productShow:rating_count", {count})}</span>
```

I have following translation keys generated for it:
```json
{
  "rating_count_one": "{{count}} opinia",
  "rating_count_few": "{{count}} opinie",
  "rating_count_many": "{{count}} opinii",
  "rating_count_other": "{{count}} opinii",
}
```

Used locale is Polish (pl).

This works for all numbers, except for 0 because of this line:
https://github.com/vinissimus/next-translate/blob/72648f845d0fea451ab65d91160c13c565ff2c75/src/transCore.tsx#L148

I get following error currently:
[next-translate] "productShow:rating_count" is missing in current namespace configuration. Try adding "rating_count" to the namespace "productShow".

Why is there a condition for > 0? Following PluralRules are correct which return `many` for pl language and `other` for en language.
```js
(new Intl.PluralRules("pl")).select(0)
```

I would have to add either base key "rating_count" to my JSON or add "rating_count_0" - however all translation extraction tools are already using the Intl.PluralRules values to generate proper keys.

What is the reasoning behind adding said condition? Pretty sure this can be just removed and leave it to natural key handling of Intl.PluralRules

**Comment by aralroca** [comment]
The reason was more for performance to avoid the calculation of `getDicValue` for all texts that do not have the parameter `count` as numeric (since inside there is a reduce). It can probably be replaced by `typeof count === 'number'`.
