### ISSUE TITLE
How do I insert line break in a string?

### ISSUE THREAD

**Issue by bsgies** [vinissimus/next-translate#776]
Hi,

My sample JSON file is like:

{
   "test": "This is a test. I want this sentence in new line",
}

I have tried \n or <br> but it doesn't work. How can I break line?

**Comment by aralroca** [comment]
you can visualize this example like:

```js
<div>{t`namespace:test`}</div>
```

Is the same that:


```js
<div>
This is a test.
I want this sentence in new line
</div>
```
And inside a `div` this doesn't work.

As an alternative you can use HTML inside your translations:

```json
{
"test": "<0>This is a test.</0><1>I want this sentence in new line</1>",
}
```

```js
import Trans from 'next-translate/Trans'
// ...
<Trans
  i18nKey="namespace:test"
  components={[<div />, <div />]}
/>
```

- Reference: https://github.com/vinissimus/next-translate#6-use-html-inside-the-translation

**Comment by bsgies** [comment]
In my home.js:

![image](https://user-images.githubusercontent.com/32961638/152893036-84fad069-73fb-43dd-8519-2f2d61ad5f0a.png)
![image](https://user-images.githubusercontent.com/32961638/152893108-7233854f-5146-4ced-bcb0-b452e6b3a791.png)


In my translation.json:

![image](https://user-images.githubusercontent.com/32961638/152893265-dc6e64f9-52a6-4e0b-a354-2a0c5421a739.png)

Output:
![image](https://user-images.githubusercontent.com/32961638/152893298-a4473cac-ec70-4a83-9307-06d713bde066.png)


Why is it like this?

**Comment by gynekolog** [comment]
```tsx
<Trans
 i18nKey={"I'm a first line.<br/>So what? I'm second."}
 components={{
   br: <br />,
 }}
/>
```
