### ISSUE TITLE
Async function in useEffect causes loop when using the default namespace

### ISSUE THREAD

**Issue by aya-eiya** [vinissimus/next-translate#779]
In a situation where I set the default namespace as an argument of `useTranslation` to get `t` and monitor it with `useEffect`, I found that when I call asynchronous functions such as `setTimeout` in `useEffect`, the function keeps being called infinitely.

Here is the reproduction code.

```typescript
import useTranslation from 'next-translate/useTranslation'
import { ReactElement, useEffect, useState } from 'react'

export default function I18nTest(): ReactElement {
  const { t } = useTranslation('common')
  const [text, setText] = useState('')
  useEffect(() => {
    const ts = setTimeout(() => {
      setText(new Date().toISOString())
    }, 1000)
    return () => clearTimeout(ts)
  }, [t])
  return (
    <div>{text}</div>
  )
}
```

Is this the expected behavior?

Environments

```
$ node --version
v14.18.2
```

```
"dependencies": {
  "next": "^12.0.10",
  "next-translate": "^1.3.3",
  "react": "^17.0.2"
}
```

**Comment by aralroca** [comment]
This was solved in: https://github.com/vinissimus/next-translate/pull/574

And reverted to solve this bug with `Component.layout`: https://github.com/vinissimus/next-translate/issues/604
 
There is currently a PR proposal to put it again: https://github.com/vinissimus/next-translate/pull/743 ...

However you can memorize the `t` as workaround or use `lang` as dependency.

**Comment by aya-eiya** [comment]
Thanks @aralroca for response, I know it's a bug,  then I'll take the work-arounds when it becomes an issue in my project until it is resolved.
