### ISSUE TITLE
Routing in static mode

### ISSUE THREAD

**Issue by justincy** [vinissimus/next-translate#78]
Static mode uses URLs with the language prefix, e.g. `/es/about`. Thus when changing the URL, the app needs to know what the current language is. This is easily accomplished with Link, by creating a simple wrapper. Something like this:

```jsx
function withLangPrefix(url, lang): string {
  if (url && url.length > 0) {
    return url.charAt(0) === '/' ? `/${lang}${url}` : `/${lang}/${url}`;
  }
  return url;
}

function Link({
  children,
  href,
  as,
  ...props
}) {
  const { lang } = useTranslation();
  return (
    <NextLink
      href={withLangPrefix(href, lang)}
      as={withLangPrefix(as, lang)}
      {...props}
    >
      {children}
    </NextLink>
  );
}
```

But how would we do the same when using `Router.push()`? `Router.push()` is used when you're not inside a component but need to change the URL, such as a default response to HTTP 401 responses. I thought about creating a wrapper for `Router.push()`

```js
const push = (
  url,
  as,
  options
) => {
  return Router.push(withLangPrefix(url, 'en'), as, options);
};
```

But notice how I hardcoded the language in that example. It's because I don't know of any way to ask for the current language outside of a component. Can that be done? Is it a reasonable feature request?

**Comment by aralroca** [comment]
At this moment there are two workarounds to fix this:

* Wrapping the lang everywhere from the hook `useTranslation`.
* Setting a global variable with the lang and use it everywhere (only for client side, in server side is not recommended for concurrence issues)

The second way can be useful to use it in places like `getStaticProps` when the `useTranslation`is not possible before the execution of that method.

However, I recognize that would be great to provide a solution for that. Maybe just some import:

```js
import clientSideLang from 'next-translate/clientSideLang'

// ...

function myHelper() {
  const lang = clientSideLang()
  // ..
}

**Comment by aralroca** [comment]
Also, thanks to tree-shaking, we can add `Link` and `Router` wrappers as:

```js
import Link from 'next-translate/Link'
import Router from 'next-translate/Router'
```

without affecting the size of the lib in the case to don't use those imports.
