### ISSUE TITLE
next.config.js module export error

### ISSUE THREAD

**Issue by ibrahim-ahmed2** [vinissimus/next-translate#780]
I have the following code in my next.config.js and it currently works

```
const nextTranslate = require("next-translate")

module.exports = nextTranslate
```

When i try to change `module.exports = nextTranslate` to `module.exports = nextTranslate()`, I get the following typescript error:

This expression is not callable.
Type 'typeof import("D:/test/node_modules/next-translate/index")' has no call signatures.ts(2349)

**Comment by aralroca** [comment]
`module.exports` should return an object.  Normally `require("next-translate")` works, but try with `require("next-translate").default`:

```js
const nextTranslate = require("next-translate").default

module.exports = nextTranslate()
```

**Comment by ibrahim-ahmed2** [comment]
That got rid of the IDE error but when I run the app I get the following error now:

error - Failed to load next.config.js, see more info here https://nextjs.org/docs/messages/next-config-error
TypeError: nextTranslate is not a function

This is the type i see when i hover over `const nextTranslate`:

![image](https://user-images.githubusercontent.com/96270886/153780579-ed3a219f-6553-4a7a-a979-c12188d2b6ab.png)

**Comment by ibrahim-ahmed2** [comment]
I am also getting this error even on a brand new app using `npx create-next-app@latest`. 

For reference, I am also using the latest version of Visual Studio Code:

![image](https://user-images.githubusercontent.com/96270886/153949062-79af1509-93e9-470a-915b-e043ef1d18fe.png)

**Comment by aralroca** [comment]
And which version of next-translate are you using?

**Comment by ibrahim-ahmed2** [comment]
@aralroca I have `"next-translate": "^1.3.4"` in my package.json

Could you also see this [reproduction repository](https://github.com/ibrahim-ahmed2/next-translate-780-next.config.js-module-export-error) and see if this problem happens for you too?

Or just take a look at the project setup steps/package.json if u need to.

**Comment by aralroca** [comment]
If you read the Error message after `yarn dev`, is saying that you miss the `i18n` file.

In reality ou miss 2 things:
- Add [`i18n.json`](https://github.com/vinissimus/next-translate#add-i18njs-config-file) file
- Add [`locales`](https://github.com/vinissimus/next-translate#create-your-namespaces-files) folder with your translations

[`i18n.json`](https://github.com/vinissimus/next-translate#add-i18njs-config-file) file: 

```json
{
  "locales": ["en", "ca", "es"],
  "defaultLocale": "en",
  "pages": {
    "*": ["common"],
    "/": ["home", "example"],
    "/about": ["about"]
  }
}
```

[`locales`](https://github.com/vinissimus/next-translate#create-your-namespaces-files):

```
.
├── ca
│   ├── common.json
│   └── home.json
├── en
│   ├── common.json
│   └── home.json
└── es
    ├── common.json
    └── home.json
```

More details in the [documentation](https://github.com/vinissimus/next-translate/blob/1.3.4/README.md#2-getting-started).

**Comment by ibrahim-ahmed2** [comment]
@aralroca You are right, i have just pushed a valid next-translate setup to the repo.

As it is currently in the repo, everything works but the issue I am having is the error in next.config.js 

Also, thanks for the help so far :)

https://user-images.githubusercontent.com/96270886/154172930-3ba608f4-03ce-4afc-b5e4-f03aec22affd.mp4

**Comment by ibrahim-ahmed2** [comment]
Closing this now.

Was able to fix by resetting my VS Code settings.

https://stackoverflow.com/questions/36108515/how-to-reset-settings-in-visual-studio-code

**Comment by mkbctrl** [comment]
I have the same issue. Just wanted to set things up.

I did the following steps:
1. install package
2. add config
3. add locales
4. update next config

Translations work but the error is present. Reseting VScode settings doesn't help

**Comment by louismonteiro** [comment]
> Closing this now.
> 
> Was able to fix by resetting my VS Code settings.
> 
> https://stackoverflow.com/questions/36108515/how-to-reset-settings-in-visual-studio-code

This worked for me
