### ISSUE TITLE
How to exclude  some route?

### ISSUE THREAD

**Issue by miladezzat** [vinissimus/next-translate#795]
Hello
How to exclude some routes from adding the language prefix?

**Comment by miladezzat** [comment]
@aralroca

**Comment by aralroca** [comment]
All the i18n routing part is implemented on Next.js core and not in this library. This library is used to manage translations later on each page.

I share a discussion on this topic in Next.js to see if it can help you: https://github.com/vercel/next.js/discussions/28554
