### ISSUE TITLE
_zero plural format not working 

### ISSUE THREAD

**Issue by groomain** [vinissimus/next-translate#796]
Hi,

In the README it's saying that the _zero plural format is used  when the count is equal to zero.
The key with _zero isn't working but it's working with _0.

i18n-parser remove the keys with _0 but keep _zero. 
How can I use _zero?

Thanks!

Maybe it's related to https://github.com/vinissimus/next-translate/issues/771

https://github.com/vinissimus/next-translate/blob/72648f845d0fea451ab65d91160c13c565ff2c75/src/transCore.tsx#L148

new Intl.PluralRules('ar-EG').select(0);
'zero'
new Intl.PluralRules('fr-FR').select(0);
'one'

> We support 6 plural forms (taken from [CLDR Plurals](http://cldr.unicode.org/index/cldr-spec/plural-rules) page) by adding to the key this suffix (or nesting it under the key with no _ prefix):
> 
> **_zero**
> _one (singular)
> _two (dual)
> _few (paucal)
> _many (also used for fractions if they have a separate class)
> _other (required—general plural form—also used if the language only has a single form)

**Comment by aralroca** [comment]
This `count > 0` looks like a mistake.  Probably for performance to avoid the calculation of `getDicValue` for all texts that do not have the parameter `count` as numeric (since inside there is a reduce)
