### ISSUE TITLE
Prevent next-translate from using getInitialProps because of HoC in _app.ts

### ISSUE THREAD

**Issue by hmbrg** [vinissimus/next-translate#801]
Currently, next-translate is using the getInitalProps strategy in my app, because I'm using a HoC in my `_app.ts`, but that HoC is not adding any getInitalProps to _app.ts. 

How can I force next-translate to use the preferred getStaticProps strategy instead? My `_app.ts` looks like this: 

```
import { withTRPC } from './trcp';
import { SessionProvider } from 'next-auth/react';
import { AppProps } from 'next/app';
import Head from 'next/head';
import './styles.css';

function CustomApp({ Component, pageProps }: AppProps) {
  return (
    <SessionProvider session={pageProps?.session}>
      <Head>
        <title>Welcome to web!</title>
      </Head>
      <main className="app">
        <Component {...pageProps} />
      </main>
    </SessionProvider>
  );
}

const WrappedApp = withTRPC(CustomApp);

export default WrappedApp;

```

**Comment by aralroca** [comment]
Adding an empty `getStaticProps` on your `_app.js` should fix this:

```js
export let getStaticProps = undefined
```

**Comment by Naumov1889** [comment]
> Adding an empty `getStaticProps` on your `_app.js` should fix this:
> 
> ```js
> export let getStaticProps = undefined
> ```

If add that line then this kind of problem occures:
"common:profile" is missing in current namespace configuration. Try adding "profile" to the namespace "common"

**Comment by Naumov1889** [comment]
> > Adding an empty `getStaticProps` on your `_app.js` should fix this:
> > ```js
> > export let getStaticProps = undefined
> > ```
> 
> If add that line then this kind of problem occures: "common:profile" is missing in current namespace configuration. Try adding "profile" to the namespace "common"

sorry, the problem was in next.config.js, my webpack config was overriding next-translate's one i guess.

My config was defined like:
```js
const nextConfig = nextTranslate({
  webpack(config, ctx) {
  ...
```

changing it to:
```js
const nextConfig = nextTranslate({
  webpack: (config, ctx) => {
  ...
```
fixed it
