### ISSUE TITLE
Is there any way to add dir=rtl for chosen locales?

### ISSUE THREAD

**Issue by bsgies** [vinissimus/next-translate#802]
Hi,

Is there any built-in way in next-translate that could help add the dir=rtl tag in the body in certain languages so that the page can be loaded from rtl?

Regards,
Bilal

**Comment by aralroca** [comment]
No... You need to add it manually

```js
// pages/_document.js

import Document, { Html, Head, Main, NextScript } from 'next/document';

class MyDocument extends Document {
  static async getInitialProps(ctx) {
    const initialProps = await Document.getInitialProps(ctx);
    return { ...initialProps };
  }

  render() {
    const { locale } = this.props.__NEXT_DATA__;
    const dir = locale === 'ar' ? 'rtl' : 'ltr';
    return (
      <Html lang={locale} dir={dir}>
        <Head />
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}

export default MyDocument;
```

**Comment by bsgies** [comment]
@aralroca Seems like working but it requires a refresh for rtl to be added. How can I add it in real time when the user clicks on the language name?

The code for changing language is given below:

                  <Dropdown>
                      <Dropdown.Toggle>
                        <div className="d-flex align-items-center">
                          <LanguageIcon />
                          <div className="f-s-14">English</div>
                        </div>
                      </Dropdown.Toggle>
                      <Dropdown.Menu>
                          <Dropdown.Item>
                            <ul>
                              {router.locales.map((locale) => 
                                    <li key={locale}>
                                          <Link href={router.asPath} locale={locale}>
                                          <a>{locale}</a>
                                        </Link> 
                                    </li>
                                )}
                            </ul>
                          </Dropdown.Item>
                      </Dropdown.Menu>
                    </Dropdown>

**Comment by aralroca** [comment]
You can change it with JavaScript `document.head.dir = 'rtl'`

**Comment by bsgies** [comment]
> You can change it with JavaScript `document.head.dir = 'rtl'`

Can you tell me how this can be achieved using a sample code? I'm pretty new to JS

**Comment by aralroca** [comment]
Inside the `onClick`:

```jsx
<Dropdown>
    <Dropdown.Toggle>
      <div className="d-flex align-items-center">
        <LanguageIcon />
        <div className="f-s-14">English</div>
      </div>
    </Dropdown.Toggle>
    <Dropdown.Menu>
        <Dropdown.Item>
          <ul>
            {router.locales.map((locale) => 
                  <li key={locale}>
                        <Link 
                           {/* You need to use the onClick event */}
                            onClick={() => { document.head.dir = 'rtl' }} 
                            href={router.asPath} 
                            locale={locale}
                        >
                        <a>{locale}</a>
                      </Link> 
                  </li>
              )}
          </ul>
        </Dropdown.Item>
    </Dropdown.Menu>
  </Dropdown>
```

Probably you need a condition to change it depending the language:

```js
const rtlLocales = new Set(['ar', 'he'])

function onClick() {
   document.head.dir = rtlLocales.has(locale) ? 'rtl' : 'lrt'
}
```
