### ISSUE TITLE
namespaces are not loaded according to the pages attribute in config

### ISSUE THREAD

**Issue by yfhui** [vinissimus/next-translate#835]
I am looking at the loading behaviors of the namespaces, and I discovered the following:

assume I have three namespaces called "common", "pageA" and "pageB", I have this config in i18n.js
```
    pages: {
        "*": ["common"],
        "/pageA": ["pageA"],
        "/pageB": ["pageB"],
    },
```
    
but then I check the packed _app.js, then **I found that all locales and all namespaces are loaded** at home page (I exepct it should be only loading "common" namespace and have the locale that the user is using.

I can also see the same issue in the example (the complex example):
in _app.js, when visiting "/", and we can see "more-examples" is loaded
![image](https://user-images.githubusercontent.com/48435910/163147386-32f6a7ea-8811-466e-9cf0-44c489377b10.png)

but the config is 
```  
pages: {
    '*': ['common'],
    '/404': ['error'],
    '/': ['home'],
    '/dashboard': ['home'],
    'rgx:^/more-examples': ['more-examples'],
  },
```
Because I am assuming when some page is visited, only the matching namepsace will be loaded. I am wondering what kind of thing is missing? Or I have a wrong understanding of the behaviors? :(

Edit: typo

**Comment by vadymshymko** [comment]
Hello, @yfhui . If you are using a next compiler (you don't have a custom babelrc file), i think you should look into [this issue](https://github.com/vinissimus/next-translate/issues/741).

**Comment by yfhui** [comment]
Thx! using fetch solved the issue!
