### ISSUE TITLE
next config pageExtensions issue

### ISSUE THREAD

**Issue by spock123** [vinissimus/next-translate#838]
I have set up next-translate with standard configuration, added single "common" namespace and it works fine.

i18n config has defined one namespace for everything: 

```
 pages: {
    '*': ['common'],
  },
```

However, if I change my `next.config.js` to use  `pageExtensions: ['page.tsx', 'page.ts', 'page.jsx', 'page.js']` , translate() no longer works, but just returns the translation key as result.

As soon as I resort to default pageExtensions, it works again.

Any help would be appreciated, thanks

**Comment by thacoon** [comment]
I had the same problem to fix it I changed my `i18n.json` to `i18n.js` and added `extensionsRgx` as described [here](https://github.com/vinissimus/next-translate/issues/703#issuecomment-955580139):

```js
module.exports = {
  locales: ["en", "de"],
  defaultLocale: "en",
  extensionsRgx: /\.page\.(tsx|ts|js|jsx)$/,
  pages: {
    "*": ["common"],
    "/": ["home"],
  },
};
```

My `next.config.js` looks like this:

```js
const nextTranslate = require('next-translate');

const nextConfig = {
  reactStrictMode: false,
  experimental: {
    outputStandalone: true,
  },
  pageExtensions: ['page.tsx', 'page.ts', 'page.jsx', 'page.js'],
};

module.exports = nextTranslate(nextConfig);
```

**Comment by spock123** [comment]
@thacoon thank you so much! I'll give it a spin. Cheers.

**Comment by Xilel** [comment]
This should be added to README

**Comment by aralroca** [comment]
@Xilel please feel free to PR
