### ISSUE TITLE
How to use all locales from server ONLY

### ISSUE THREAD

**Issue by fs-innonova** [vinissimus/next-translate#858]
Hi guys, Im trying to use next to load all the locales from server API and not from any local folder

in `_app.tsx`:
```
export const getInitialProps = () => ({});
```
in `i18n.js`:
```
module.exports = {
  locales: ['en', 'de'],
  defaultLocale: 'en',
  pages: {
    '*': ['common'],
    'rgx:^/projects': ['projects'],
    'rgx:^/user': ['user'],
    'rgx:^/help': ['help'],
  },
  loadLocaleFrom: async (locale, namespace) => {
    const localesUrl = `${window.location.origin}/api/i18n/${locale}/${namespace}/translations.json`;
    try {
      const response = await fetch(localesUrl);
      if (response.status === 200) {
        return await response.json();
      }
      console.error(`Fetching translations from ${localesUrl} failed`, response);
    } catch (e) {
      console.log(`Fetching translations from ${localesUrl} failed`, e);
    }
    return {};
  },
};
```

What happens is, on the first load no translations are coming, after navigation in the app then all works fine.

**Comment by aralroca** [comment]
The `loadLocaleFrom` code is isomorphic, so it works on both client and server. If it doesn't work in server is because `window` doesn't exist in Node.js. You can implement a different logic depending on `typeof window === 'undefined'`

**Comment by fs-innonova** [comment]
Is there any way for me to see the logs when the function `` is called from the server?

I also tried this:
```
const origin = process.env.BFF_URL || window.location.origin;
const localesUrl = `${origin}/api/i18n/${locale}/${namespace}/translations.json`;
```
but I have no idea if he gets that env variable

> As a curiosity, what are the advantages of using the API instead of importing a file?
the advantages is that we host the translations in another service and lets say, if we want to change a translation in prod we don't need to redeploy the app :)

**Comment by aralroca** [comment]
> Is there any way for me to see the logs when the function `loadLocaleFrom` is called from the server? I also tried this option but nothing changed -> `loggerEnvironment: 'both',`

Sorry, this logger (`loggerEnvironment`) is a function to log the missing keys in development and production, not when the `loadLocaleFrom` is called. 

> but I have no idea if he gets that env variable

Inside the `loadLocaleFrom` you can debug normally, or just add a `console.log(process.env.BFF_URL)`.

> actually the only log I get from server (when I reload the app) is this:
next-translate - compiled page: /projects - locale: en - namespaces: common, projects - used loader: getInitialProps

Yes, each time namespaces are loaded in `loadLocaleFrom` a log is executed in the terminal where you can see which method has been used (getInitialProps, getStaticProps, etc) and which namespaces have been loaded. But it is only informative and can only be turned on and off with `logBuild: false`:

<img width="885" alt="image" src="https://user-images.githubusercontent.com/13313058/169016660-f16e4e17-a4a4-41a9-9b1f-82f9af0fdae9.png">

 If you are using `getInitialProps` in `_app.js`, the `loadLocaleFrom` is called inside the `getInitialProps`.

**Comment by fs-innonova** [comment]
Thats the thing, with normal console.log nothing is printed.. maybe as you said because in `_app.tsx` I use `getInitialProps` but I only added that there as a "trick" so that next always get the translations from that loader. If you notice I have no code inside `getInitialProps` should I have?

**Comment by fs-innonova** [comment]
So If I have this log:
```next-translate - compiled page: /projects - locale: en - namespaces: common, projects - used loader: getInitialProps```
this means that the `loadLocaleFrom` is not called from 1st render right? is calling only the `getInitialProps`

**Comment by aralroca** [comment]
A `console.log` it should work. Maybe is throwing an error because `process.env.BFF_URL` is empty and trying to get `window.location.origin` is not possible because `window` is `undefined`. 

Have you tried to put a try-catch to debug if you have an error within the `loadLocaleFrom `?

**Comment by fs-innonova** [comment]
yes, look:

```
module.exports = {
  locales: ['en', 'de'],
  defaultLocale: 'en',
  pages: {
    '*': ['common'],
    'rgx:^/projects': ['projects'],
    'rgx:^/user': ['user'],
    'rgx:^/help': ['help'],
  },
  loadLocaleFrom: async (locale, namespace) => {
    console.log('window.location', window.location.host);
    console.log('process.env.BFF_URL', process.env.BFF_URL);
    try {
      const origin = process.env.BFF_URL || window.location.origin;
      const localesUrl = `${origin}/api/i18n/${locale}/${namespace}/translations.json`;
      const response = await fetch(localesUrl);
      if (response.status === 200) {
        return await response.json();
      }
      console.error(
        `Fetching translations from ${localesUrl} failed`,
        response
      );
    } catch (e) {
      console.error(`Fetching translations from ${localesUrl} failed`, e);
    }
  },
};
```
and this are the server logs:
<img width="1037" alt="image" src="https://user-images.githubusercontent.com/93779923/169035750-7d31998e-6f41-4095-b5db-0d958c3049fa.png">

**Comment by aralroca** [comment]
`console.log('window.location', window.location.host);` I'm sure is throwing an error in Node.js because `window` is `undefined`, and is outside the try-catch

**Comment by fs-innonova** [comment]
Even inside the `try` still same result no log :(

**Comment by aralroca** [comment]
well, I'm glad you solved it 😊
