### ISSUE TITLE
Feature request for getT: get multiple namespaces 

### ISSUE THREAD

**Issue by slevy85** [vinissimus/next-translate#861]
Hi,
I have been using next-translate for a while and it is a great library thank you very much.

I am coming accross a problematic where I need to translate some messages server-side with `getT` but the messages can belong to different namespaces, so I have this kind of code:  

```
   const [tErrors, tGeneral] = await Promise.all([
      getT(lang, 'errors'),
      getT(lang, 'general'),
    ])
```
This is ok if I know what message belongs to what namespace

```
const errorMessage = getErrorMessage(req)
const translated = tErrors(errorMessage)

```

But if I don't know what namespace the message belongs I will need to make more checks:
```
const message = getMessage(req) // can be an error message or a general message 
const translated = tErrors(message, null, {fallback: tGeneral(message)})
```

I wish I could load many namespaces in `getT` just like `useTranslation` can:

```
const t = getT(lang, ['errors', 'general'])
const message = getMessage(req) // can be an error message or a general message 
const translated = t(message)
```

Thank you very much.

**Comment by aralroca** [comment]
Another workaround maybe is overwrite `loadLocaleFrom` in `i18n.js` file with a custom implementation:

**i18n.js**
```js
{
  // ...rest of config
  loadLocaleFrom: async (locale, namespaces) => {
    const dicts = await Promise.all(
      namespaces
      .split(',')
      .map(namespace => import(`./locales/${locale}/${namespace.trim()}`).then((m) => m.default))
    )

    return dicts.reduce((acc, dict) => ({ ...acc, ...dict }), {})
  }
```

Then:

```js
const t = getT(lang, 'errors, general'])

```

**Comment by slevy85** [comment]
Yes this is a good idea but it looks less clear than `getT(lang, ['ns1', 'ns2'])`, would you accept a pull request for it ?

**Comment by aralroca** [comment]
Yes feel free to implement it!

**Comment by slevy85** [comment]
In fact i tried this way but it doesn't seem to allow to have the namespace syntax (like  `t('errors:error.message')`), it is like all translations are in one namespace called `'errors, general'` in the case of  `getT(lang, 'errors, general')`:  
```
 loadLocaleFrom: async (locale, namespaces) => {
    const dicts = await Promise.all(
      namespaces
      .split(',')
      .map(namespace => import(`./locales/${locale}/${namespace.trim()}`).then((m) => m.default))
    )

    return dicts.reduce((acc, dict) => ({ ...acc, ...dict }), {})
}
  ```

Anyway, I hope that the pull request #862 will be ok.

**Comment by aralroca** [comment]
Prereleased in 1.5.0-canary.1

**Comment by slevy85** [comment]
Thank you very much
