### ISSUE TITLE
How does this compare to next-i18next?

### ISSUE THREAD

**Issue by martpie** [vinissimus/next-translate#87]
Hello!

Thank you for your amazing work!

It would be interesting to have a comparison between `next-translate` (which looks quite new), and the more established `next-i18next`. What are the pros and cons of both solutions, is there a trade-off while using `next-translate`? etc...

Is this something you would be willing to share? 🤗

**Comment by aralroca** [comment]
hi @martpie ! This is a very good question.

We are using `preact` in our e-commerce and we implemented `next-translate` after see that `next-i18next` was much bigger than `preact` itself. 

`next-translate` is thought about performance first: Little size + it works with static, SSG & Server.  Instead, if you want to use`next-i18next` it only works with Server.

As a drawback, we have a simpler API with the i18n basics.

Little bit comparison:

| Comparison                  | next-i18next                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | next-translate                    
| ----------------------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------- |
| Size       |     ~40kb    |  ~1kb        
| Server       |    ✅   |  ✅  
| SSG       |     ❌    |   ✅     
| Static       |    ❌    |   ✅     
| i18n API | Lot of options | Basics

![bundle-size-min](https://user-images.githubusercontent.com/13313058/76848869-b3184b00-6844-11ea-81b5-9bcc58c1f6e2.png)

**Comment by aralroca** [comment]
@martpie I'm going to close the issue if I resolved your doubts 👍
