### ISSUE TITLE
next-translate Cannot find module './locales/en/common.json'

### ISSUE THREAD

**Issue by salmanfazal01** [vinissimus/next-translate#888]
I am trying to integrate the next-translate library into my Next app, however I am getting an error when configuring the loadLocaleFrom function

This is what my i18n.js file looks like:
```
module.exports = {
  locales: ["en", "fr", "es", "ru", "ar", "zh", "hi", "sw"],
  defaultLocale: "en",
  pages: {
    "*": ["common"],
    "/": ["home"],
  },
  loadLocaleFrom: async (lang, ns) => {
    try {
      const m = await import(`./locales/${lang}/${ns}.json`);

      return {
        ...m.default,
      };
    } catch (error) {
      console.log(error);
    }
  },
};
```

And my next.config file:
```
const withPlugins = require("next-compose-plugins");
const withImages = require("next-images");
const nextTranslate = require("next-translate");

module.exports = withPlugins([withImages, nextTranslate], {
  reactStrictMode: true,
  images: {
    disableStaticImages: true,
  },
});
```

package.json versions:
```
next-translate: ^1.5.0
next: 12.1.6
react: 17.0.2
```

Even though my directory has both, the common.json and the home.json files in the correct folder structure, the loadLocaleFrom function still throws an error that looks like this:
```
Error: Cannot find module './locales/en/common.json'
    at webpackEmptyContext (D:\projects\mk\mk-academy\.next\server\pages\index.js:529:10)
    at eval (webpack-internal:///./i18n.js:64:89)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.loadLocaleFrom (webpack-internal:///./i18n.js:63:23)
    at async Promise.all (index 0) {
  code: 'MODULE_NOT_FOUND'
}
```

I did try using the appWithI18n hoc in _app.js but that doesn't solve it too. I also did try moving the locales to a different directory under src but that shouldn't make a difference. 

![image](https://user-images.githubusercontent.com/15085416/180868336-2ef0b00f-b932-4a0d-8db9-f5b998851c70.png)

**Comment by dakshinasd** [comment]
@salmanfazal01 first try printing the path which you construct. Maybe something not properly generating the path hence it cannot find the correct file. I'm talking about this part of your code ``./locales/${lang}/${ns}.json``

**Comment by salmanfazal01** [comment]
Turns out import didn't work for me but require did. Took me a while to figure this out

await require(`./locales/${lang}/${ns}.json`)

**Comment by aralroca** [comment]
Don't use `require`, it increases the bundle size... We are searching for a good solution, but for the moment I recommend this workaround to don't increase the bundle sieze: https://github.com/aralroca/next-translate/issues/851#issuecomment-1173611946

Any feedback for a solution to this will be very welcome! Thanks!
