### ISSUE TITLE
Access current lang in getStaticProps and getStaticPaths

### ISSUE THREAD

**Issue by maksymdukov** [vinissimus/next-translate#92]
I wonder if there's a way to identify current language in exported **getStaticProps** and **getStaticPaths** functions to have an ability to fetch localized data?

**Comment by aralroca** [comment]
I'm not sure about some hack, but I guess that is not possible, at least right now. 

However, I think that we should change our way to do the build in the CLI in order to provide it, using dynamic routes with `[lang]`. After that, it should be possible to get the current language via params.

Thank @maksymdukov to report this! This will be very useful for 0.13.0 release 🙂

**Comment by aralroca** [comment]
When this issue will be solved https://github.com/zeit/next.js/issues/11309 it will be trivial to wrap the lang to `getStaticProps` & `getServerSideProps` 🤞 Meanwhile, I'm going to investigate if there is another way to handle this!

**Comment by aralroca** [comment]
@maksymdukov from now on, the `lang` will be available on `getStaticProps`, `getStaticProps` and `getServerSideProps`.

I'm going to explain it better in the docs for `0.13.0` version. But a simple example:

```js
export function getStaticProps({ lang }){
   return { props: { data: getDataFromLang(lang) } }
}
```

The `0.13.0` release will be available soon. However, I released the `0.13.0-canary.1` with that feature. Please, confirm that `0.13.0-canary.1` works in your case 👏!

**Comment by maksymdukov** [comment]
@aralroca 
Wow, that was fast.
It works, many thanks. :)

However there's one rare case which regexp in **hasSpecialMethod** doesn't cover:
`export async function getStaticProps() {}`

**Comment by aralroca** [comment]
Good catch!! Thanks, this should be fixed before `0.13.0` release! Thanks!

**Comment by aralroca** [comment]
@maksymdukov `async function` should work in `0.13.0-canary.2` 👍

**Comment by ekafyi** [comment]
Hi, was wondering if accessing current lang is possible in `getStaticPaths`?
